### ISSUE TITLE
Unifi-Poller can't show more than 1 Unifi Controller?

### ISSUE THREAD

**Issue by adlisyah** [unifi-poller/unifi-poller#109]
I love your great dashboard, it's very useful, but i try to add more than 1 controller always failed to start service unifi-poller, it's can add more than 1 unifi controller ?

**Comment by davidnewhall** [comment]
It doesn't currently support multiple controllers. You could run it more than once to poll separate controllers. I'll consider adding support for this, but for now I recommend just running two copies.

**Comment by adlisyah** [comment]
I created network with unifi devices and separate 1 site for 1 controller, it will so helpfull if the fitur add on unifi-poller.
Thanks for your prompt responses! 👍

**Comment by davidnewhall** [comment]
I'm going to add this support, but just so we're clear: it's going to be a long time, and a 2.0 release when it's added. This requires changing the config file format which I've been reluctant to do in the 1.x series.
