### ISSUE TITLE
Clients with same hostname gets bundled together in client insights dashboard.

### ISSUE THREAD

**Issue by sorano** [unifi-poller/unifi-poller#132]
Greetings.
Found your nice poller when I had to troubleshoot some wireless clients that were misbehaving and was very impressed.

However I also encountered a bug that made troubleshooting hard in certain cases.

When there are multiple clients with the same hostname in the unifi controller (pretty common among android phones) all data points will be bundled together based on that hostname.

I'll attach some screenshots so you know what I mean.
In my case I had a site with 3x galaxy-xcover-4:
![image](https://user-images.githubusercontent.com/6185109/66656605-9f860a00-ec3e-11e9-8316-8a81469268cd.png)

Trying to find those clients in grafana dashboards will only identify as one client:
![image](https://user-images.githubusercontent.com/6185109/66656741-df4cf180-ec3e-11e9-80e3-6daa7cc15613.png)

And when viewing Wifi Client / AP and Client / IP data will show as if it's one and the same client that is acting strange af:
![image](https://user-images.githubusercontent.com/6185109/66656925-33f06c80-ec3f-11e9-8722-f252cf5a1418.png)

I guess a solution could be to use another identifier for clients instead of hostname, like device MAC? And perhaps present them as hostname (mac) in the dashboard.

My environment is running:
Unifi controller: 5.11.50
Unifi poller: v1.5.4

**Comment by davidnewhall** [comment]
You can change the dashboard to use any data you'd like, such as the MAC address. All of the data is in the database.

**Comment by davidnewhall** [comment]
I've been kicking the idea around in my head to add a new configuration option that allows you to control the Client's name. Something like `client_name = "{{Name}} {{MAC}}"` which would allow you to force unique names onto all clients. Is that something you think would help?

**Comment by SuperQ** [comment]
There's no need to change the labels, this can all be done at query time. At least for Prometheus.

**Comment by davidnewhall** [comment]
I agree, but I'm releasing a full suite here, with dashboards included. I'm trying to make the included dashboards as useful as possible. Some people probably deal with "iPhone" clients and I can make a pretty easy fix by making the unique identifier controllable. It's just a thought. If you know how to make the dashes more dynamic out of the box (to support a solution for this problem), give me a lesson please! :D

**Comment by davidnewhall** [comment]
The default will of course, remain unchanged. I'm just proposing a new tuning knob. This is good for users in this category:
- Larger installation.
- This problem bothers them.
- They don't want to spend time building their own dashboards.

**Comment by SuperQ** [comment]
No, really, don't change the labeling, we have separate labels, you just need to fix the dashboard selectors. That's dead simple and the correct way to deal with it.

**Comment by SuperQ** [comment]
![unifi-client-mac](https://user-images.githubusercontent.com/1320667/75324020-5691c380-5876-11ea-9116-12ff21213a22.png)

**Comment by davidnewhall** [comment]
Understood. I personally do not want MAC addresses in my graphs. I do not need it. Your solution doesn't solve _my_ problem. :(

**Comment by sorano** [comment]
Hmm, is it possible to make a condition in the dashboard like:
"if clientname exists more than once show mac otherwise not" ?

**Comment by SuperQ** [comment]
Even on a trivial network, client name is not enough to identify a device. MAC address is the only option. :-(

**Comment by davidnewhall** [comment]
100% agree, Ben, but I still don't want them in my personal graphs. These graphs are my personal graphs that I've shared with the world and made better with feedback. I do not currently have clients with shared names, but I have at times. I don't find the overlap a problem that bothers me. They're usually `iPhone` and don't do much one the network anyway. I'll keep thinking about this, but I really like the idea of just making one of the tags configurable.

**Comment by davidnewhall** [comment]
@sorano What's your take? Would you like to see name + MAC in your dashboards?

**Comment by sorano** [comment]
Yes I would @davidnewhall

**Comment by davidnewhall** [comment]
I've updated the Client dashboards with a new variable called `Identifier`. The choices are (generally) `name`, `mac` and `name,mac`. This allows you to choose how to display clients on the dashboards.  I'll have them uploaded in the next couple days.

**Comment by davidnewhall** [comment]
However using the same trick with InfluxDB is proving challenging. I sure hope you use Prometheus. :D
