### ISSUE TITLE
Speedtest-status_rundate missing from influxdb output

### ISSUE THREAD

**Issue by wally007** [unifi-poller/unifi-poller#169]
Hello,

I just installed unifi-poller on CentOS7 to see if I can get better statistics from it with influx/grafana than from built-in Unifi GUI (which is disappointing to say the least) and everything seem to work great except I can not get date/time of the **_last_** speedtest run.

In InfluxDB it seems the value is not a date or timestamp or anything that can be converted to a date as far as I can see.
Can you please shed some light how to get this info ? I can see the date in UnfiFi GUI 

![image](https://user-images.githubusercontent.com/627956/71640782-00970a00-2c91-11ea-9911-e570cbc2fd3e.png)

but in influx i get number such as 35 or 36 - which I'm not sure what it is - is not a timestamp or a date :-)

```
influx -host localhost -port 8086
>use unifi
>SELECT "speedtest-status_runtime" FROM "usg"
1577877008191708500 35
```

**Comment by davidnewhall** [comment]
`runtime` looks like how long it took to run in seconds. In your case, 35.
The speediest runtime value for a USG in the API is `rundate` - you can see the api library has that value [here](https://github.com/unifi-poller/unifi/blob/master/usg.go#L182). However, the influxdb outputs for a USG do not include that value. In other words, the graphable values are there, but not the time stamp. In Prometheus, we'd have to store the time stamp as a tag I'd think.

I did notice another value that comes from `sites` named `speedtest_lastrun` and it _is_ stored in influx, [code here](https://github.com/unifi-poller/influxunifi/blob/master/site.go#L45). You should be able to find this value in the `subsystems` table; try `SELECT "speedtest_lastrun" FROM "subsystems"`. Let me know if that has what you want.

**Comment by SuperQ** [comment]
For Prometheus, we store timestamps as values.

Something like `speedtest_lastrun_timestamp_seconds 1577891216`

**Comment by davidnewhall** [comment]
My experience with GitHub issues is: the OP will never come back, so this remains a mystery.

**Comment by zunder1990** [comment]
FYI the value of 1577877008191708500 is the epoch time stamp. Below is a epoch to human readable time converter. That value would convert to 
GMT: Wednesday, January 1, 2020 11:10:08.191 AM

https://www.epochconverter.com/

**Comment by davidnewhall** [comment]
Correct, that's the timestamp recorded in his influx database for the value, which is 35.

**Comment by wally007** [comment]
> `runtime` looks like how long it took to run in seconds. In your case, 35.
> The speediest runtime value for a USG in the API is `rundate` - you can see the api library has that value [here](https://github.com/unifi-poller/unifi/blob/master/usg.go#L182). However, the influxdb outputs for a USG do not include that value. In other words, the graphable values are there, but not the time stamp. In Prometheus, we'd have to store the time stamp as a tag I'd think.
> 
> I did notice another value that comes from `sites` named `speedtest_lastrun` and it _is_ stored in influx, [code here](https://github.com/unifi-poller/influxunifi/blob/master/site.go#L45). You should be able to find this value in the `subsystems` table; try `SELECT "speedtest_lastrun" FROM "subsystems"`. Let me know if that has what you want.

Thanks, `speedtest_lastrun` is what I was looking for. I couldnt find it in "usg" (thought all speedtest related stats were there)  - didnt think to look at "sites".

Thanks again - I think it's valuable information to have in Grafana along with the actual speedtest results.

**Comment by davidnewhall** [comment]
I'm interested in how you visualize the data in grafana. Please share. :D

**Comment by wally007** [comment]
> I'm interested in how you visualize the data in grafana. Please share. :D

For now, simple single stat panel with timestamp converted into human readable date with headline - last speed test run.

We have some Grafana "experts" at work, so I will ask them if there's a way to nicely visualize it in the graph along with speedtest results (i've converted your templated speedtest gauges into a graph like this and would like to have some kind of marker at when speedtest ran)

![image](https://user-images.githubusercontent.com/627956/71659134-bf613180-2d46-11ea-9d73-e4f3c734f417.png)

**Comment by davidnewhall** [comment]
What you described sounds about right. I actually have another idea. I'll see if I can put it together for v2. It's going to be adding an annotation query the speed test graph (which also needs to be created iirc). What this will do is put a blue line with the date at each speed test run. I could even make it show the seconds (using the value we have now). We'll see.

**Comment by davidnewhall** [comment]
I don't think I can easily add annotation to this setup. That will be a major-release feature, and I need to put some thought into how to do it dynamically so other fields can benefit from annotated updates. 

I did add this data to the USG output for Influx and Prometheus, so if nothing else, you'll be able to access it in the next release.
