### ISSUE TITLE
Awesome! Have a small issue though! No Data to Show in Grafana

### ISSUE THREAD

**Issue by daven1985** [unifi-poller/unifi-poller#171]
Good Evening,

I have installed it on Ubuntu 1804, and the log when I run it comes up as below. Though Grafana shows 
'No Data to Show'.

ladmin@sr-monitor:~$ tail -f -n100  /var/log/syslog /var/log/messages | grep unifi-poller
tail: Jan  5 09:16:42 sr-monitor unifi-poller[13085]: 2020/01/05 09:16:42 [INFO] UniFi Metrics Recorded. Sites: 1, Clients: 37, UAP: 4, USG/UDM: 1, USW: 8, Points: 100, Fields: 2886, Errs: 0, Elapsed: 95ms
Jan  5 09:17:12 sr-monitor unifi-poller[13085]: 2020/01/05 09:17:12 [INFO] UniFi Metrics Recorded. Sites: 1, Clients: 37, UAP: 4, USG/UDM: 1, USW: 8, Points: 100, Fields: 2886, Errs: 0, Elapsed: 64ms
Jan  5 09:17:42 sr-monitor unifi-poller[13085]: 2020/01/05 09:17:42 [INFO] UniFi Metrics Recorded. Sites: 1, Clients: 37, UAP: 4, USG/UDM: 1, USW: 8, Points: 100, Fields: 2886, Errs: 0, Elapsed: 52ms
Jan  5 09:18:12 sr-monitor unifi-poller[13085]: 2020/01/05 09:18:12 [INFO] UniFi Metrics Recorded. Sites: 1, Clients: 37, UAP: 4, USG/UDM: 1, USW: 8, Points: 100, Fields: 2883, Errs: 0, Elapsed: 75ms
Jan  5 09:18:42 sr-monitor unifi-poller[13085]: 2020/01/05 09:18:42 [INFO] UniFi Metrics Recorded. Sites: 1, Clients: 37, UAP: 4, USG/UDM: 1, USW: 8, Points: 100, Fields: 2883, Errs: 0, Elapsed: 117ms
Jan  5 09:19:10 sr-monitor systemd[1]: Stopping unifi-poller - Polls a UniFi controller, exports metrics to InfluxDB and Prometheus...
cannot open '/var/log/messages' for reading: No such file or directoryJan  5 09:19:10 sr-monitor systemd[1]: Stopped unifi-poller - Polls a UniFi controller, exports metrics to InfluxDB and Prometheus.
Jan  5 09:19:10 sr-monitor systemd[1]: Started unifi-poller - Polls a UniFi controller, exports metrics to InfluxDB and Prometheus.
Jan  5 09:19:11 sr-monitor unifi-poller[13141]: 2020/01/05 09:19:11 [INFO] Loading Configuration File: /etc/unifi-poller/up.conf
Jan  5 09:19:11 sr-monitor unifi-poller[13141]: 2020/01/05 09:19:11 [INFO] UniFi Poller v1.6.3-641 Starting Up! PID: 13141

Jan  5 09:19:12 sr-monitor unifi-poller[13141]: 2020/01/05 09:19:12 [INFO] Found 1 site(s) on controller: default (Default)
Jan  5 09:19:12 sr-monitor unifi-poller[13141]: 2020/01/05 09:19:12 [INFO] Polling UniFi Controller at https://192.168.1.3:8443 v5.13.5 as user influx. Sites: [all]
Jan  5 09:19:12 sr-monitor unifi-poller[13141]: 2020/01/05 09:19:12 [INFO] Everything checks out! Poller started, InfluxDB interval: 30s
Jan  5 09:19:42 sr-monitor unifi-poller[13141]: 2020/01/05 09:19:42 [INFO] Logging Measurements to InfluxDB at http://127.0.0.1:8086 as user unifi
Jan  5 09:19:42 sr-monitor unifi-poller[13141]: 2020/01/05 09:19:42 [INFO] UniFi Metrics Recorded. Sites: 1, Clients: 37, UAP: 4, USG/UDM: 1, USW: 8, Points: 100, Fields: 2883, Errs: 0, Elapsed: 61ms

**Comment by davidnewhall** [comment]
I'll have more time to provide a better answer later, I'm about to head to bed. I'll throw this at you real quick while I'm still awake:

- Check the data source.
- Check the variables in the dashboards. (make sure they show data)
- Look at the closed issues in this repo (this is a common problem with pretty easy fixes).
- Jump on Discord, might be someone there who can help.

Let me know what your variables look like and I can provide better more guidance. Screenshots do great. Questions: Do any of the dashboards work? Do any graphs work?

**Comment by daven1985** [comment]
Was part of the datasource. Database name was wrong.

Cheers.

**Comment by davidnewhall** [comment]
Rad! Enjoy!
