### ISSUE TITLE
docs: Develop Native CloudKey Support (Run poller ON the CK)

### ISSUE THREAD

**Issue by daven1985** [unifi-poller/unifi-poller#172]
I tried to installed this my Cloud Key, worked all until the Unifi script install.

Unknown Architecture. Submit a pull request to fix this, please.

Any way it can support Debian?
Cheers

**Comment by davidnewhall** [comment]
CloudKey isn't that simple. I've only seen one person install this on a cloudkey, and I think he used Docker. The install script is for normal Linux distributions, not embedded operating systems, like the CloudKey. The script just downloads a package and installs it. Can you install any of the packages on the cloudkey? There are four debian packages available on the releases page.

**Comment by daven1985** [comment]
I'll have look. The Unifi Poller is the last thing to install... Grafana and InfluxDB installed without an issue.

**Comment by davidnewhall** [comment]
Unfortunately I don't have a CloudKey to test this on. I have no way to provide directions or installation instructions for that device because I've never used one. If you have an extra CK you can send my way I guarantee a wiki article with instructions on how to make it work. I'll even send it back to you.

**Comment by davidnewhall** [comment]
I found a wonderful user willing to send me a CloudKey. Hope to have more on this topic in the coming weeks.

**Comment by daven1985** [comment]
@davidnewhall ... that's exciting. Let me know if you need a tester?

**Comment by davidnewhall** [comment]
I think he forgot :(

**Comment by daven1985** [comment]
@davidnewhall ... I forgot?

**Comment by davidnewhall** [comment]
Sorry, no, the person who was sending me a CK. I just hit him on Discord and he said he's still going to send it 🤞

**Comment by daven1985** [comment]
Okay… I thought for a second I had forgotten something. HAHA. Have a good day.

**Comment by hatemzidi** [comment]
hello all, 
i just bought a Cloudkey Gen 2 Plus and unifi-poller seems to work like a charm.

i was running unifi controller under docker with {client, usw, usg, uap} insight dashboards on grafana, i migrated this morning to the cloudkey gen 2+ and all is ok 👍

**Comment by davidnewhall** [comment]
I think he forgot :( oh well... This may not happen.

**Comment by vijaytejak** [comment]
> hello all,
> i just bought a Cloudkey Gen 2 Plus and unifi-poller seems to work like a charm.
> 
> i was running unifi controller under docker with {client, usw, usg, uap} insight dashboards on grafana, i migrated this morning to the cloudkey gen 2+ and all is ok 👍

Hey could you send the instructions on how you are able to achieve, installing poller on cloud key gen2 plus.

**Comment by hatemzidi** [comment]
@vijaytejak ah, sorry i may misexplained.
i have unifi-poller working on another machine, i just configured it with the cloud key's ip.

**Comment by davidnewhall** [comment]
> Hey could you send the instructions on how you are able to achieve, installing poller on cloud key gen2 plus.

https://github.com/unifi-poller/unifi-poller/wiki/Installation

**Comment by vijaytejak** [comment]
> > Hey could you send the instructions on how you are able to achieve, installing poller on cloud key gen2 plus.
> 
> https://github.com/unifi-poller/unifi-poller/wiki/Installation

Hey will this work on cloudkey gen2plus

**Comment by vijaytejak** [comment]
> hello all,
> i just bought a Cloudkey Gen 2 Plus and unifi-poller seems to work like a charm.
> 
> i was running unifi controller under docker with {client, usw, usg, uap} insight dashboards on grafana, i migrated this morning to the cloudkey gen 2+ and all is ok 👍

Can you brief more how did you use cloudkey and get data, i mean, i have cloudkey up and running, but the unifi poller is not working on it, what to do now ?

**Comment by davidnewhall** [comment]
@vijaytejak,

Please open a new issue; this is not your issue and not related to your problem. This issue is here for me to gauge how many people are interested in running Poller _on_ their CloudKey device.

When you open a new issue, please explain how you installed poller, and provide your configuration and log output messages.

**Comment by shrimpza** [comment]
For what it's worth, I'm having good success running the arm64 poller binary with a simple systemd service definition on my CK Gen2 without issues. I'm using an off-site InfluxDB and Grafana setup, so didn't need those on the CK itself.

I didn't use the install scripts - I just grabbed the binary from the releases page and dropped it into `/usr/bin/`, added configuration based on `up.conf.example` as `/etc/unifi-poller/up.conf`, and created a service definition as `/etc/systemd/system/unifi-poller.service`.

In principal, native CK Gen2 support certainly exists already and works like a charm with 10 minutes of manual setup.

**Comment by davidnewhall** [comment]
@shrimpza Thank you for your details. I am aware of a few folks running this app on their CK. I'm leaving this issue open to remind me, or someone else, to write docs on how to do what you did to run this on a CK. Ultimately, I'd like to figure out the same thing for the UDM/UDMP.

**Comment by vijaytejak** [comment]
> For what it's worth, I'm having good success running the arm64 poller binary with a simple systemd service definition on my CK Gen2 without issues. I'm using an off-site InfluxDB and Grafana setup, so didn't need those on the CK itself.
> 
> I didn't use the install scripts - I just grabbed the binary from the releases page and dropped it into `/usr/bin/`, added configuration based on `up.conf.example` as `/etc/unifi-poller/up.conf`, and created a service definition as `/etc/systemd/system/unifi-poller.service`.
> 
> In principal, native CK Gen2 support certainly exists already and works like a charm with 10 minutes of manual setup.

Hey thanks for the response, could you share the step by step instructions that you followed.

**Comment by Waffull** [comment]
> @vijaytejak,
> 
> Please open a new issue; this is not your issue and not related to your problem. This issue is here for me to gauge how many people are interested in running Poller _on_ their CloudKey device.

I'm definitely interested.  I offloaded Protect to the UNVR4, so my CK2+ is only running the controller now... plenty of processing power for unifi-poller now ;)

Will unifi-poller be wiped out during firmware updates if we did this?

**Comment by camprr** [comment]
I've been trying to install docker on my cloud key gen 2, but no luck, running into a filesystem issue due to the very old kernel the controller comes with (3.9). Might have to run influx, grafana and the poller bare metal.

**Comment by davidnewhall** [comment]
Would not recommend running InfluxDB on a CloudKey. That software requires at least 16GB ram.

**Comment by camprr** [comment]
Done: https://www.robertcampbell.dev/2020/07/installing-unifi-poller-influxdb-and.html  Memory usage does not seem crazy, influx uses 'only' 5% memory out of the 2Gbytes.

**Comment by davidnewhall** [comment]
Keep your retention low and that should stay true. Thanks for the doc, I'll find a place to integrate this!

**Comment by camprr** [comment]
Maybe a 'crazy' point, but can't this ticket be closed now, as the unifi-poller has been 'proven' to run on Cloud key 2? Bug solved through documentation ;-)

**Comment by davidnewhall** [comment]
The documentation is not findable at the moment. I'll close this issue once I add appropriate links to your page from the wiki (and probably save a copy of it somewhere in case your page becomes inaccessible or out of date). Really appreciate your work here, and yes, you've solved this issue. :) Thanks!

**Comment by davidnewhall** [comment]
Since we're here.. Does the cloudkey expose statistics we can collect with poller and graph in grafana? CPU/memory/disk usage, etc. Would you know what API paths those live under? Wanna help me figure it out? :D Can you jump on Discord?

**Comment by camprr** [comment]
Just for who-ever get to this page, use "telegraf" to do this: https://www.influxdata.com/time-series-platform/telegraf/  there are some plugins you can enable to get more information. I have also found an effort to 
[[inputs.influxdb]]
[[inputs.netstat]]
[[inputs.net]]
[[inputs.interrupts]]

**Comment by davidnewhall** [comment]
Docs will soon be updated, and we'll find a cozy place for this. https://github.com/unifi-poller/unifi-poller/issues/172#issuecomment-665258403 Thanks!

**Comment by davidnewhall** [comment]
Looks like got these directions transferred into this page https://unifipoller.com/docs/install/cloudkey 
Attribution provided at the top. Thank you!
