### ISSUE TITLE
Controller IP blocked on 127.0.0.1 (ignoring up.conf?)

### ISSUE THREAD

**Issue by KZ-Vince** [unifi-poller/unifi-poller#173]
Hi Guys,

I've been stumbling on the same issue for days: unifi-poller seems to ignore my up.conf file details and tries to establish a connection the CloudKey on 127.0.0.1 no matter what is written in the config file under the unifi or the unifi.defaults url sections. I have tried the Windows precompiled version and also a Linux install on the CloudKey. No luck. All tcp connections attemps to the CloudKey go to 127.0.0.1 and I get an error message saying that the remote machine refused the connection.

Any idea on what I'm missing here? Thanks.

**Comment by davidnewhall** [comment]
What version?

**Comment by KZ-Vince** [comment]
Hi David, thanks for your swift reply. I'm using version 1.6.3, "unifi-poller.amd64.exe.zip" for the pre-compiled Windows version and the Linux one deployed on the CloudKey is rpm (1.6.3 again). I've used a copy/paste of the instructions mentioned in the installation section here.

I'm indeed calling it mentioning the `-c /path/to/up.conf for both versions`

What exactly do you mean by 

> running it manually?

Thanks!

**Comment by KZ-Vince** [comment]
Hi, got to the bottom of it.  I replaced the `up.conf` file with the `up.conf.example` which seems to be a simpler version. I changed its details with the applicable ones and everything works like a breeze now :)

**Comment by davidnewhall** [comment]
Sounds like you were using the up.conf.example from the repo instead of the package you installed. The version in the repo is for unifi-poller v2. Glad you figured it out!
