### ISSUE TITLE
WAN/LAN Throughput legend or pull issue

### ISSUE THREAD

**Issue by rodrigolangella** [unifi-poller/unifi-poller#174]
Hi,

I'm not sure if this is a puller issue or Grafana but my WAN and LAN throughput are displaying incorrect values, for example  I got a 20Mbits internet link and at the Unifi portal I was getting 100% of the link being used, so on Grafana because it shows MB/s intead of Mb/s I should be getting -2.5MB (download)  but instead Grafana was displaying 6MBs.   

I'm trying to get more deep info at the moment and I thought would be gread to write this in case someone is having the same issue

**Comment by davidnewhall** [comment]
Influx or Prometheus? Are you using the latest dashboard on Grafana? Can you share some screenshots of the unifi controller interface and the graph in Grafana?

**Comment by rodrigolangella** [comment]
Hi David,  Sorry for this lack of info.   I managed to fix that :) and I 'll show you what it was before and what it looks like now:

I'm using Influx with a dashboard I downloaded on 7/01,  and I got a 18Mbit internet pipe. For this test I left a big file downloading for a few minutes to generate some WAN traffic

**Before:**
On the Unifi portal I could see Internet capacity going up to 85% (~14Mbits) and when I looked at Grafana I've seen -5.291MBs which converted is 42.328Mbits
![image](https://user-images.githubusercontent.com/59672796/72038307-afb88e80-32ec-11ea-89a6-b4c43e8cf459.png)

**Now**
I've changed the SELECT field to rx_bytes-r and tx_bytes-r (was rx_bytes/tx_bytes before) and multiplied the result by 8 and the results are now correct as you can see on the images when comparing USG Portal and Grafana.  Note I removed derivative option.

![Annotation 2020-01-09 1516222221](https://user-images.githubusercontent.com/59672796/72040195-894a2180-32f3-11ea-9e23-1b496d97b68e.png)

![image](https://user-images.githubusercontent.com/59672796/72040307-dded9c80-32f3-11ea-8aa8-e686e7dd7761.png)


I hope that helps you .

**Comment by davidnewhall** [comment]
I'mma leave this open to remind me to look at/fix that graph. I'm tied up right now, but I will get back into this project soon.

**Comment by davidnewhall** [comment]
So I looked at this. I get pretty much identical data flow from both metrics. They look a little different which is expected, but they're close enough that it tells me both are accurate.
![Screen Shot 2020-01-30 at 10 03 38 PM](https://user-images.githubusercontent.com/2402929/73516198-7daac180-43ac-11ea-8a93-daa069eae813.png)

The next release of this dashboard will have both views programmed, but only one will be visible.
