### ISSUE TITLE
Client Insights missing TX/RX stats - Prometheus

### ISSUE THREAD

**Issue by truncsphere** [unifi-poller/unifi-poller#175]
It appears the Client Insights Dashboard for the Wired/Wireless devices does not contain total TX/RX stats anymore. Is this a limitation with Prometheus?

**Comment by davidnewhall** [comment]
What versions of UniFi Controller, Grafana, Poller and Prometheus are you running? Can you show me a screenshot of the broken dashboard? Does poller output any errors?

**Comment by truncsphere** [comment]
Unifi Controller = 5.12.35; Grafana = 6.5.2; Poller= 1.6.3 Prometheus = latest
No errors on the Poller. These stats were available in the influxDB version of the Dashboards for what it's worth. 
![image](https://user-images.githubusercontent.com/16292618/72191225-6896d000-33b6-11ea-8d2d-f69274596a0c.png)

**Comment by davidnewhall** [comment]
I think I just removed it from there since traffic is shown below. You can probably add that metric back real easy.

**Comment by davidnewhall** [comment]
I just looked at this a bit more. In Prometheus, you can only really get one metric value into a graph. I chose `rate` in this case. The other values are just labels. There is probably a way to join two metrics, but I'm not real good with Prometheus and I'm not sure how. @SuperQ may be able to figure it out. :D

For an easy workaround, you can do this. Change the query from `rate` (what it is now) to:
```
unifipoller_client_receive_bytes_total+unifipoller_client_receive_bytes_total{site_name=~"$Site", name=~"$Client", ap_name=~"$AP"}
```

That should give you what you want. You'll have to rename the column in the Visualize settings.

**Comment by davidnewhall** [comment]
Keep in mind this table does not respect the time range, and you will see accumulated totals since the unifi controller started up. I do not know how to fix this, and that's where @SuperQ's help may be useful. It may not really be something that can be fixed. Prometheus and tables don't play that well together.

**Comment by truncsphere** [comment]
Understood. I'll take a closer look at it.

**Comment by SuperQ** [comment]
Grafana can render multiple queries by matching label values for Prometheus.

[ap_rate_panel.json.gz](https://github.com/unifi-poller/unifi-poller/files/4049135/ap_rate_panel.json.gz)

**Comment by truncsphere** [comment]
> 
> 
> Grafana can render multiple queries by matching label values for Prometheus.
> 
> [ap_rate_panel.json.gz](https://github.com/unifi-poller/unifi-poller/files/4049135/ap_rate_panel.json.gz)
> 
> ![Screenshot from 2020-01-11 10-01-36](https://user-images.githubusercontent.com/1320667/72201940-23c47500-345a-11ea-8e1a-ff770b9716c6.png)

I duplicated the original panel so I could experiment. When I enter the new query A you have listed, it shows all of my devices vs just wireless devices. How would I filter it out so it only shows wireless devices still?

**Comment by SuperQ** [comment]
@truncsphere Add `wired="false"` to the label filter list in the query to only show wifi in that table.

**Comment by davidnewhall** [comment]
If that doesn't work, for some reason, I prefer `wired != "true"`.

My question is: Can we make this show data transfer totals for the _selected time range_ without using _Instant_ ?

**Comment by SuperQ** [comment]
@davidnewhall No, instant query is the right thing to do. Grafana provides the `$__range` template variable to give you the selected time range. If you want the transfer totals, not the average transfer rate, switch the `rate()` for `increase()`.

For example:
```
sum by (name, ap_name, mac, oui, ip, site_name) (
  increase(unifipoller_client_receive_bytes_total{wired!="true", site_name=~"$Site", name=~"$Client", ap_name=~"$AP"}[$__range])
)
```

**Comment by davidnewhall** [comment]
These are the examples I need more of :D

**Comment by davidnewhall** [comment]
I'm going to close this. I've updated the dashboard locally, and it will be added to grafana.com with the release of v2.
