### ISSUE TITLE
Show Wireless clients for Client Insights Panel 

### ISSUE THREAD

**Issue by truncsphere** [unifi-poller/unifi-poller#176]
I'm running the Prometheus Dashboards and for the Amazon/Echo and Cameras panel, it currently doesn't show wireless clients. 

I was asked to open this issue so that the option could be added.

**Comment by davidnewhall** [comment]
Hello. Those panels use a regex to match names of devices. The device names have to begin with `amazon` and `camera` respectively. Renaming your devices should make them show up. Alternatively you can edit the graph to suite your environment.

**Comment by truncsphere** [comment]
@davidnewhall 
On the Amazon panel (repurposed for Roku's), I have my wired roku show up. It's only the wireless Roku's that aren't showing up.

**Comment by davidnewhall** [comment]
Got it. I'll adjust the next release of those graphs to include wireless as well as wired devices.

**Comment by davidnewhall** [comment]
This has been fixed locally and will be included in poller v2. Closing it out here. Thanks for the report!
