### ISSUE TITLE
Installation stops at "makevendor" on Mac

### ISSUE THREAD

**Issue by lundejd** [unifi-poller/unifi-poller#182]
I've tried installing this on two different Macs, one with a fresh install of homebrew.  Both are getting this error that interrupts the installation:

Server-40-4k:~ jd$ brew install golift/mugs/unifi-poller
==> Tapping golift/mugs
Cloning into '/usr/local/Homebrew/Library/Taps/golift/homebrew-mugs'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 10 (delta 4), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (10/10), done.
Tapped 6 formulae (40 files, 44.4KB).
==> Installing unifi-poller from golift/mugs
==> Installing dependencies for golift/mugs/unifi-poller: go and dep
==> Installing golift/mugs/unifi-poller dependency: go
==> Downloading https://homebrew.bintray.com/bottles/go-1.13.6.mojave.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/78/78522946effa0cdb1f6ed8e9ea1e626c10084667a92f94292f2647c38508ac6d?__gda__=exp=1579707724~hmac=0d15e47ceedb03e95ad565f76730752ba534492b431
######################################################################## 100.0%
==> Pouring go-1.13.6.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/go/1.13.6: 9,275 files, 414.1MB
==> Installing golift/mugs/unifi-poller dependency: dep
==> Downloading https://homebrew.bintray.com/bottles/dep-0.5.4.mojave.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/33/33200b5422fac00416ac44c7c28ad5aa627b845cd4d9aeb7002f7d41304deab0?__gda__=exp=1579707752~hmac=525b5d14ba89b2c84affd9961250008dbe135afe314
######################################################################## 100.0%
==> Pouring dep-0.5.4.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/dep/0.5.4: 7 files, 11.6MB
==> Installing golift/mugs/unifi-poller
==> Downloading https://golift.io/unifi-poller/archive/v2.0.0-alfalfa1.tar.gz
==> Downloading from https://codeload.github.com/unifi-poller/unifi-poller/tar.gz/v2.0.0-alfalfa1
######################################################################## 100.0%
==> makevendor
Last 15 lines from /Users/jd/Library/Logs/Homebrew/unifi-poller/01.makevendor:
2020-01-22 09:30:37 -0600

makevendor

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/golift/homebrew-mugs/issues

Server-40-4k:~ jd$

**Comment by davidnewhall** [comment]
Yeaaaaaa.... I'll get this fixed as soon as I can.

**Comment by davidnewhall** [comment]
I just reverted the homebrew file to version 1.6.3. Give it another shot, please!

**Comment by lundejd** [comment]
Works!  Thanks man!

**Comment by davidnewhall** [comment]
Made a note to make sure this works with next release. Thanks for the report!
