### ISSUE TITLE
How is "uptime" formatted?

### ISSUE THREAD

**Issue by AlfaJackal** [unifi-poller/unifi-poller#183]
I am trying to create an overview of my guests connected. I wanted to use the uptime measurement for it. Could you tell me more about the scale? Is it milliseconds?

![grafik](https://user-images.githubusercontent.com/17096950/73175407-62b92280-410a-11ea-85b4-9d7e702586d7.png)

Best,
AJ

**Comment by davidnewhall** [comment]
It's a counter of seconds.

**Comment by davidnewhall** [comment]
Keep in mind, this counter may reset if you restart the controller. I'm really not sure how stable it is.
