### ISSUE TITLE
Template variable service failed Network Error: Request-URI Too Large(414)

### ISSUE THREAD

**Issue by WouterLS** [unifi-poller/unifi-poller#185]
If I use All sites on the filters i'm getting this error

Template variable service failed
Network Error: Request-URI Too Large(414)

for the client/channel stats I have to narrow down on clients too.

Somehow the request is to large with 'all' selected. It seems to be talked about on this issue: https://github.com/grafana/grafana/issues/8109
But i'm unsure on the fix.

Could someone help?

**Comment by davidnewhall** [comment]
Maybe try changing the All value for Clients to `.*` under variables in the dashboard settings. I've never seen this. How many clients do you have?

**Comment by WouterLS** [comment]
Yeah, that does the trick.
Aparently enoough to cause trouble.

UniFi Metrics Recorded. Sites: 63, Clients: 2578, UAP: 139, USG/UDM: 0, USW: 108, IDS Events: 0, Points: 5175, Fields: 154112, Errs: 0, Elapsed: 4.837s

**Comment by davidnewhall** [comment]
nice! You're going to really f-up that InfluxDB now. :)

**Comment by davidnewhall** [comment]
I made this the default for _all_ variables in all dashboards.

**Comment by craguilar** [comment]
This works.
