### ISSUE TITLE
Filter for different SSIDs in Network Sites Dashboard

### ISSUE THREAD

**Issue by KLESYS** [unifi-poller/unifi-poller#186]
Hi,

first we wanted to say great work with this solution to easily pull data from Unifi Controllers and displaying it so good looking.
We are using the Dashboards with InfluxDB in the background and pull data for different sites and locations. The Network Sites Dashboard is a great overview for us, but we would like to difference between the SSIDs installed in those locations.
In the Client Insights Dashboard you have the ability to filter the different sites, access points, switches and clients. In the Wireless Devices table the ssid is displayed.
It is possible to easily add such an filter to the Network Sites dashboard and filter the Data Transfer + Client Counts for one specific SSID or multiple?

Thank you for your work. I am looking foward to your answer.

Greetings
KLESYS

**Comment by davidnewhall** [comment]
Hello!

Unfortunately, the data powering the network sites dashboard does not have any notion of SSIDs. It contains Site info, not Wireless info.

Fortunately, Grafana is very flexible and you can make your own dashboards from data in any  source. My recommendation to you, and to anyone else looking for custom data displays, is to create those yourself. I do not mind feature requests, but in this case it's not a feature an I implement. The dashboards I've created provide a solid foundation to build from, but they are far from covering every possible use case. I've provided these dashes as examples and to give new users some initial data to display. From there, you should make copies of them and slice and dice the data in a way that works for you.

You're going to want to use the data powering the Clients and UAP dashboards to find user counts per SSID. I'm releasing updated dashboards with poller v2. Soon.

**Comment by davidnewhall** [comment]
I've looked over both the prometheus and influxdb sites dashboards. Adding this functionality breaks the separation concept I have with these dashboards. I highly recommend creating your own custom dashboards that have the data you want. If you need help with that, there are professional services available. Good luck!
