### ISSUE TITLE
cannot unmarshal number into Go struct field Client.data.dhcpend_time of type int

### ISSUE THREAD

**Issue by jwever** [unifi-poller/unifi-poller#187]
I am running the latest docker container on a new install, but getting the following error ...
`2020/01/30 18:23:01 [INFO] Loading Configuration File: /etc/unifi-poller/up.conf
2020/01/30 18:23:01 [INFO] UniFi Poller v1.6.3-641 Starting Up! PID: 1
2020/01/30 18:23:01 [INFO] Found 1 site(s) on controller: default (Default)
2020/01/30 18:23:01 [INFO] Polling UniFi Controller at https://192.168.1.1:8443 v5.12.22 as user influx. Sites: [all]
2020/01/30 18:23:01 [INFO] Everything checks out! Poller started, InfluxDB interval: 30s
2020/01/30 18:23:31 [INFO] Logging Measurements to InfluxDB at http://influxdb:8086 as user unifi
2020/01/30 18:23:31 [ERROR] unifi.GetClients(): json: cannot unmarshal number 4123168624 into Go struct field Client.data.dhcpend_time of type int`

I have dropped & recreated the influx db, but still get the same error. It is not clear to me if this indicates bad data being returned from my controller or something unexpected in the code. Any advice on how to fix this issue?

**Comment by davidnewhall** [comment]
Looks like unifi changed a json type. This will likely require patching and a new version to fix it.

**Comment by PianSom** [comment]
Hello @jwever - I am running that docker version with controller 5.13.9 on a CK2, and am not seeing any errors. Maybe try a controller update to that testing version (you may need to sign up to the beta program)?

**Comment by jwever** [comment]
@PianSom Unfortunately my controller is running on a UDM. I have yet to see any updates for the controller which is actually bundled with the firmware on that device. I looked for beta versions, but did not see any for the UDM.

**Comment by davidnewhall** [comment]
@jwever Can you send me the output of `unifi-poller -j d`? You'll need to install it outside of the docker container, or download a binary from the releases pages. It's really easy to do. This command (using `-j`) makes the app print out the json from the controller and exit. The only other thing it needs is a config file, which contains your unifi controller auth data.

This data contains MACs, ip addresses and the names of your devices. If that's important for you to keep secret you can [email](mailto:david@sleepers.pro) me the file or send it on discord. I just need to see what changed so I can account for it in the next release.

**Comment by jwever** [comment]
@davidnewhall. I just sent you the output log on discord. Thanks.

**Comment by davidnewhall** [comment]
it looks like number has become larger than an integer. I can fix this in the next release.

```
      "dhcpend_time": 4123169864,
      "dhcpend_time": 0,
      "dhcpend_time": 70,
      "dhcpend_time": 4123168674,
      "dhcpend_time": 4123168704,
      "dhcpend_time": 4123169764,
      "dhcpend_time": 4123168784,
      "dhcpend_time": 40,
      "dhcpend_time": 4123168634,
      "dhcpend_time": 1123320,
      "dhcpend_time": 0,
      "dhcpend_time": 4123168744,
      "dhcpend_time": 4123169014,
      "dhcpend_time": 4123168704,
      "dhcpend_time": 4550,
      "dhcpend_time": 4123168834,
      "dhcpend_time": 0,
      "dhcpend_time": 4123169724,
      "dhcpend_time": 0,
      "dhcpend_time": 0,
      "dhcpend_time": 4123168684,
```

**Comment by davidnewhall** [comment]
This commit fixes the issue: https://github.com/unifi-poller/unifi/commit/b3ed8bd7d27a170f99739350cbc08ecd1cb4bb90

I'm going to close this out now. Version 2.0 will not have this same bug. Thank you so much for the report!

**Comment by davidnewhall** [comment]
You can try v2 now. The beta is stable.

**Comment by jwever** [comment]
Thanks, I will give v2 a try soon with a new db to confirm; however, I also wanted to report that after rebooting my UDM, the poller worked again. I'm unsure what caused such a high lease time.

**Comment by davidnewhall** [comment]
That's actually really good to know! Thanks for the update! I feel like you ran into some where time bug. Maybe the time on the UDM changed and the lease end times got skewed. Hard to say, but it's good to know a reboot fixed it.
