### ISSUE TITLE
influxdb input field type conflict

### ISSUE THREAD

**Issue by weidercs** [unifi-poller/unifi-poller#188]
Version: UniFi Poller v2.0.0-rc1-753
I tried dropping unifi and re-adding the influxdb database, still happens.
UDM with 5 AP and 4 switches.
Happens every 30 seconds:
`influxdb.Write(points): {"error":"partial write: field type conflict: input field \"state\" on measurement \"uap\" is type string, already exists as type integer dropped=1"}`

**Comment by davidnewhall** [comment]
How confident are you that you really dropped the db? Can you try dropping it, and not recreating it? Make sure poller gives you a different error. I'm having a hard time understanding how this could "come back" after the db was dropped.

**Comment by weidercs** [comment]
Docker...
Stopped Unifi-Poller container.
Dropped DB:
```
InfluxDB shell version: 1.7.9
> show databases
name: databases
name
----
_internal
collectd
traefik
unifi
> drop database unifi
> show databases
name: databases
name
----
_internal
collectd
traefik
> create database unifi
> show databases
name: databases
name
----
_internal
collectd
traefik
unifi
>
```
Started Unifi-Poller Container:
```
2020/02/05 00:40:41 [INFO] Loading Configuration File: /etc/unifi-poller/up.conf


2020/02/05 00:40:41 [INFO] UniFi Poller v2.0.0-rc1-753 Starting Up! PID: 1


2020/02/05 00:40:42 [INFO] Found 1 site(s) on controller https://10.0.1.1:8443: default (Default)


2020/02/05 00:40:42 [INFO] Configured UniFi Controller at https://10.0.1.1:8443 v5.12.42 as user influx. Sites: [all]


2020/02/05 00:40:42 [INFO] Everything checks out! Poller started, InfluxDB interval: 30s


2020/02/05 00:40:42 [INFO] Prometheus exported at https://0.0.0.0:9130/ - namespace: unifipoller


2020/02/05 00:41:12 [ERROR] influxdb.Write(points): {"error":"field type conflict"}


2020/02/05 00:41:42 [ERROR] influxdb.Write(points): {"error":"partial write: field type conflict: input field \"state\" on measurement \"uap\" is type string, already exists as type integer dropped=1"}
```

Then I tried no DB (drop with no create):
```
2020/02/05 00:43:39 [INFO] Loading Configuration File: /etc/unifi-poller/up.conf


2020/02/05 00:43:39 [INFO] UniFi Poller v2.0.0-rc1-753 Starting Up! PID: 1


2020/02/05 00:43:40 [INFO] Found 1 site(s) on controller https://10.0.1.1:8443: default (Default)


2020/02/05 00:43:40 [INFO] Configured UniFi Controller at https://10.0.1.1:8443 v5.12.42 as user influx. Sites: [all]


2020/02/05 00:43:40 [INFO] Everything checks out! Poller started, InfluxDB interval: 30s


2020/02/05 00:43:40 [INFO] Prometheus exported at https://0.0.0.0:9130/ - namespace: unifipoller


2020/02/05 00:44:10 [ERROR] influxdb.Write(points): {"error":"database not found: \"unifi\""}
```

**Comment by davidnewhall** [comment]
Turn on debug and show me the output please.
`-e UP_POLLER_DEBUG=true`

**Comment by davidnewhall** [comment]
oh, I think I know what's happening...........

**Comment by davidnewhall** [comment]
yup found it, will have a fix for you in ~30m

**Comment by davidnewhall** [comment]
I didn't run into this myself because I haven't yet tested a UDM (non-pro). There are some differences in how the UAP in UDM is collected vs a normal UAP.

The new docker tag is building now and should be ready in about 15 minutes. I'll update again shortly.

**Comment by weidercs** [comment]
Thanks! Really appreciate it.

**Comment by weidercs** [comment]
BOOM, that works!  Thank you!  Closing issue.
```

2020/02/05 01:30:50 [INFO] UniFi Metrics Recorded. Sites: 1, Clients: 62, UAP: 5, USG/UDM: 1, USW: 4, IDS Events: 0, Points: 138, Fields: 4252, Errs: 0, Elapsed: 44ms


2020/02/05 01:31:20 [INFO] UniFi Metrics Recorded. Sites: 1, Clients: 62, UAP: 5, USG/UDM: 1, USW: 4, IDS Events: 0, Points: 138, Fields: 4252, Errs: 0, Elapsed: 13ms
```

**Comment by davidnewhall** [comment]
Grab `master` again. I made two updates. The second just removes the `state` field entirely. Glad it's working!

**Comment by davidnewhall** [comment]
It's actually still building. has another couple minutes

**Comment by davidnewhall** [comment]
It's done now. Pull `master` again for the latest and greatest. I'm trying to get v2 officially release tomorrow. Thanks for your report!

**Comment by weidercs** [comment]
Pulled latest, still working.  Thanks again
