### ISSUE TITLE
Wrong ENV Variable Names in docker-compose.yml

### ISSUE THREAD

**Issue by benblustey** [unifi-poller/unifi-poller#191]
The ENV variables for the chronograf docker setup are incorrect. They should be INFLUXDB_USER & INFLUXDB_PASS respectively on lines 26 & 27 of the docker-compose.yml file.

https://github.com/unifi-poller/unifi-poller/blob/master/init/docker/docker-compose.yml#L26-L27

**Comment by davidnewhall** [comment]
@scyto please confirm. Very possibly I messed those up.

**Comment by davidnewhall** [comment]
I was going to make a PR for review, but I noticed in the readme is lists other values for password. Can someone confirm? Should we pass admin values, or..?  https://hub.docker.com/_/influxdb I've never run influx via docker, and I want to make sure this is right! :) Thanks!

**Comment by jonbloom** [comment]
Looks like the .env example uses INFLUXDB_USER not INFLUXDB_USERNAME. That's an easy fix, but I actually like USERNAME vs USER and PASSWORD vs PASS. Thoughts?

**Comment by davidnewhall** [comment]
I actually prefer the shorter terms haha, but enough to tell someone else they're doing it wrong. 

My concern is, why doesn't the readme for the influx container mention `INFLUXDB_PASS` at all? Is it a deprecated variable?

**Comment by jonbloom** [comment]
Looks like the var is ‘INFLUXDB_USER_PASSWORD`.

**Comment by davidnewhall** [comment]
Please test before committing the change. :D <3
