### ISSUE TITLE
docker compose - variable is not set

### ISSUE THREAD

**Issue by xteeio** [unifi-poller/unifi-poller#195]
Any idea? Not detecting the variable
`xxx@xxx01:~/Github/unifi-poller/init/docker$ docker-compose version
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
xxx@xxx01:~/Github/unifi-poller/init/docker$`

`xxx@xxx01:~/Github/unifi-poller/init/docker$ sudo docker-compose up -d
WARNING: The INFLUXDB_DB variable is not set. Defaulting to a blank string.
WARNING: The INFLUXDB_HTTP_AUTH_ENABLED variable is not set. Defaulting to a blank string.
WARNING: The INFLUXDB_ADMIN_USER variable is not set. Defaulting to a blank string.
WARNING: The INFLUXDB_ADMIN_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The GRAFANA_USERNAME variable is not set. Defaulting to a blank string.
WARNING: The GRAFANA_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The POLLER_TAG variable is not set. Defaulting to a blank string.
WARNING: The UNIFI_USER variable is not set. Defaulting to a blank string.
WARNING: The UNIFI_URL variable is not set. Defaulting to a blank string.
WARNING: The POLLER_DEBUG variable is not set. Defaulting to a blank string.
Pulling influxdb (influxdb:latest)...`

**Comment by jonbloom** [comment]
What's your environment file called? By default, it should be just `.env` in the same folder as the `docker-compose.yml` file.

https://docs.docker.com/compose/environment-variables/#the-env-file

**Comment by davidnewhall** [comment]
From the recently updated [Docker wiki](https://github.com/unifi-poller/unifi-poller/wiki/Docker#docker-compose):

- Fill out the `docker-compose.env.example` file with the appropriate values
- Save the file as `.env` in the same folder as your `docker-compose.yml` file.
- Run `docker-compose up -d`

**Comment by xteeio** [comment]
Yes i did all that already but stil not reading the .env file was the reason why i reported here.

`xxx@xxx01:~/Github/unifi-poller/init/docker$ ls
docker-compose.env  docker-compose.yml  Dockerfile  hooks  README.md
xxx@xxx01:~/Github/unifi-poller/init/docker$ 
`

**Comment by jonbloom** [comment]
The file needs to be called `.env`, not `docker-compose.env`

**Comment by davidnewhall** [comment]
@xteeio Were you able to figure this out?

**Comment by xteeio** [comment]
It works. Thanks.

**Comment by xteeio** [comment]
so after i spin up all the docker container using docker compose, do i still need to create influxdb user? I can see the db was created. I went to grafana, setup the influxdb datasource but i throws error. Other than setting the database as unifi, do i need to set basic auth with the admin credential as well as the db username and password?
