### ISSUE TITLE
Docker Volume issue

### ISSUE THREAD

**Issue by henro4niger** [unifi-poller/unifi-poller#197]
I discover that when running the docker-compose.yml file, everything will run smoothly for a while (say 30 mins) then everything stops working. When I prune docker container volume and restart everything starts working fine again. 
I think this has to do with volume going out of size. is there a way to increase the volume size and also wipe the data that is say 3 days old?

**Comment by davidnewhall** [comment]
The application doesn't write any data to disk, so the size of the volume doesn't seem to play a part in your issue. Can you elaborate on what you're seeing happen when "everything stops working?" What do you mean by "prune the docker container?"

**Comment by henro4niger** [comment]
Thank you so much @davidnewhall for the quick response. What I meant by "everything stops working" is the Grafana will not get any data from Influxdb and all the panels will return "do data" if I set the time to, say 5mins. If I run "docker-compose down" and  run "docker volume prune" on my machine followed by "docker-compose up -d" I will have to start the setup afresh and add data source and dashboard. Everything will be back to normal.

**Comment by davidnewhall** [comment]
Okay. I definitely recommend troubleshooting with steps other than "docker-compose." `docker ps` and `docker logs` are great commands to begin with.

**Comment by davidnewhall** [comment]
Did you find the poller output? Were there any clues there?

**Comment by henro4niger** [comment]
Hello @davidnewhall  I battled above problem and I was able to solve it by using a linux instance with higher storage (30GB). Everything seems alright but I still have some challenges
![image](https://user-images.githubusercontent.com/52746166/75983378-bf1d1800-5ee8-11ea-9bc4-3d5cedf2cc82.png)
when I select a particular site, for the client insight dashboard, under "switch bandwidth/Wired Devices" all the clients are showing but no activities from them (max, avg, current showing 0Bs) even though there're people connected to the lan and are actively surfing the internet. 

This is not the same for other sites, I've carefully checked the site settings under unifi but everything seems ok.

**Comment by henro4niger** [comment]
Also is it possible to pull up total rx of users, I want to build a panel that displays daily data usage of users and possibly, monthly total data of each user

**Comment by davidnewhall** [comment]
> when I select a particular site, for the client insight dashboard, under "switch bandwidth/Wired Devices" all the clients are showing but no activities from them

How many sites do you have? Only one has this problem? You may need to look at the raw API data coming out of the controller, it's probably all zeros. It may also be that  your user doesn't have access to that site? That's less likely though since you have client names. My hunch is that the controller is not getting accurate updates for that site.

>  is it possible to pull up total rx of users

All users' data is recorded in the database, so it's possible to build a graph that sums them. Keep in mind that's all data usage, not just Internet-bound traffic.

**Comment by henro4niger** [comment]
I have 3 sites, in the controller and only one site is giving me zero bytes under "switch bandwidth/Wired Devices". Every other metrics seems ok and accurate, even "switch bandwidth/Wireless Devices" shows accurate data. I really need to figure out what is going on. Any suggestions on what I might try?

> All users' data is recorded in the database, so it's possible to build a graph that sums them. Keep in mind that's all data usage, not just Internet-bound traffic.
can you suggest the query I can use to pull up the data, I'm using influxDB

**Comment by henro4niger** [comment]
Hello @davidnewhall still waiting for feedback but in addition to that, I also noticed that the panel I customized showing total user has been showing zero since yesterday. Please checkout the image below
![image](https://user-images.githubusercontent.com/52746166/76282541-3f040300-6298-11ea-8451-e16b3881a363.png)
I was thinking it is a docker issue and I spun up another ubuntu instance on-premise, installed and configured influxdb yet, the total users are still showing zero, in addition to the other issue I mentioned above. Please help me out

**Comment by davidnewhall** [comment]
oh sorry, let me get something together for you to do some forensics.

**Comment by davidnewhall** [comment]
What happened to make the number become zero? Any idea? Was the controller upgraded maybe? Do the dashboards I provide show zero where you don't expect it too? I'm not sure what data source you're pulling that count from, can you share the query?

**Comment by henro4niger** [comment]
Yes, I upgraded the controller to version 5.12, also the dashboard shows zero in dashboard you built @davidnewhall . If the update triggered the issue, is there anything I can do to fix it? no configuration changes were made on the controller, just the upgrade. I'm really enjoying this tool and I want to make it work for me. I am considering using promethius as my datasource but I doubt if it will help.

**Comment by henro4niger** [comment]
SELECT "num_sta" AS "Total Users" FROM "subsystems" WHERE ("site_name" =~ /^$Site$/ AND "subsystem" = 'wan') AND $timeFilter

![image](https://user-images.githubusercontent.com/52746166/76300450-062a5500-62bd-11ea-8a84-eb8a6153101f.png)

**Comment by davidnewhall** [comment]
Do the poller output logs show any errors?

**Comment by davidnewhall** [comment]
I'll mess with this a bit more tomorrow (about to go to bed). I'll see if I can find any problems with the latest controller version, but I think mine is still working fine..

**Comment by henro4niger** [comment]
The zero value in the total users only affects just one site. I have three sites I am monitoring from the controller. Could it be information "overlap"?
![image](https://user-images.githubusercontent.com/52746166/76302474-5820aa00-62c0-11ea-9103-04f1d117de5e.png)

**Comment by henro4niger** [comment]
@davidnewhall I posted the three sites I'm monitoring up for you

**Comment by henro4niger** [comment]
The Lan subsystem for the second site is not showing the LAN IP, it is still this same site that is showing zero for total users

**Comment by henro4niger** [comment]
Everything seems ok for the last site (Owerri) but it is this same site that is showing zero user traffic I reported up there under "switch bandwidth/Wired Devices" for the client insights dashboard

**Comment by davidnewhall** [comment]
The screenshots you've provided show that DPI data collection is either off on the controller or off in unifi-poller. You have to enable DPI in two places to get traffic by category.

As for the missing `num_sta` value in the sites data, you are probably at a point where you need to inspect the data coming from your controller. 

This is probably not the easiest process when troubleshooting 3 sites. Can you get on Discord so we can chat?

**Comment by henro4niger** [comment]
thank you @davidnewhall  for the feedback, however, I have dpi enabled on all my sites. I am on discord, how do I reach you?

**Comment by mrjware** [comment]
Hi David, thanks for all your work, it sweet!  I have the same DPI data not found issue as well.  AND I have three sites.  only two of the sites have a USG and DPI is enabled on both.

**Comment by davidnewhall** [comment]
Provide poller configs please.

**Comment by davidnewhall** [comment]
If this is still a problem, please reply with your configuration.
