### ISSUE TITLE
UDMP throws error when collecting sites

### ISSUE THREAD

**Issue by jw59** [unifi-poller/unifi-poller#199]
When I point poller at my new UDMP (running 1.6.5 rc6 at the moment), I get an error when poller tries to find the 'sites'.  UDM(p) doesn't really have a concept of sites anymore, they can only manage themselves.

Any suggestions on how to get around this?

[ERROR] metric fetch for InfluxDB failed: unifi.GetSites(): invalid status code from server for https://xxxx/proxy/network/api/stat/sites: 500 Internal Server Error | stdout

**Comment by jw59** [comment]
This was because I didn't explicitly add the permissions to the 'Network' app.

**Comment by davidnewhall** [comment]
For everyone else that find this issue, here's jw's screenshot.
![Screen_Shot_2020-02-25_at_9 50 24_PM-1](https://user-images.githubusercontent.com/2402929/75379203-d83f1c80-5889-11ea-818f-cbf6d6655c1e.png)
