### ISSUE TITLE
new release soon?

### ISSUE THREAD

**Issue by Obre** [unifi-poller/unifi-poller#203]
Hey,

is there any ETA for the new release? I really love the application but cannot use it since brew not installing it :(

How could I use it on MacOS ? Build myself?

**Comment by davidnewhall** [comment]
I've been waiting for a piece of hardware so i can add better cloudkey support. There is no easy way to fix homebrew without making a new release, unfortunately. For now, you can download a pre-built binary from the [Releases](https://github.com/unifi-poller/unifi-poller/releases) page and copy it into place. Do the same with the new up.conf config file.
