### ISSUE TITLE
Small mistake in the installation instructions

### ISSUE THREAD

**Issue by thomaspurchas** [unifi-poller/unifi-poller#204]
In the InfluxDB setup instructions there is a small mistake

```
influx -host localhost -port 8086
CREATE DATABASE unifi
CREATE USER unifipoller WITH PASSWORD 'unifipoller' WITH ALL PRIVILEGES
GRANT ALL ON unifi TO unifi
```

should read 

```
influx -host localhost -port 8086
CREATE DATABASE unifi
CREATE USER unifipoller WITH PASSWORD 'unifipoller' WITH ALL PRIVILEGES
GRANT ALL ON unifi TO unifipoller
```

GRANT ALL ON unifi TO **unifi** -> GRANT ALL ON unifi TO **unifipoller**

**Comment by davidnewhall** [comment]
I'll take a PR against this repo https://github.com/unifi-poller/wiki if someone wants to fix this. I've been super busy at work lately.
