### ISSUE TITLE
Ingress and Egress metrics seem to be backwards

### ISSUE THREAD

**Issue by 1Poochh** [unifi-poller/unifi-poller#205]
Great work on this!  Thank you.

I believe from the data, that something isn't either named incorrectly or my understanding is off on the meaning of the metric names.

I have imported the default dashboard for unifi-poller.  My setup includes Prometheus, Unifi-Poller, and Grafana.  While looking at several panels, I see that Tx metrics are metrics for data received by that device and Rx metrics are actually metrics around what is being sent.  The naming here seems backwards, so I wanted to do a quick verification.

Let me show the data around what I am seeing.  
![image](https://user-images.githubusercontent.com/7731631/78105825-e4495d00-73a6-11ea-89ed-0306406c4147.png)

My setup is pretty simple.  I have an Unifi 16 port switch that has both my plex server and my Roku hard-wired.  Plex (device name is Zeus - Hades (Wired)), being a video streaming service, I would expect it to be large amounts of data out (transmitting, not receiving).  My Roku (device name is Roku (Wired), should be receiving more data than it is sending.  The image above shows just that, but the metric names are backward.  `unifipoller_client_transmit_bytes_total` should be `unifipoller_client_receive_bytes_total` and `unifipoller_client_receive_bytes_total` should be `unifipoller_client_transmit_bytes_total`.  

First, I wanted to verify this with you that I understanding the naming of the metrics correctly.  If I do, it isn't clear to me if this is an Unifi issue or a naming of the metric issue.    Please let me know if you have any other questions on this.

**Comment by olmo1501** [comment]
To me this seems correct.

This is switch-view not device-view. The switch is receiving the traffic from your Plex and transmitting it to the Roku

**Comment by SuperQ** [comment]
Yes, @olmo1501 is correct. This is the view from the switch, so it seems a little backwards. But the data is correct.

**Comment by 1Poochh** [comment]
Great. Thank you, @olmo1501 and @SuperQ!
