### ISSUE TITLE
Allow reading password from file

### ISSUE THREAD

**Issue by regner** [unifi-poller/unifi-poller#206]
It's common to store passwords in files rather than environment variables. For example Docker Secrets are mounted into containers as a file. Files are often preferred over environment variables as lots of applications will dump environment variables for debug and secrets can sometimes leak that way.

As an example Grafana supports this: https://grafana.com/docs/grafana/latest/installation/configure-docker/

**Comment by davidnewhall** [comment]
The application supports a config file. [up.conf](https://github.com/unifi-poller/unifi-poller/blob/master/examples/up.conf.example). It can be formatted in xml, json, yaml or tool (default). Your passwords can go in there, or in environment variables.

**Comment by regner** [comment]
Thanks for the response. I understand that, however Docker orchestration tools (Kubernetes and Docker Swarm) prefer to inject secrets directly into a file where the contents of the file is the value of the secret.

In the case of Docker Swarm that is the only option for handling secrets. If I put it as an environment variable in Docker Swarm it gets exposed in a lot of ways it shouldn't.

**Comment by davidnewhall** [comment]
You've done a great job of describing the solution you'd like to have, and it may be something that gets implemented. I'm a firm believer that every problem has more than one solution. 

It seems that you can publish a Docker Secret using a snippet of the unifi-poller config file with any secrets you need to hide, like this:
```
[unifi.defaults]
pass = "mySecretPassword"
```
Then map it into `/etc/unifi-poller/up.conf`. You can then use environment variables to fill in the rest of the config data. Does that solve your use case?

**Comment by davidnewhall** [comment]
Did putting the secrets in the config file work?

**Comment by davidnewhall** [comment]
Hello @regner,

Will the solution described here work for your use case?
https://github.com/unifi-poller/inputunifi/pull/1

Thanks!

**Comment by davidnewhall** [comment]
I've confirmed this approach is compatible with Docker Swarm and Kubernetes secrets distribution process. This will now work for the UniFi controller password and the InfluxDB password. Instead of setting a password, you can set a file path prefixed with `file://`. Prefixing a password with `file://` makes poller treat it as a password file path instead of an actual password. This feature will be released with v2.0.1 soon.
