### ISSUE TITLE
unifi-poller not collecting and clientdpi data

### ISSUE THREAD

**Issue by itsmichaelk** [unifi-poller/unifi-poller#207]
First of all **THANK YOU** for this repo! We're absolutely loving it.

I found the _clientdpi dashboard_ in your "twelve dashboards" and I know the clientdpi dashboard is in work, but the poller isn't gathering **any** clientdpi data.

Do I have to tweak something or did I forget to set something up in the unifi admin section where I created the read-only user?

Thanks in advance!

Michael

**Comment by davidnewhall** [comment]
You have to enable in the poller config and in your controller. Two spots.

**Comment by itsmichaelk** [comment]
> You have to enable [DPI collection] in the poller config and in your controller. Two spots.

Yup, I forgot to enable the dpi collecting in the poller config.
Thank you so much @davidnewhall - enjoy the rest of your day!
