### ISSUE TITLE
Update UAP Graph query

### ISSUE THREAD

**Issue by halkeye** [unifi-poller/unifi-poller#208]
I'm not sure how to fork/PR dashboards, but can you update https://grafana.com/grafana/dashboards/11314 to use the following query

I'm currently running poller inside of kubernetes, using annotations to automatically pull prometheus data, which adds a bunch of columns to the table which messes up the chart

```
sum by (bytes,id,ip,mac,model,name,serial,site_name,source,type,uptime,version) ( unifipoller_device_info{site_name=~"$Site", name=~"$AP"} )
```

Sample data:
```
unifipoller_device_info{app_kubernetes_io_instance="unifi-poller",app_kubernetes_io_managed_by="Helm",app_kubernetes_io_name="unifi-poller",app_kubernetes_io_version="2.0",bytes="2044549212171",helm_sh_chart="unifi-poller-0.1.0",id="5e10de4f6e7c9300281ecc67",instance="[SNIP]",ip="[SNIP]",job="kubernetes-service-endpoints",kubernetes_name="unifi-poller",kubernetes_namespace="unifi",kubernetes_node="nickfury",mac="b[SNIP]",model="US24P250",name="[SNIP]",serial="[SNIP]",site_name="[SNIP]",source="[SNIP]",type="usw",uptime="4298763",version="4.0.80.10875"}

**Comment by halkeye** [comment]
same with USW Insights - Prometheus

**Comment by davidnewhall** [comment]
Can you show me a screenshot of the before/after that shows me the problem and the solution?

**Comment by halkeye** [comment]
Before
![image](https://user-images.githubusercontent.com/110087/79377292-47430400-7f10-11ea-83a3-2c423df25bd0.png)


After
![image](https://user-images.githubusercontent.com/110087/79377141-195dbf80-7f10-11ea-82ee-ca3d1cfebb78.png)

**Comment by halkeye** [comment]
oops, missed a mac, but its totally fine :)

**Comment by davidnewhall** [comment]
I'm not sure it makes sense for me to package changes in my graphs that work with your custom data schema. My general recommendation is create your own graphs when you want to customize them. In this case, I think modifying the schema and storing additional data in that name space is a bad idea. Can you store your k8s data in another name space?

**Comment by halkeye** [comment]
Its something the kubernetes annotations add automatically.

Its absolutely not a big deal, I just through modifying the table query to only pull the data your publishing was a safe change, which is why I suggested it, but its absolutely not a problem

**Comment by davidnewhall** [comment]
It's likely a safe change, but I have no reasonable way to test it or validate it doesn't break your setup when I make changes to it later. To me it becomes tech debt since it's just extra stuff in my graphs that doesn't do anything for me. 

I feel like K8s should allow you to choose a name space for the annotations and not force you to add stuff to your existing name spaces.
https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/

**Comment by davidnewhall** [comment]
If you're going to edit the graphs, I suggest you add the extra label selectors to the variables and not the graphs. It'll be a lot easier.

**Comment by halkeye** [comment]
Yea those are both links for kubernetes. Essentially for each container you run you can add labels to tell Prometheus to connect to that container and pull metrics without me having to manage a scrape config for each service.

Like I said, this specific graph doesn't impact me, I don't have multiple clients I just saw it was broken for me and figures the change would be helpful.

I'll look at the Prometheus source code and see if I can't disable that feature 

It was also an excuse to learn some promql since so far I've just used public graphs and havnt played with it

**Comment by halkeye** [comment]
> If you're going to edit the graphs, I suggest you add the extra label selectors to the variables and not the graphs. It'll be a lot easier.

I mean yes, if I was trying to select on those labels, I was trying to hide them

**Comment by davidnewhall** [comment]
I'll leave this open to see if anyone else has ideas. Maybe @SuperQ is familiar with this setup; he's a Prometheus god.

**Comment by davidnewhall** [comment]
I've looked more carefully at the update you requested. I actually think that's fine. Thanks!

**Comment by halkeye** [comment]
\o/ I thought it was a super safe change, but i'm also super new to prometheus, so i'm happy to hear that.

**Comment by davidnewhall** [comment]
The new dashboard with this change will be published this week.
