### ISSUE TITLE
does it work with UDM Pro? -> Server Error 500

### ISSUE THREAD

**Issue by jdornauf** [unifi-poller/unifi-poller#209]
i could help in debugging, try to set popper up on ubuntu machine with Grafana/influx/unifi-poller to poll my fresh UDM Pro, auth runs fine, polling not: (all in house) 

calling mentioned endpoint from browser gives JSON answer from UDM Pro after manual login:
https://unifi.xyz.com/proxy/network/api/stat/sites
{"meta":{"rc":"ok"},"data":[{"_id":"5e7d18ec756cd702da2a1e7b","name":"default","desc":"DCO","attr_hidden_id":"default","attr_no_delete":true,"health":[{"subsystem":"wlan","num_user":20,"num_guest":5,"num_iot":0,"tx_bytes-r":166525,"rx_bytes-r":36457,"status":"ok","num_ap":2,"num_adopted":2,"num_disabled":0,"num_disconnected":0,"num_pending":0},{"subsystem":"wan","num_gw":1,"num_adopted":1,"num_disconnected":0,"num_pending":0,"status":"ok","wan_ip":"176.95.217.41","gateways":[],"netmask":"255.255.255.255","nameservers":[],"num_sta":97,"tx_bytes-r":99759,"rx_bytes-r":234577,"gw_mac":"e0:63:da:c2:56:f5","gw_name":null,"gw_system-stats":{"cpu":"10.0","mem":"44.3","uptime":"511200"},"gw_version":"1.6.6.2431"},{"subsystem":"www","status":"ok","tx_bytes-r":99759,"rx_bytes-r":234577,"latency":12,"uptime":263129,"drops":3,"xput_up":29.459,"xput_down":89.978,"speedtest_status":"Success","speedtest_lastrun":1586934150,"speedtest_ping":14,"gw_mac":"e0:63:da:c2:56:f5"},{"subsystem":"lan","lan_ip":null,"status":"ok","num_user":72,"num_guest":0,"num_iot":0,"tx_bytes-r":136373,"rx_bytes-r":71658,"num_sw":5,"num_adopted":5,"num_disconnected":0,"num_pending":0},{"subsystem":"vpn","status":"ok","remote_user_enabled":true,"remote_user_num_active":0,"remote_user_num_inactive":0,"remote_user_rx_bytes":0,"remote_user_tx_bytes":0,"remote_user_rx_packets":0,"remote_user_tx_packets":0,"site_to_site_enabled":false}],"num_new_alarms":81}]}

Apr 17 11:26:03 ubuntu unifi-poller[101558]: 2020/04/17 11:26:03.979572 influxdb.go:75: [ERROR] metric fetch for InfluxDB failed: unifi.GetSites(): invalid status code from server for https://unifi.xyz.com/proxy/network/api/stat/sites: **500 Internal Server Error**

-> its not clear for me which server throws this 500 error

Apr 17 11:26:03 ubuntu unifi-poller[101558]: 2020/04/17 11:26:03.732840 unifi.go:186: [DEBUG] Requesting https://unifi.xyz.com/proxy/network/api/stat/sites, with params: false, cookies: 1
Apr 17 11:26:03 ubuntu unifi-poller[101558]: 2020/04/17 11:26:03.758028 collector.go:69: [INFO] Re-authenticating to UniFi Controller: https://unifi.xyz.com
Apr 17 11:26:03 ubuntu unifi-poller[101558]: 2020/04/17 11:26:03.758298 unifi.go:100: [DEBUG] Requesting https://unifi.dornauf.com/ to determine API paths
Apr 17 11:26:03 ubuntu unifi-poller[101558]: 2020/04/17 11:26:03.788832 unifi.go:129: [DEBUG] Using NEW UniFi controller API paths for https://unifi.xyz.com/
Apr 17 11:26:03 ubuntu unifi-poller[101558]: 2020/04/17 11:26:03.789447 unifi.go:186: [DEBUG] Requesting https://unifi.dornauf.com/api/auth/login, with params: true, cookies: 0
Apr 17 11:26:03 ubuntu unifi-poller[101558]: 2020/04/17 11:26:03.957339 unifi.go:84: [DEBUG] Requested https://unifi.dornauf.com/api/auth/login: elapsed 168ms, returned 1189 bytes
Apr 17 11:26:03 ubuntu unifi-poller[101558]: 2020/04/17 11:26:03.958015 unifi.go:186: [DEBUG] Requesting https://unifi.dornauf.com/proxy/network/status, with params: false, cookies: 1
Apr 17 11:26:03 ubuntu unifi-poller[101558]: 2020/04/17 11:26:03.978902 unifi.go:157: [DEBUG] Requested https://unifi.dornauf.com/proxy/network/status: elapsed 21ms, returned 320 bytes
Apr 17 11:26:03 ubuntu unifi-poller[101558]: 2020/04/17 11:26:03.979368 input.go:92: [DEBUG] Authenticated with controller successfully, https://unifi.xyz.com
Apr 17 11:26:03 ubuntu unifi-poller[101558]: 2020/04/17 11:26:03.979572 influxdb.go:75: [ERROR] metric fetch for InfluxDB failed: unifi.GetSites(): invalid status code from server for https://unifi.xyz.com/proxy/network/api/stat/sites: 500 Internal Server Error
Apr 17 11:26:03 ubuntu unifi-poller[101558]: 2020/04/17 11:26:03.980742 influxdb.go:300: [INFO] UniFi Metrics Recorded. Sites: 0, Clients: 0, UAP: 0, USG/UDM: 0, USW: 0, IDS Events: 0, Points: 0, Fields: 0, Errs: 1, Elapsed: 1ms

**Comment by davidnewhall** [comment]
Strange. The controller returns a 500 for the sites list. The user may not have access to list sites. Try using your admin account to see if it works. If it does, you're missing some permissions on the user you added. If the admin account also gives you a 500, I'd question if you're running the latest OS. If yes, then this looks like a bug in UDM, or a change in their API.

> https://unifi.xyz.com/proxy/network/api/stat/sites: 500 Internal Server Error
> -> its not clear for me which server throws this 500 error

 https://unifi.xyz.com is throwing a 500.

**Comment by jdornauf** [comment]
yes your are pointing me right: its a users problem, will look for that, polling works fine with my admin user, THX
