### ISSUE TITLE
Controller Auth or Connection failed

### ISSUE THREAD

**Issue by mrstevefay** [unifi-poller/unifi-poller#210]
Hi, looking for some direction on this one.

Poller is getting "Controller Auth or Connection failed" from the controller. The accounts can login to the controller web GUI and access the site data. 

Controller 5.12.67 

Any suggestions?

` unifi-poller[22400]: 2020/04/17 20:54:36 [ERROR] Controller Auth or Connection failed, but continuing to retry! unifi @ https://192.168.1.1:8443: unifi controller: Get https://192.168.1.1:8443/: dial tcp 192.168.1.1:8443: connect: connection refused`

**Comment by davidnewhall** [comment]
Try removing the `:8443` from the URL.

**Comment by davidnewhall** [comment]
Please re-open if you're still having issues.
