### ISSUE TITLE
The Wiki has wrong influxdb query

### ISSUE THREAD

**Issue by Zolli** [unifi-poller/unifi-poller#211]
In the configuration section of the wiki, a some-sort of typo is made and the query that grants permission to the db cannot be executed because the username is not correct.

Relevant page: https://github.com/unifi-poller/unifi-poller/wiki/Installation

Pleas change the 
```sql
GRANT ALL ON unifi TO unifi
```

to:
```sql
GRANT ALL ON unifi TO unifipoller
```

**Comment by davidnewhall** [comment]
Thank you! I have #206 to remind me to do this.
