### ISSUE TITLE
Is the Flex Mini switch supported? = YES

### ISSUE THREAD

**Issue by jjlawren** [unifi-poller/unifi-poller#212]
https://store.ui.com/collections/unifi-network-routing-switching/products/usw-flex-mini

I don't see why not, but I'd like to confirm if the Flex Mini switches were supported for these metrics. They do not support SNMP, so this would be a great alternative.

**Comment by davidnewhall** [comment]
Probably. Someone with one will have to answer. 

I still need to make the switch ports on the UAP-IW-HD work, but I have one of those devices and will make that happen eventually.

**Comment by PianSom** [comment]
Yeah, they work just fine (within the limits of the data that the switch provides - so no temp, experience etc)
