### ISSUE TITLE
Unable to set timezone

### ISSUE THREAD

**Issue by wildloveil** [unifi-poller/unifi-poller#213]
Hi,
I'm running the unifi-poller as container but I'm not able to set the container timezone to my correct timezone.
I've tried doing it using paramter "-e TZ=Asia/Jerusalem" but it didn't work.
Is there a way you can see how I can do that?

Thanks

**Comment by davidnewhall** [comment]
The container doesn't have any zone info files. That will probably render it impossible to change the time zone. This should only affect the log messages and not the function of the app. I'll leave this task open to remind me to add the zone info files and do some timezone testing.

**Comment by davidnewhall** [comment]
I've added the ability to pass a `TZ` env variable into the application. This allows you to set the time zone. This enhancement will be included with release v2.0.1 in the coming week.
