### ISSUE TITLE
Typo on Installation Wiki page.

### ISSUE THREAD

**Issue by ScottHelme** [unifi-poller/unifi-poller#215]
On the [Installation](https://github.com/unifi-poller/unifi-poller/wiki/Installation) Wiki Page, Section 3:

`GRANT ALL ON unifi TO unifi`

Should be:

`GRANT ALL ON unifi TO unifipoller`

**Comment by davidnewhall** [comment]
You sure?

**Comment by davidnewhall** [comment]
Thanks! Fixed.
