### ISSUE TITLE
Brew Install Failing at *darwin.so

### ISSUE THREAD

**Issue by pyrofection** [unifi-poller/unifi-poller#219]
I'm getting an error when attempting to install unifi-poller via Homebrew. I'm new to this sort of thing but have Grafana and InfluxDB installed and have them working but run into the issue below when I try running $ brew install golift/mugs/unifi-poller  that is listed in the wiki for the MacOS install.

Pyro-MBP:~ michaeldupaix$ brew install golift/mugs/unifi-poller --verbose
==> Installing unifi-poller from golift/mugs
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200429-34497-6i0m67.sb nice ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/golift/homebrew-mugs/Formula/unifi-poller.rb --verbose
==> Downloading https://golift.io/unifi-poller/archive/v2.0.0.tar.gz
Already downloaded: /Users/michaeldupaix/Library/Caches/Homebrew/downloads/e70b0b04eba4252ac2249c8f2008a520ae1c9f64949edafe491ab2820b4dbe96--unifi-poller-2.0.0.tar.gz
==> Verifying e70b0b04eba4252ac2249c8f2008a520ae1c9f64949edafe491ab2820b4dbe96--unifi-poller-2.0.0.tar.gz checksum
tar xof /Users/michaeldupaix/Library/Caches/Homebrew/downloads/e70b0b04eba4252ac2249c8f2008a520ae1c9f64949edafe491ab2820b4dbe96--unifi-poller-2.0.0.tar.gz -C /private/tmp/d20200429-34498-141em82
cp -pR /private/tmp/d20200429-34498-141em82/unifi-poller-2.0.0/. /private/tmp/unifi-poller-20200429-34498-ebwu1e/unifi-poller-2.0.0
chmod -Rf +w /private/tmp/d20200429-34498-141em82
==> make install VERSION=2.0.0 ITERATION=763 PREFIX=/usr/local/Cellar/unifi-poller/2.0.0 ETC=/usr/local/etc
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
go get github.com/github/hub/md2roff-bin
go build -o unifi-poller -ldflags "-w -s -X github.com/prometheus/common/version.Branch=unknown -X github.com/prometheus/common/version.BuildDate=2020-04-29T17:52:51Z -X github.com/prometheus/common/version.Revision=0 -X github.com/prometheus/common/version.Version=2.0.0-763"
go: downloading github.com/unifi-poller/promunifi v0.0.6
go: downloading github.com/unifi-poller/inputunifi v0.0.6-0.20200205010458-a1783e28d08a
go: downloading github.com/unifi-poller/poller v0.0.5
go: downloading github.com/unifi-poller/influxunifi v0.0.8
go: downloading github.com/unifi-poller/unifi v0.0.4
go: downloading github.com/github/hub v1.12.4
go: downloading github.com/prometheus/client_golang v1.4.0
go: downloading github.com/prometheus/common v0.9.1
go: downloading golift.io/cnfg v0.0.5
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/influxdata/influxdb1-client v0.0.0-20191209144304-8bf82d3c094d
go: downloading golang.org/x/net v0.0.0-20200202094626-16171245cfb2
go: downloading github.com/github/hub v2.11.2+incompatible
go: downloading github.com/BurntSushi/toml v0.3.1
go: downloading gopkg.in/yaml.v2 v2.2.8
go: downloading github.com/prometheus/client_model v0.2.0
go: downloading github.com/prometheus/procfs v0.0.8
go: downloading github.com/golang/protobuf v1.3.3
go: downloading github.com/cespare/xxhash/v2 v2.1.1
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: found github.com/github/hub/md2roff-bin in github.com/github/hub v2.11.2+incompatible
go: downloading github.com/russross/blackfriday v2.0.0+incompatible
go: downloading github.com/mattn/go-colorable v0.1.4
go: downloading github.com/mattn/go-isatty v0.0.11
go: downloading golang.org/x/sys v0.0.0-20200202164722-d101bd2416d5
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
# Building man page. Build dependency first: md2roff
# This turns README.md into README.html
go run github.com/github/hub/md2roff-bin --manual unifi-poller --version 2.0.0 --date "2020-04-29T17:52:51Z" README.md
go run github.com/github/hub/md2roff-bin --manual unifi-poller --version 2.0.0 --date "2020-04-29T17:52:51Z" examples/MANUAL.md
gzip -9nc examples/MANUAL > unifi-poller.1.gz
mv examples/MANUAL.html unifi-poller_manual.html
- Done Building! -
- Local installation with the Makefile is only supported on macOS.
If you wish to install the application manually on Linux, check out the wiki: https://https://github.com/unifi-poller/unifi-poller/wiki/Installation
- Otherwise, build and install a package: make rpm -or- make deb
See the Package Install wiki for more info: https://https://github.com/unifi-poller/unifi-poller/wiki/Package-Install
# Copying the binary, config file, unit file, and man page into the env.
/usr/bin/install -m 0755 -d /usr/local/Cellar/unifi-poller/2.0.0/bin /usr/local/Cellar/unifi-poller/2.0.0/share/man/man1 /usr/local/etc/unifi-poller /usr/local/Cellar/unifi-poller/2.0.0/share/doc/unifi-poller /usr/local/Cellar/unifi-poller/2.0.0/lib/unifi-poller
/usr/bin/install -m 0755 -cp unifi-poller /usr/local/Cellar/unifi-poller/2.0.0/bin/unifi-poller
/usr/bin/install -m 0755 -cp *darwin.so /usr/local/Cellar/unifi-poller/2.0.0/lib/unifi-poller/
install: *darwin.so: No such file or directory
make: *** [install] Error 71

==> Formula
Tap: golift/mugs
Path: /usr/local/Homebrew/Library/Taps/golift/homebrew-mugs/Formula/unifi-poller.rb
==> Configuration
HOMEBREW_VERSION: 2.2.14
ORIGIN: https://github.com/Homebrew/brew
HEAD: e2bc0fa6879ce4c74ea2d8f8c654c9812f776b43
Last commit: 34 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 12d7c0db8214a80673cdb14bc2415495c8abb09b
Core tap last commit: 47 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 10.0 build 1001
Git: 2.20.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: N/A
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/libxml2:/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.14
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk
PATH: /usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/local/opt/go/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: golift/mugs/unifi-poller 2.0.0 did not build
Logs:
     /Users/michaeldupaix/Library/Logs/Homebrew/unifi-poller/01.make
     /Users/michaeldupaix/Library/Logs/Homebrew/unifi-poller/00.options.out
     /Users/michaeldupaix/Library/Logs/Homebrew/unifi-poller/01.make.cc
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/golift/homebrew-mugs/issues

**Comment by davidnewhall** [comment]
This will be fixed when I get around to making another release. For now you can grab the b binary off the releases page, and the example config file from the repo. Put them in place and you an run this on your mac.

Duplicates #200.

**Comment by davidnewhall** [comment]
Version 2.0.1 fixes the issue.

brew install unifi-poller
