### ISSUE TITLE
Add support for events

### ISSUE THREAD

**Issue by blalor** [unifi-poller/unifi-poller#220]
I'd love to see controller events stuffed into influx in a way that I can show them as annotations in grafana. 

<img width="563" alt="Screen Shot 2020-05-01 at 8 59 05 AM" src="https://user-images.githubusercontent.com/109915/80861552-3cd97780-8c3d-11ea-8424-2c825e140c63.png">

Web inspector "copy as curl":

```
curl 'https://unifi-cloudkey.home.local:8443/api/s/default/stat/event' \
-XPOST \
-H 'Content-Type: application/json;charset=utf-8' \
-H 'Accept: application/json, text/plain, */*' \
-H 'Host: unifi-cloudkey.home.local:8443' \
-H 'Accept-Language: en-us' \
-H 'Accept-Encoding: br, gzip, deflate' \
-H 'Origin: https://unifi-cloudkey.home.local:8443' \
-H 'Referer: https://unifi-cloudkey.home.local:8443/manage/site/default/dashboard' \
-H 'Content-Length: 39' \
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15' \
-H 'Connection: keep-alive' \
-H 'Cookie: csrf_token=…; unifises=…' \
-H 'X-Csrf-Token: …' \
--data-binary '{"_limit":500,"_start":0,"within":4320}'
```

Sample event:

```json
    {
      "_id": "5eac130853afdc04bb92ba8c",
      "user": "…",
      "ap_from": "…",
      "ap_to": "…",
      "radio_from": "na",
      "radio_to": "na",
      "radio": "na",
      "channel_from": "36",
      "channel_to": "149",
      "channel": "149",
      "ssid": "<SSID>",
      "key": "EVT_WU_Roam",
      "subsystem": "wlan",
      "site_id": "…",
      "time": 1588335358461,
      "datetime": "2020-05-01T12:15:58Z",
      "msg": "User[…] roams from AP[…] to AP[…] from \"channel 36(na)\" to \"channel 149(na)\" on \"<SSID>\""
    },
```

**Comment by davidnewhall** [comment]
I already tried this with IDP/IDS. It's gross and difficult to use. These are not metrics, and influx is the wrong database for this data. Sorry, but poller doesn't solve every problem, and this is one it cannot solve. The best we could do is create another database (mysql, psql, etc) to store the data in. Honestly, I don't think there's enough value in that to justify the expense.

I'll leave this open [for a while] for others to +1 and leave their thoughts.

**Comment by blalor** [comment]
Events is actually one of the stated use cases of influxdb, which is why I brought it up. It’s really useful for overlaying with annotations in grafana.

**Comment by davidnewhall** [comment]
If you can give me more data about how you'd expect to find (SELECT) this data in InfluxDB, it may help my understanding of what you're looking for.

**Comment by blalor** [comment]
Sample insert:

    insert event,user=them,ap_from=old\ ap,ap_to=new\ ap,radio_from=na,radio_to=na,ssid=pretty\ fly\ for\ a\ wifi,key=EVT_WU_Roam,subsystem=wlan,site_id=42 channel_from=36,channel_to=149,msg="User[] roams from AP[] to AP[] ..."

A query:

    select "msg","ssid" from "event" where "key" = 'EVT_WU_Roam' AND $timeFilter ORDER BY time ASC limit 100

This would show annotations on a graph indicating where roam events happened, channel changes, etc.

More on Grafana annotations and influxdb: https://grafana.com/docs/grafana/latest/features/datasources/influxdb/#annotations

Influx does require a field to be returned (you can't just select tags).

**Comment by varac** [comment]
Does this request cover the `Wifi Metrics Anomalies` from the dashboard as well ? 
Or are those already exported is some way ?

```
Anomalies over 4 devices

1:00pm   Excessive packet drops for Access Point 
9:00am   Access Point experienced high retry rates
3:00am   Long association time for Access Point
9:00pm   Excessive packet drops for Access Point
```

**Comment by varac** [comment]
Because I'd really like to create alerts for such kind of anomalies with alertmanager i.e.

**Comment by davidnewhall** [comment]
My current question is:
Does `/api/s/default/stat/event` contain all the same events as `/api/s/default/stat/ips/event` (and more) ?

**Comment by blalor** [comment]
`/api/s/default/stat/ips/event` doesn't return any events for me. I'm not using a USG or similar. Is `ips` "intrusion protection system"(?) or "IP (addresse)s"?  Any other endpoints I could sniff out for you?

**Comment by davidnewhall** [comment]
> intrusion protection system

yes.

**Comment by davidnewhall** [comment]
@varac What screen/link do you see these under in your UniFi UI?

> Anomalies over 4 devices

Is this `Alarms` ?

**Comment by davidnewhall** [comment]
@varac What screen/link do you see these under in your UniFi UI?

> Anomalies over 4 devices

Is this `Alarms` ?

**Comment by davidnewhall** [comment]
@varac What screen/link do you see these under in your UniFi UI?

> Anomalies over 4 devices

Is this `Alarms` ?

**Comment by davidnewhall** [comment]
Still working in a new feature. Events support will be released probably mid-August.

**Comment by davidnewhall** [comment]
Try https://github.com/unifi-poller/unifi-poller/releases/tag/v2.0.2-beta1
