### ISSUE TITLE
"No data" or "n/a" until I edit the queries for each element?

### ISSUE THREAD

**Issue by hcanning87** [unifi-poller/unifi-poller#221]
Hi there,

I have followed the instructions Unifi Poller working.  I'm having a bit of an issue getting it to show any data though...

For each element of the dashboard I have to edit it and remove the "where name" and "site_name" tag filters in order to get it to change from "n/a" or "no data.

![2020-05-03 16_24_46-UniFi-Poller_ USG Insights - InfluxDB - Grafana](https://user-images.githubusercontent.com/64742014/80918294-15c59780-8d5c-11ea-815f-9bd8c2287bcc.png)

Below - Left one is one I have fixed, right is one that is default:

![2020-05-03 16_35_34-UniFi-Poller_ USG Insights - InfluxDB - Grafana](https://user-images.githubusercontent.com/64742014/80918311-2ece4880-8d5c-11ea-99bd-048a1e62d93c.png)

Can anyone let me know how I might be able to fix this centrally without having to go through every single element and edit it this way?

Many thanks!!

**Comment by davidnewhall** [comment]
Upgrade InfluxDB.

**Comment by davidnewhall** [comment]
Did upgrading work?

**Comment by hcanning87** [comment]
I managed to fix it by manually editing each graph in the meantime. It was
a fresh install of InfluxDB anyway so should be the latest version.
