### ISSUE TITLE
docker image for linux/aarch64

### ISSUE THREAD

**Issue by lkoenigsberger** [unifi-poller/unifi-poller#223]
Hi,

i just tried to pull the image from an nvidia jetson and got the following error:
```
latest: Pulling from golift/unifi-poller
no matching manifest for linux/arm64/v8 in the manifest list entries
```
Would be nice to have a docker image for that architecture also.
```
docker info  -f '{{.OSType}}/{{.Architecture}}'
linux/aarch64
```

Thanks

**Comment by davidnewhall** [comment]
Try `master` instead of `latest`.

**Comment by lkoenigsberger** [comment]
Nice! Thanks that`s working

**Comment by davidnewhall** [comment]
Leaving this open, to remind me to make sure this works in the next release.

**Comment by davidnewhall** [comment]
Dup #232
