### ISSUE TITLE
Ability to restrict polling to non-personal data

### ISSUE THREAD

**Issue by varac** [unifi-poller/unifi-poller#224]
Hej, I just stumbled across this awesome project, thanks a lot in advance !

I'd like to know if you ever though about restricting polling to non-personal data.
We're administrating a small site and want to make sure that we don't store any personal data in prometheus/grafana. It already worries me how much information I can extract from the unifi-controller (Oh, I see that alice is visiting bob at 2pm at night because her phone is roaming to bobs AP). It's a nightmare not only from a ethical point of view to have access to so much details as an admin, it also worrisome in terms of the The General Data Protection Regulation (GDPR) in the EU.

So I'd love if there would be an option to use the unifi-poller only for non-personal metrics. Hope you understand what I mean.
I know this is probably a lot to ask, but I need to investigate if using the unifi-poller is an option for me with these regards.

**Comment by SuperQ** [comment]
There's some nice tricks you can do anonomize label values with Prometheus relabel configs.

```yaml
metric_relabel_configs:
- source_labels:
  - sensitive_label
  target_label: sensitive_label
  modulus: 18446744073709551616
  action: hashmod
```

The modulus value is uint64 max value. The label value will then end up as the MD5 of the original value. This should be good enough for GDPR regulation.

It's also an option in relabel configs to full drop some labels. So you can hashmod on something like mac address, but fully drop the host information.

**Comment by varac** [comment]
@SuperQ Thx, good to know, I'll give this a try.

However I still feel it would be better imo if the poller itself has an option to hash all sensitive metrics, for everybody who is not familiar with the different types of metrics which need to get hashed. Sth like a GDPR compliance mode.

**Comment by SuperQ** [comment]
I agree, I run this code for a makerspace, and it would be useful to have some privacy options.

I just wanted to post a workaround until something is done here.

**Comment by davidnewhall** [comment]
I run this code in a house with 4 members. PII isn't really a concern for me. How do you prevent the controller from storing PII data? 

What is personally identifying? We're talking about [typically private] IPs and host names. There's no usernames here that I recall. So you'd just need a way to remove the host name?

**Comment by SuperQ** [comment]
MAC addresses and discovered hostnames are PII. And yes, the fact that they're in the controller is also a concern. But for GDPR, it's a storage concern, which is why it's important in a Prometheus/InfluxDB context.

**Comment by davidnewhall** [comment]
Does an md5 hash of the data seem sufficient?

**Comment by varac** [comment]
> Does an md5 hash of the data seem sufficient?

That's great, thanks !
