### ISSUE TITLE
Client with newline in name causes influxdb parse error.

### ISSUE THREAD

**Issue by fribse** [unifi-poller/unifi-poller#226]
I've just tried setting up unifipoller, and have gotten the right credentials provided for unifipoller.
But when it starts it fails to parse the output as I understand the log:

`May 11 07:38:50 unifipoller unifi-poller[373]: 2020/05/11 07:38:50 [ERROR] influxdb.Write(points): {"error":"partial write: unable to parse 'clients,ap_name=Groundfloor,channel=1,gw_name=Gateway,is_guest=false,is_wired=false,mac=c8:f7:42:83:ff:ff,name=RM3-83-85-bc\r': missing fields\nunable to parse ',oui=Hangzhou,radio=ng,radio_name=wifi0,radio_proto=ng,site_name=Default\\ (default),source=https://192.168.168.1:443,sw_name=Masterswitch,sw_port=19,vlan=0 anomalies=0i,bssid=\"18:e8:29:c1:00:00\",bytes_r=0i,ccq=991i,channel=1,essid=\"ssid\",hostname=\"RM3-83-85-bc\r\n\",ip=\"192.168.1.147\",noise=-108i,note=\"\",radio_desc=\"Groundfloor ng wifi0:ng\",roam_count=0i,rssi=31i,rx_bytes=27118201261i,rx_bytes_r=0i,rx_packets=57539517i,rx_rate=72109i,satisfaction=97,signal=-65i,tx_bytes=110355148027i,tx_bytes_r=0i,tx_packets=103966002i,tx_power=34i,tx_rate=72222i,tx_retries=352i,uptime=41251i,wifi_tx_attempts=4144i,wired-rx_bytes=0i,wired-rx_bytes-r=0i,wired-rx_packets=0i,wired-tx_bytes=0i,wired-tx_bytes-r=0i,wired-tx_packets=0i': missing measurement dropped=0"}`
The setup here is not that big.
UDM Pro
48 port USW POE500
1 unfi ap ac lite
2 unfi sw flex mini
Everything should be at the latest software
The MAC's, SSID, BSSID and IP's have been modified...

**Comment by davidnewhall** [comment]
That's new. What version of InfluxDB?

**Comment by fribse** [comment]
That's a good question, it's running as a [Homeassistant Addon](https://github.com/hassio-addons/addon-influxdb). 
Chronograf 1.8.2
The addon is 3.6.2, but I'm not sure that reflects the InfluxDB version.
How can I get the version of the DB engine?

**Comment by davidnewhall** [comment]
https://stackoverflow.com/questions/41856474/how-to-get-influxdb-version-via-shell

**Comment by fribse** [comment]
Thankyou David, I got a result when doing it from my unifi-poller lxc:
```
HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: e52c4bed-9367-11ea-80de-0242ac1e2104
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.7.10
X-Request-Id: e52c4bed-9367-11ea-80de-0242ac1e2104
Date: Mon, 11 May 2020 09:15:02 GMT
```

**Comment by davidnewhall** [comment]
That should be a supported version. I've never seen an error like this. I really do not know what to make of it.

**Comment by davidnewhall** [comment]
This sort of makes it look like one of the devices has special characters in its name. Perhaps something with a device name is not parsing correctly. Can you check the names of your devices in the controller? Do you see anything that stands out as non-alphanumeric?
```
name=RM3-83-85-bc\r': missing fields\nunable to parse ',oui=Hangzhou
```

**Comment by davidnewhall** [comment]
Yeah, this seems to be it. The hostname has a newline in it. I'll see what I can do to fix this in poller, but in the meantime, try to remove that extra newline at the end of your device's name.
```
hostname=\"RM3-83-85-bc\r\n\"
```

**Comment by fribse** [comment]
Ahaa, ok, I can't modify them in the device itself, I'll try and modify the alias in the controller and see if that helps

**Comment by fribse** [comment]
Wow, that made it work, just changing the alias. So you were spot on, impressive! :-)

**Comment by fribse** [comment]
But why on earth do they put a newline in the hostname for a smart-device, geez???

**Comment by davidnewhall** [comment]
That's a broad link device? RM mini I take it?

**Comment by fribse** [comment]
Yes, there are two RM mini 3
They are called Stue remote and Køkkenremote, no newlines in the device list in the app (allthough a danih character), but the name doesn't have anything to do with the hostname.
