### ISSUE TITLE
What Port to use with UDM-Pro?

### ISSUE THREAD

**Issue by gnoffer** [unifi-poller/unifi-poller#227]
Hi, i want to use unifi-poller with UDM-Pro. What Port do i have to use, cause 8443 ist not the right port any more. But also 443 and also with HTTPS-path is not working.

2020/05/11 08:25:38.974313 interface.go:49: [ERROR] Controller Auth or Connection failed, but continuing to retry! poller @ https://192.168.22.1:443/network/site/default/dashboard: unifi controller: Get https://192.168.22.1:443/network/site/default/dashboard/: dial tcp 192.168.22.1:443: connect: connection timed out

**Comment by davidnewhall** [comment]
443 is the correct port. Based on the timeout error, it looks like 192.168.22.1 is not the correct IP or there's a firewall preventing access.

**Comment by gnoffer** [comment]
Thanks. seems to be a firewall/VPN issue. thanks for the hint.
