### ISSUE TITLE
How can I show a specific network-sites dashboard?

### ISSUE THREAD

**Issue by fribse** [unifi-poller/unifi-poller#228]
Hi there
Wow, this is a really great insight into the unifi, geez it sucks out a lot of info from the system, I'm very impressed.
I only have 1 site, and I would like to set up a kiosk browser on a computer that shows the network sites dashboard for the specific site (I only have 1, so not much choice), but if I share the dashboard it shows up collapsed, which is unfortunate for a kiosk display :-)

**Comment by davidnewhall** [comment]
Save it, uncollapsed.

**Comment by fribse** [comment]
Ha , wow that simple, and yes, that works :-) Thankyou!
