### ISSUE TITLE
How do I make a shortcut that hides the legend?

### ISSUE THREAD

**Issue by fribse** [unifi-poller/unifi-poller#229]
I've gotten a RPi3 running now with chromium as kioskbrowser to show the up/down graph on a 7" monitor, very nice to be able to pull out all this nice data, I'm still very impressed with this package.

So it looks like this now:
![image](https://user-images.githubusercontent.com/13660621/81953976-96ac4b00-9608-11ea-8627-28fe65d5cb65.png)
When it opens, it shows the legend, but as the monitor is only 7", it takes up too much space.
I have attached a keyboard/mouse to toggle the legend off after a boot.
Is there a way to put that in the shared URL, so it will not require me to turn it off after a boot?

**Comment by davidnewhall** [comment]
It sounds like you need to click save after you make your edits.

**Comment by davidnewhall** [comment]
And/or make a new dashboard for your Kiosk and set it up just the way you want/need it to look.

**Comment by fribse** [comment]
Hi @davidnewhall 
I don't want to save it, as that will affect the 'original' panel where I like that it shows the legend.
I tried looking in the json for it, and got it pasted it as a new dashboard, but it doesn't show any data, I'm very new to grafana, so I'm a bit confused.

**Comment by davidnewhall** [comment]
Duplicate the dashboard and edit to fit the needs of your Kiosk. The dashboards I provide are examples and I never recommend editing them. I recommend building your own with those examples to display the data just the way you want it. [Explained more here](https://github.com/unifi-poller/unifi-poller/wiki/Grafana#dashboards).

**Comment by fribse** [comment]
Hi David, that was what I tried, I press copy, open a new dashboard and paste it.
But the graph is empty, so what am I doing wrong?
![image](https://user-images.githubusercontent.com/13660621/82014723-79fe2a80-967d-11ea-9c32-0f55406428c2.png)

**Comment by davidnewhall** [comment]
It looks like you copied only the single panel. Duplicate the entire dashboard and delete the panels you don't want. Probably easiest. You're missing the variables, and your query still references the `$Site` variable. You can also fix the query to have your site name instead of the variable.

**Comment by fribse** [comment]
Ahaa, now I'm beginning to understand this, I didn't know about the variables, gotcha.
Ok, so I altered the query, and removed all the extra boxes here and there to maximise available realestate for the graph, and now it looks much better, thankyou, you are a gem!
