### ISSUE TITLE
Unbound metrics cardinality

### ISSUE THREAD

**Issue by paulfantom** [unifi-poller/unifi-poller#231]
Metric `unifipoller_device_info` has unbound cardinality due to the constantly mutating value of `uptime` and `bytes` labels. This is causing unnecessary memory issues on prometheus side.

Those labels should be converted into metrics where only the metric value is changing. Sth like:
```
unifipoller_device_info
unifipoller_device_uptime_seconds
unifipoller_device_bytes
```

According to [prometheus docs](https://prometheus.io/docs/practices/naming/#labels) label keys and values should be static and predictable.

More on prometheus cardinality: https://www.robustperception.io/cardinality-is-key

**Comment by davidnewhall** [comment]
Can you go further and show me how to make that work in my existing Grafana panels?

**Comment by paulfantom** [comment]
There are already examples in dashboards on how to use such metrics (it should be easier without placing values in labels). For example in network sites there are queries using `unifipoller_site_uptime_seconds` metric or `unifipoller_site_transmit_rate_bytes`.

The first thing is to make application not expose those data sets in labels but as a metric value. After that changing it in dashboards is just an easy expression change.

---
Side question: are those dashboards in any repository so I could make contributions or are those only on grafana.com?

**Comment by SuperQ** [comment]
Yes, the dashboards are in https://github.com/unifi-poller/dashboards

**Comment by davidnewhall** [comment]
I've got this taken care of. Thanks for the bug report! Will be fixed in next release.
