### ISSUE TITLE
Installation issues on ARM64 arch

### ISSUE THREAD

**Issue by paulfantom** [unifi-poller/unifi-poller#232]
Current container images lock application only to `linux/arm64/armv8` but I don't see any reason why this couldn't be broadened to `linux/arm64`. Especially considering that this line is not so restrictive: https://github.com/unifi-poller/unifi-poller/blob/master/Makefile#L116-L119. I see that this is possibly only a container manifest change and nothing else.

Such tight restriction of CPU architecture causes problems when running in distributed environments (for example in k8s/k3s).

**Comment by davidnewhall** [comment]
Try the `master` tag.

**Comment by davidnewhall** [comment]
Have you built multi-architecture Docker images? You're talking about "restrictions" like you have. If that's the case, please tell me how to create the image correctly. ie. Provide the `docker manifest` commands. Thanks! ex: https://github.com/unifi-poller/unifi-poller/blob/master/init/docker/hooks/push#L40

**Comment by paulfantom** [comment]
It is a simple fix to change:
```
docker manifest annotate ${DOCKER_REPO}:${tag} ${IMAGE_NAME}_${os}_${name} --os ${os} --arch ${arch} --variant "${vari}"
```
into
```
docker manifest annotate ${DOCKER_REPO}:${tag} ${IMAGE_NAME}_${os}_${name} --os ${os} --arch ${arch}
```

You don't use variant either way.

**Comment by davidnewhall** [comment]
`BUILDS` is defined in Travis-CI. Thanks! I will build an image without the variant and make sure it works. I simply didn't know that was an option.

**Comment by paulfantom** [comment]
It would be good to define public travis environment variables in `.travis.yml`. This way others could test it too :)

**Comment by davidnewhall** [comment]
It's in the README. https://github.com/unifi-poller/unifi-poller/tree/master/init/docker/hooks

**Comment by paulfantom** [comment]
Yes, but no one can do a PR to fix this :)

**Comment by JanHBade** [comment]
```
ERROR: for unifi-poller  no matching manifest for linux/arm64/v8 in the manifest list entries
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries
```

pull from a RasPi 4 with UbuntuServer 64Bit

**Comment by davidnewhall** [comment]
I've moved all env variables into the repo and out of docker hub.
