### ISSUE TITLE
Grafana panel plugin "stat" not found

### ISSUE THREAD

**Issue by bothorsen** [unifi-poller/unifi-poller#233]
I just installed the unifi-poller, and this works fine. But in the Grafana view for the USG, I get an error in the top views saying "Panel plugin not found: stat".

I have this in all views above USG load average except the one on the left with the numbers.

Since it can't find the stat plugin, I tried some others in the view with USG test time and uplink latency. The one called "singlestat" gave series errors. The Bar gauge plugin shows something.

There was no mention in the docs about installing new Grafana plugins. Is this necessary?

**Comment by davidnewhall** [comment]
[What's new in Grafana 6.6](https://grafana.com/docs/grafana/latest/guides/whats-new-in-v6-6/)
> Panels: New stat panel

Either upgrade to Grafana 6.6+ or change the stat panel to singlestat.
