### ISSUE TITLE
issue connecting with udm pro using docker compose

### ISSUE THREAD

**Issue by yulicrunchy** [unifi-poller/unifi-poller#234]
Hello,

I am seeing these errors when using the docker compose file from this repo to test against the UDM Pro using firmware 1.7.0.

Here are my errors in the unifi-poller:

```
2020/05/25 19:57:47.916467 influxdb.go:75: [ERROR] metric fetch for InfluxDB failed: re-authenticating to https://10.0.1.1:443/network/site/default: unifi controller: unable to get server version: invalid character '<' looking for beginning of value
2020/05/25 19:57:47.917088 influxdb.go:85: [ERROR] influxdb.Write(points): {"error":"database not found: \"unifi\""}
```

Any guidance would be appreciated. Thanks.

**Comment by davidnewhall** [comment]
Create the database in InfluxDB.

https://github.com/unifi-poller/unifi-poller/wiki/InfluxDB#influxdb

**Comment by yulicrunchy** [comment]
@davidnewhall thanks for the help. It turns out the error I was seeing about the endpoint for UDM-Pro was actually a separate issue:

```2020/05/25 19:57:47.916467 influxdb.go:75: [ERROR] metric fetch for InfluxDB failed: re-authenticating to https://10.0.1.1:443/network/site/default: unifi controller: unable to get server version: invalid character '<' looking for beginning of value```

I was using the endpoint `https://10.0.1.1/network/site/default` for `UNIFI_URL`, when just the IP address is enough: `UNIFI_URL=`https://10.0.1.1`.

Hope this helps someone else.
