### ISSUE TITLE
build fails even after re-release

### ISSUE THREAD

**Issue by Obre** [unifi-poller/unifi-poller#236]
still having build problems via brew
what can we do?

==> Installing unifi-poller from golift/mugs
==> Downloading https://golift.io/unifi-poller/archive/v2.0.0.tar.gz
Already downloaded: /Users/olegbrendel/Library/Caches/Homebrew/downloads/e70b0b04eba4252ac2249c8f2008a520ae1c9f64949edafe491ab2820b4dbe96--unifi-poller-2.0.0.tar.gz
Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.

==> make install VERSION=2.0.0 ITERATION=763 PREFIX=/usr/local/Cellar/unifi-poller/2.0.0 ETC=/usr/local/etc
Last 15 lines from /Users/olegbrendel/Library/Logs/Homebrew/unifi-poller/01.make:
go run github.com/github/hub/md2roff-bin --manual unifi-poller --version 2.0.0 --date "2020-06-02T14:56:57Z" examples/MANUAL.md
go run github.com/github/hub/md2roff-bin --manual unifi-poller --version 2.0.0 --date "2020-06-02T14:56:57Z" README.md
gzip -9nc examples/MANUAL > unifi-poller.1.gz
mv examples/MANUAL.html unifi-poller_manual.html
Done Building! -
- Local installation with the Makefile is only supported on macOS.
If you wish to install the application manually on Linux, check out the wiki: https://https://github.com/unifi-poller/unifi-poller/wiki/Installation
- Otherwise, build and install a package: make rpm -or- make deb
See the Package Install wiki for more info: https://https://github.com/unifi-poller/unifi-poller/wiki/Package-Install
# Copying the binary, config file, unit file, and man page into the env.
/usr/bin/install -m 0755 -d /usr/local/Cellar/unifi-poller/2.0.0/bin /usr/local/Cellar/unifi-poller/2.0.0/share/man/man1 /usr/local/etc/unifi-poller /usr/local/Cellar/unifi-poller/2.0.0/share/doc/unifi-poller /usr/local/Cellar/unifi-poller/2.0.0/lib/unifi-poller
/usr/bin/install -m 0755 -cp unifi-poller /usr/local/Cellar/unifi-poller/2.0.0/bin/unifi-poller
/usr/bin/install -m 0755 -cp *darwin.so /usr/local/Cellar/unifi-poller/2.0.0/lib/unifi-poller/
zsh:1: no matches found: *darwin.so
make: *** [install] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/golift/homebrew-mugs/issues

Error: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.

**Comment by davidnewhall** [comment]
Copy the binary from the releases page and the config file from the repo. Put them in place manually. Brew has not been fixed yet.

**Comment by davidnewhall** [comment]
Dup #200

**Comment by Obre** [comment]
Pardon me @davidnewhall 
Config file is which exactly?

**Comment by davidnewhall** [comment]
Well, at this point, version 2.0.1 fixes the issue.

```
brew install unifi-poller
```
