### ISSUE TITLE
Not all metrics showing up

### ISSUE THREAD

**Issue by mukeshchsrivastava** [unifi-poller/unifi-poller#238]
Hi Everyone,

Sorry if this is not the right forum. I am new with the influxdb and Grafana. I have imported the dashboard: https://grafana.com/grafana/dashboards/10418
But not all the metrics are showing up, such as Wireless and wired devices, switch bandwidth, wireless devices, wifi client AP, Switch bandwidth and several others.
I am using a Unifi Dream Machine, couldn't find any specific dashboard for this device type. I assumed that since this device has Switch and Access Point built-in the above mentioned dashboard should have worked. 
Any suggestions, please?

Regards,
Mukesh
![Grafana](https://user-images.githubusercontent.com/44853181/83930450-02826d80-a7db-11ea-9cc4-c2b1f93f06e6.jpg)

**Comment by davidnewhall** [comment]
Upgrade InfluxDB.

**Comment by mukeshchsrivastava** [comment]
Thanks @davidnewhall 
The database is already updated:

sudo apt upgrade influxdb -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
influxdb is already the newest version (1.6.4-1build1).

**Comment by davidnewhall** [comment]
Please read the first paragraph of the [InfluxDB wiki page](https://github.com/unifi-poller/unifi-poller/wiki/InfluxDB).

**Comment by mukeshchsrivastava** [comment]
Thanks David, reinstalled everything.
Most of the dashboards are working except the client dpi one https://grafana.com/grafana/dashboards/10419. Noticed that it's unable to find the sites. Any suggestions to solve this one, please?
![Client-DPI](https://user-images.githubusercontent.com/44853181/84567428-f9396800-adbb-11ea-827e-bf0dbf35d7ab.png)

**Comment by davidnewhall** [comment]
If this is now using InfluxDB 1.7.x the next step to getting DPI data is to enable it on both the controller and in the poller config. Two spots.

**Comment by mukeshchsrivastava** [comment]
Thanks David, it was disabled in the Poller Config. It's working now.
