### ISSUE TITLE
very new to docker and tried using docker-compose but running into an issue

### ISSUE THREAD

**Issue by KellyMahan** [unifi-poller/unifi-poller#241]
I haven't set any variables yet but golift/unifi-poller is throwing an error about no image

docker-compose.exe -f .\docker-compose.yml up
WARNING: The INFLUXDB_DB variable is not set. Defaulting to a blank string.
WARNING: The INFLUXDB_HTTP_AUTH_ENABLED variable is not set. Defaulting to a blank string.
WARNING: The INFLUXDB_ADMIN_USER variable is not set. Defaulting to a blank string.
WARNING: The INFLUXDB_ADMIN_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The GRAFANA_USERNAME variable is not set. Defaulting to a blank string.
WARNING: The GRAFANA_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The POLLER_TAG variable is not set. Defaulting to a blank string.
WARNING: The UNIFI_USER variable is not set. Defaulting to a blank string.
WARNING: The UNIFI_PASS variable is not set. Defaulting to a blank string.
WARNING: The UNIFI_URL variable is not set. Defaulting to a blank string.
WARNING: The POLLER_DEBUG variable is not set. Defaulting to a blank string.
WARNING: The POLLER_SAVE_DPI variable is not set. Defaulting to a blank string.
ERROR: no such image: golift/unifi-poller:: invalid reference format

**Comment by davidnewhall** [comment]
I've got plenty of people using it. What may be different about your environment?

**Comment by davidnewhall** [comment]
How about if you do:
```
docker pull golift/unifi-poller
docker run golift/unifi-poller
```

I just test these commands on my mac and it worked OK. `docker run golift/unifi-poller -v` should print out the version: `v2.0.1-787`.

**Comment by KellyMahan** [comment]
Running windows 10, installed docker desktop. The last 2 commands ran without error

**Comment by davidnewhall** [comment]
I think you need to set some variables. Like at a minimum `POLLER_TAG`

**Comment by KellyMahan** [comment]
So it's just an unrelated error message?

**Comment by davidnewhall** [comment]
It's definitely related. https://github.com/unifi-poller/unifi-poller/blob/master/init/docker/docker-compose.yml#L44

**Comment by KellyMahan** [comment]
ohh ya I missed that, Like I said, brand new to docker =)
