### ISSUE TITLE
Error in Grafana: "Invalid interval string, expecting a number followed by one of "Mwdhmsy"

### ISSUE THREAD

**Issue by chrisrueckert** [unifi-poller/unifi-poller#242]
I've installed all prerequisites and get the error "Invalid interval string, expecting a number followed by one of "Mwdhmsy"" in Grafana.

Controller version used: 5.13.29

Any hints where the error is coming from?

**Comment by davidnewhall** [comment]
Maybe you can give me a few more hints where it's coming from. What version of Grafana? What dashboard?

**Comment by chrisrueckert** [comment]
David, 

Grafana version: v6.6.1 (21bf8b71bc)
Dashboards: I tried UAP, Sites, and DPI. All of the three showed the same error (see screenshot).

![image](https://user-images.githubusercontent.com/43147497/84777430-ddafa680-afe1-11ea-9c28-bfa651f8b8a4.png)

**Comment by davidnewhall** [comment]
Great, glad you found the problem!
