### ISSUE TITLE
UNRESOLVED: Add VLAN data dashboards

### ISSUE THREAD

**Issue by revilo951** [unifi-poller/unifi-poller#244]
From inspecting the influx database, it doesn't look like any VLAN data is collected. If this is possible that'd be very handy.

Also, thank you for an incredible set of tools :)

edit: should add, I don't have a USG, just USWs and UAPs

**Comment by davidnewhall** [comment]
Can you be more specific? What data are you looking for? Is it in the UniFi API?

**Comment by revilo951** [comment]
I'm not sure if it's in the API, sorry. I'd like to be able to graph traffic per vlan, if that makes sense. EG if I have an IoT VLAN and a LAN VLAN, I'd like to be able to see which VLAN is carrying how much traffic.

**Comment by davidnewhall** [comment]
I looked in the clients and devices API data. I do not see the information there for vlans (there is a vlans field but it's `0` for all - I have 4 vlans). I'm not sure if the data you seek is available. Does the UniFi controller present the data broken down per vlan?

**Comment by revilo951** [comment]
hmm, I can't find the data presented in the unifi controller. that's a shame.

heres hoping ui add it sometime, but what are the odds of that?
