### ISSUE TITLE
add to freebsd ports tree

### ISSUE THREAD

**Issue by antxxxx** [unifi-poller/unifi-poller#245]
This is to track adding this to freebsd ports tree. This will make installation on freebsd in line with how programs are installed on freebsd

Request for this is at https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=247338

**Comment by davidnewhall** [comment]
Will keep an eye on it. Thanks!

**Comment by davidnewhall** [comment]
Amazing. It looks like they accepted it. Now, how do we keep it up to date? I plan to release a new version soon, and curious how that gets updated. How does one install this on FreeBSD now? `port install unifi-poller`? (I haven't used BSD in years..)

**Comment by antxxxx** [comment]
I was waiting for FreeBSD CI to build it so it can be easily installed before updating this. It looks like this has happened now.    
You can install it using `pkg install unifi-poller`. I have created a pull request on the wiki at https://github.com/unifi-poller/wiki/pull/15 with updated instructions.

To update the version in ports I need to submit a patch with an updated Makefile that points to the new version you have released and get that merged. I also have some updates based on feedback of the original submission that I made (unrelated to your code). If you are going to release a new version soon I will just include them in there.   
As the port gets a tagged version from this repo, I don't think I can prepare the updated port until you create a new release, but as soon as you do I will create a new version and submit the patch for it

**Comment by davidnewhall** [comment]
Thank you so much! wiki updated. https://github.com/unifi-poller/unifi-poller/wiki/Installation
