### ISSUE TITLE
RESOLVED: Panel plugin not found: table-old and DPI Dashboard: No data

### ISSUE THREAD

**Issue by isujosh** [unifi-poller/unifi-poller#248]
The dashboard is throwing an error "Panel plugin not found: table-old"

Not sure which plugin this is referring to?

Apart from that, the Unifi Poller is superb!

**Comment by isujosh** [comment]
This is where it is referenced in the JSON Model

    "timeFrom": "5m",
      "title": "Wired Devices",
      "transform": "table",
      "type": "table-old"

**Comment by davidnewhall** [comment]
Upgrading Grafana will solve this. The dashboards are exported from Grafana 7.

**Comment by isujosh** [comment]
Many thanks. 

I am on Grafana 6.6.1 - but apt-get update & upgrade doesn't find version 7, so I'll check up on doing this manually.

**Comment by davidnewhall** [comment]
You may follow the Ubuntu instructions here. https://github.com/unifi-poller/unifi-poller/wiki/Grafana#ubuntu-1804

**Comment by isujosh** [comment]
I'm running unifi-poller on a raspberry pi 4 and it doesn't look like there is a Grafana 7 distro for raspian/buster unless I'm missing something

**Comment by davidnewhall** [comment]
I'd assume you're missing something. Grafana runs on pretty much any OS.

**Comment by isujosh** [comment]
Managed to get Grafana 7.0.5 installed - thanks for pointing me in the right direction.

I now have a new problem with the Client-DPI dashboard - none of the panels are populating with data. It appears as if there is no site name - the only option is 'None'

![image](https://user-images.githubusercontent.com/38072419/86182245-805e3e00-bb27-11ea-9d84-f860703d3091.png)

**Comment by davidnewhall** [comment]
DPI must be enabled in the controller and in the poller config. Two spots.

**Comment by isujosh** [comment]
I have it enabled in the controller already - but only just noticed the 'save_dpi = true' option in up.conf

I'll try this again tomorrow and let you know how I get on - thanks again!

**Comment by isujosh** [comment]
That dashboard is populating with data now - I'll report back on any issues if that's helpful. Thanks yet again
