### ISSUE TITLE
Docker - unable to get interactive shell

### ISSUE THREAD

**Issue by bdf0506** [unifi-poller/unifi-poller#249]
On docker, I'm unable to get an interactive shell to see the config file, etc. Should a shell be available?

```
root@unraid:~$ docker exec -it unifi-poller bash
OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown

root@unraid:~$ docker exec -it unifi-poller /bin/bash
OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown

root@unraid~:$ docker exec -it unifi-poller /bin/sh
OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory": unknown

**Comment by paulfantom** [comment]
This image is based on https://github.com/unifi-poller/unifi-poller/blob/master/init/docker/Dockerfile#L24 which doesn't have anything apart from what is needed by unifi-poller application. This means no shell is present in the container.

Why do you need interactive shell in the first place?

**Comment by bdf0506** [comment]
Thanks, good to know. Figured I would check out the config file that was created, however, appears that when setting this up via docker, you just enter the variables and cross your fingers (I was able to get it working as needed). I see that docker logs does work at least, but looks like there is no shell at all.

**Comment by paulfantom** [comment]
> appears that when setting this up via docker, you just enter the variables and cross your fingers

Same as you would do with a binary :)

---
Not having a shell inside a container is following one of best practices in container security - choosing minimal base image. This in turn transfers into overall security best practice of minimizing attack surface and having least possible privileges.

**Comment by bdf0506** [comment]
Fair point. Thanks!

**Comment by davidnewhall** [comment]
The config file pre-loaded in the docker container is the exact same [config file you'll find in the repo](https://github.com/unifi-poller/unifi-poller/blob/master/examples/up.conf.example). You can overlay your own config file into the container or you can configure poller using environment variables.
