### ISSUE TITLE
Poller v2 will not start with v1 config file on macOS.

### ISSUE THREAD

**Issue by Oleg187** [unifi-poller/unifi-poller#250]
Hey,

on my computer (MacOS Catalina) there was a working unifi-poller (influx) running some months ago
then I did not use it for a while and forgot the admin password of Grafana

So I had to re-install Grafana which I did

Now I can login to grafana and see my dashboards but they do not have data

- i did not change anything related to influx
- i did not change the user on my unifi-controller

How can I make unifi-poller work again like it in when set it up for the first time on this machine?

Is there a way to delete all influx data and simply create again? (note: there is NO way to do that with grafana. If you try to uninstall grafana and reinstall because you forgot your admin password - it will not work. You need to change the admin password on the SQLITE3 grafana.db even if you delete grafana the db data remains)

**Comment by Oleg187** [comment]
it really feels like I need to use another machine now..

**Comment by davidnewhall** [comment]
Hello,

Please explain how you installed poller. Make sure it's still running. Check the log file. Report any errors, so we can figure out what's happening. What version of InfluxDB are you running?

**Comment by Oleg187** [comment]
Initially in the beginning of the year I did it via following all the steps described here
https://github.com/unifi-poller/unifi-poller/wiki/Installation for Mac

🤦 of course the log file

see it contents please

`2020/02/07 14:51:10 [INFO] UniFi Metrics Recorded. Sites: 3, Clients: 295, UAP: 16, USG/UDM: 3, USW: 9, Points: 593, Fields: 16562, Errs: 0, Elapsed: 80ms
2020/06/22 15:01:11 [INFO] Loading Configuration File: /usr/local/etc/unifi-poller/up.conf
2020/06/22 15:01:11 [INFO] UniFi Poller v2.0.1-790 Starting Up! PID: 34794
2020/06/22 15:01:11 [INFO] UniFi input plugin disabled or missing configuration!
2020/06/22 15:01:11 [INFO] InfluxDB config missing (or disabled), InfluxDB output disabled!
2020/06/22 15:01:11 [INFO] Prometheus exported at https://0.0.0.0:9130/ - namespace: unifipoller
2020/06/22 15:51:19 [INFO] Loading Configuration File: /usr/local/etc/unifi-poller/up.conf
2020/06/22 15:51:20 [INFO] UniFi Poller v2.0.1-790 Starting Up! PID: 669
2020/06/22 15:51:20 [INFO] UniFi input plugin disabled or missing configuration!
2020/06/22 15:51:20 [INFO] InfluxDB config missing (or disabled), InfluxDB output disabled!
2020/06/22 15:51:20 [INFO] Prometheus exported at https://0.0.0.0:9130/ - namespace: unifipoller
2020/06/23 14:28:24 [INFO] Loading Configuration File: /usr/local/etc/unifi-poller/up.conf
2020/06/23 14:28:24 [INFO] UniFi Poller v2.0.1-790 Starting Up! PID: 11532
2020/06/23 14:28:24 [INFO] UniFi input plugin disabled or missing configuration!
2020/06/23 14:28:24 [INFO] InfluxDB config missing (or disabled), InfluxDB output disabled!
2020/06/23 14:28:24 [INFO] Prometheus exported at https://0.0.0.0:9130/ - namespace: unifipoller
2020/06/23 18:25:29 [INFO] Loading Configuration File: /usr/local/etc/unifi-poller/up.conf
2020/06/23 18:25:29 [INFO] UniFi Poller v2.0.1-790 Starting Up! PID: 870
2020/06/23 18:25:29 [INFO] UniFi input plugin disabled or missing configuration!
2020/06/23 18:25:29 [INFO] InfluxDB config missing (or disabled), InfluxDB output disabled!
2020/06/23 18:25:29 [INFO] Prometheus exported at https://0.0.0.0:9130/ - namespace: unifipoller
2020/06/26 15:29:21 [INFO] Loading Configuration File: /usr/local/etc/unifi-poller/up.conf
2020/06/26 15:29:21 [INFO] UniFi Poller v2.0.1-790 Starting Up! PID: 1196
2020/06/26 15:29:21 [INFO] UniFi input plugin disabled or missing configuration!
2020/06/26 15:29:21 [INFO] InfluxDB config missing (or disabled), InfluxDB output disabled!
2020/06/26 15:29:21 [INFO] Prometheus exported at https://0.0.0.0:9130/ - namespace: unifipoller
2020/06/29 18:24:47 [INFO] Loading Configuration File: /usr/local/etc/unifi-poller/up.conf
2020/06/29 18:24:47 [INFO] UniFi Poller v2.0.1-790 Starting Up! PID: 627
2020/06/29 18:24:47 [INFO] UniFi input plugin disabled or missing configuration!
2020/06/29 18:24:47 [INFO] InfluxDB config missing (or disabled), InfluxDB output disabled!
2020/06/29 18:24:47 [INFO] Prometheus exported at https://0.0.0.0:9130/ - namespace: unifipoller
2020/06/30 10:05:57 [INFO] Loading Configuration File: /usr/local/etc/unifi-poller/up.conf
2020/06/30 10:05:57 [INFO] UniFi Poller v2.0.1-790 Starting Up! PID: 743
2020/06/30 10:05:57 [INFO] UniFi input plugin disabled or missing configuration!
2020/06/30 10:05:57 [INFO] InfluxDB config missing (or disabled), InfluxDB output disabled!
2020/06/30 10:05:57 [INFO] Prometheus exported at https://0.0.0.0:9130/ - namespace: unifipoller
2020/07/01 13:37:46 [INFO] Loading Configuration File: /usr/local/etc/unifi-poller/up.conf
2020/07/01 13:37:46 [INFO] UniFi Poller v2.0.1-790 Starting Up! PID: 638
2020/07/01 13:37:46 [INFO] UniFi input plugin disabled or missing configuration!
2020/07/01 13:37:46 [INFO] InfluxDB config missing (or disabled), InfluxDB output disabled!
2020/07/01 13:37:46 [INFO] Prometheus exported at https://0.0.0.0:9130/ - namespace: unifipoller
2020/07/06 11:31:07 [INFO] Loading Configuration File: /usr/local/etc/unifi-poller/up.conf
2020/07/06 11:31:07 [INFO] UniFi Poller v2.0.1-790 Starting Up! PID: 765
2020/07/06 11:31:07 [INFO] UniFi input plugin disabled or missing configuration!
2020/07/06 11:31:07 [INFO] InfluxDB config missing (or disabled), InfluxDB output disabled!
2020/07/06 11:31:07 [INFO] Prometheus exported at https://0.0.0.0:9130/ - namespace: unifipoller
2020/07/06 15:22:47 [INFO] Loading Configuration File: /usr/local/etc/unifi-poller/up.conf
2020/07/06 15:22:47 [INFO] UniFi Poller v2.0.1-790 Starting Up! PID: 902
2020/07/06 15:22:47 [INFO] UniFi input plugin disabled or missing configuration!
2020/07/06 15:22:47 [INFO] InfluxDB config missing (or disabled), InfluxDB output disabled!
2020/07/06 15:22:47 [INFO] Prometheus exported at https://0.0.0.0:9130/ - namespace: unifipoller
2020/07/07 09:45:35 [INFO] Loading Configuration File: /usr/local/etc/unifi-poller/up.conf
2020/07/07 09:45:35 [INFO] UniFi Poller v2.0.1-790 Starting Up! PID: 619
2020/07/07 09:45:35 [INFO] UniFi input plugin disabled or missing configuration!
2020/07/07 09:45:35 [INFO] InfluxDB config missing (or disabled), InfluxDB output disabled!
2020/07/07 09:45:35 [INFO] Prometheus exported at https://0.0.0.0:9130/ - namespace: unifipoller
2020/07/07 16:25:25 [INFO] Loading Configuration File: /usr/local/etc/unifi-poller/up.conf
2020/07/07 16:25:25 [INFO] UniFi Poller v2.0.1-790 Starting Up! PID: 63469
2020/07/07 16:25:25 [INFO] UniFi input plugin disabled or missing configuration!
2020/07/07 16:25:25 [INFO] InfluxDB config missing (or disabled), InfluxDB output disabled!
2020/07/07 16:25:25 [INFO] Prometheus exported at https://0.0.0.0:9130/ - namespace: unifipoller
2020/07/07 16:42:52 [INFO] Loading Configuration File: /usr/local/etc/unifi-poller/up.conf
2020/07/07 16:42:52 [INFO] UniFi Poller v2.0.1-790 Starting Up! PID: 64414
2020/07/07 16:42:52 [INFO] UniFi input plugin disabled or missing configuration!
2020/07/07 16:42:52 [INFO] Prometheus exported at https://0.0.0.0:9130/ - namespace: unifipoller
2020/07/07 16:42:52 [INFO] InfluxDB config missing (or disabled), InfluxDB output disabled!
2020/07/07 16:48:27 [INFO] Loading Configuration File: /usr/local/etc/unifi-poller/up.conf
2020/07/07 16:48:27 [INFO] UniFi Poller v2.0.1-790 Starting Up! PID: 64830
2020/07/07 16:48:27 [INFO] UniFi input plugin disabled or missing configuration!
2020/07/07 16:48:27 [INFO] Prometheus exported at https://0.0.0.0:9130/ - namespace: unifipoller
2020/07/07 16:48:27 [INFO] InfluxDB config missing (or disabled), InfluxDB output disabled!
2020/07/07 16:56:09 [INFO] Loading Configuration File: /usr/local/etc/unifi-poller/up.conf
2020/07/07 16:56:09 [INFO] UniFi Poller v2.0.1-790 Starting Up! PID: 65302
2020/07/07 16:56:09 [INFO] UniFi input plugin disabled or missing configuration!
2020/07/07 16:56:09 [INFO] InfluxDB config missing (or disabled), InfluxDB output disabled!
2020/07/07 16:56:09 [INFO] Prometheus exported at https://0.0.0.0:9130/ - namespace: unifipoller
2020/07/07 17:17:59 [INFO] Loading Configuration File: /usr/local/etc/unifi-poller/up.conf
2020/07/07 17:17:59 [INFO] UniFi Poller v2.0.1-790 Starting Up! PID: 66472
2020/07/07 17:17:59 [INFO] UniFi input plugin disabled or missing configuration!
2020/07/07 17:17:59 [INFO] InfluxDB config missing (or disabled), InfluxDB output disabled!
2020/07/07 17:17:59 [INFO] Prometheus exported at https://0.0.0.0:9130/ - namespace: unifipoller`


the line from february is just 1 but before that line come hundreds of those lines so it was working in february!

**Comment by Oleg187** [comment]
how do I tell it to again use my influx?

**Comment by davidnewhall** [comment]
Can you show me your config file contents? I'm not sure why your logs are missing the first couple startup messages, where it prints the config file. It should be at `/usr/local/etc/unifi-poller/up.conf`.

**Comment by Oleg187** [comment]
`# UniFi Poller primary configuration file. TOML FORMAT #
# commented lines are defaults, uncomment to change.   #
########################################################

# If the controller has more than one site, specify which sites to poll here.
# Set this to ["default"] to poll only the first site on the controller.
# A setting of ["all"] will poll all sites; this works if you only have 1 site too.
sites = ["all"]

# The UniFi Controller only updates traffic stats about every 30 seconds.
# Setting this to something lower may lead to "zeros" in your data.
# If you're getting zeros now, set this to "1m"
interval = "30s"

# Turns on line numbers, microsecond logging, and a per-device log.
# The default is false, but I personally leave this on at home (four devices).
# This may be noisy if you have a lot of devices. It adds one line per device.
debug = false

# Turns off per-interval logs. Only startup and error logs will be emitted.
# Recommend enabling debug with this setting for better error logging.
quiet = false

# Which mode to run this application in. The default mode is "influx". Providing
# an invalid mode will also result in "influx". In this default mode the application
# runs as a daemon and polls the controller at the configured interval.
#
# Other options: "influxlambda",  "prometheus", "both"
#
# Mode "influxlambda" makes the application exit after collecting and reporting metrics
# to InfluxDB one time. This mode requires an external process like an AWS Lambda
# or a simple crontab to keep the timings accurate on UniFi Poller run intervals.
#
# Mode "prometheus" opens an HTTP server on port 9130 and exports the metrics at
# /metrics for polling collection by a prometheus server. This disables influxdb.
#
# Mode "both" runs the Prometheus HTTP server and InfluxDB poller interval at
# the same time.
mode = "influx"

# This controls on which ip and port /metrics is exported when mode is "prometheus".
# This has no effect in other modes. Must contain a colon and port.
http_listen = "0.0.0.0:9130"

# InfluxDB does not require auth by default, so the user/password are probably unimportant.
influx_url = "http://127.0.0.1:8086"
influx_user = "unifipoller"
influx_pass = "unifipoller"
# Be sure to create this database.
influx_db = "unifi"
# If your InfluxDB uses an invalid SSL cert, set this to true.
influx_insecure_ssl = false

# Make a read-only user in the UniFi Admin Settings.
unifi_user = "influxx"
# You may also set env variable UNIFI_PASSWORD instead of putting this in the config.
unifi_pass = "REMOVED"
unifi_url = "REMOVED"

# Some controllers or reverse proxy configurations do not allow cookies to be
# re-user on every request (every interval). This setting provides a workaround
# That causes the poller to re-auth (login) to the controller on every interval.
# Only enable this if you get login errors after 30 seconds. This will generate
# a few more requests to your controller every interval.
reauthenticate = false

# Enable collection of Intrusion Detection System Data (InfluxDB only).
# Only useful if IDS or IPS are enabled on one of the sites.
save_ids = false

# Enable collection of site data. This data powers the Network Sites dashboard.
# It's not valuable to everyone and setting this to false will save resources.
save_sites = true

# If your UniFi controller has a valid SSL certificate (like lets encrypt),
# you can enable this option to validate it. Otherwise, any SSL certificate is
# valid. If you don't know if you have a valid SSL cert, then you don't have one.
verify_ssl = false`


the user "influx" that I initially created on the controller in Feb. was deleted by me and a new one was created named "influxx"
But I did not change the password that is written in the up.conf file 
just added one "x" to the user

**Comment by davidnewhall** [comment]
You have an old config file. Do this to reinstall unifi-poller with a valid config file:

```
brew uninstall unifi-poller
rm -f /usr/local/etc/unifi-poller/up.conf
brew install unifi-poller
```

Then edit your config file and set the unifi and influxdb endpoints correctly.

**Comment by Oleg187** [comment]
Thank you very much for the help and the formatting

Now i get this in my log

2020/07/07 19:18:54 [INFO] Loading Configuration File: /usr/local/etc/unifi-poller/up.conf
2020/07/07 19:18:54 [ERROR] Near line 76 (last key parsed 'unifi.defaults.url'): Key 'unifi.defaults.url' has already been defined.
2020/07/07 19:19:04 [INFO] Loading Configuration File: /usr/local/etc/unifi-poller/up.conf
2020/07/07 19:19:04 [ERROR] Near line 76 (last key parsed 'unifi.defaults.url'): Key 'unifi.defaults.url' has already been defined.

**Comment by Oleg187** [comment]
![image](https://user-images.githubusercontent.com/67900534/86909581-94520300-c118-11ea-9ced-3f66ea572be0.png)
and it looks yellow instead of the normal green

**Comment by Oleg187** [comment]
got it working after doing

`sudo find / -name unifi-poller`
thanks again
