### ISSUE TITLE
WAN throughput

### ISSUE THREAD

**Issue by AlfaJackal** [unifi-poller/unifi-poller#251]
Compared to the Unifi Controller Stats, the WAN throughput differs from Unifi Poller. 

WAN Rx shows me 199Mb/s but these are only 90MB/s on my USG3

Why is that? Can anybody help me?

**Comment by davidnewhall** [comment]
You haven't provided enough information for someone else to accurately deduce why you're having a problem. Can you elaborate and provide screenshots?

**Comment by AlfaJackal** [comment]
Sure, I will try! 😊 
I have a gbit network. As you can see in the following screenshot:

Unifi Poller Stats: 
- WAN RX reaches 199 MB/s 
- WAN TX 7 MB/s

Compared to UCK stats:
- WAN download ca. 80 Mb/s
- WAN Upload ca. 30 Mb/s

![image](https://user-images.githubusercontent.com/17096950/87820204-f673dc00-c86d-11ea-85ab-704767708486.jpeg)

Please let me know if I can provide more details!

**Comment by davidnewhall** [comment]
There are gaps in your metric data. Instead of showing you the average of ~100, it's bouncing between 0 and 200 on every other poll. Increase your influxdb interval from 30s to 60s; this will likely smooth out the data and fix the display.

**Comment by AlfaJackal** [comment]
That definitely helped to smooth it out:
![image](https://user-images.githubusercontent.com/17096950/87826781-c92d2b00-c879-11ea-919e-9bedf29f475f.jpeg)

But the numbers are still wrong. It must not have been more than 125 MB/s which is the limit for my 1Gbit WAN.
Also, in comparison to measured speed by USG (and battle.net) is a huge gap - the correct download speed should have been around 90 Mb/s, which is not shown in grafana/influx.

**Comment by davidnewhall** [comment]
From here, it gets more complicated. You need to inspect the data UniFi is giving you from the API and determine if it's accurate. Poller doesn't manipulate the numbers, it just takes them from UniFi and writes them to InfluxDB. This command will produce raw JSON from the controller:
```
unifi-poller -j d
```

If you're running in docker you can do it like this:
```
docker run -it golift/unifi-poller -j d
```

You will need to provide the config variables that provide access to the controller, or pass `-c /path/to/up.conf` so it can authenticate to the controller. Run this a few times every minute and inspect the byte differences. You'll have to divide by time to figure out the rate (again, gets complicated).

**Comment by AlfaJackal** [comment]
I am running it from docker and could get the json data. Easiest thing for me is to look at  `tx-data` because I am backing up my Synology regularly so there is a constant upload stream.

I could find the `tx_bytes` even though it is pretty messy copying and pasting those date from CLI. For now I just did it for these two:

`"tx_bytes": 3106348700`
`"rx_bytes": 11347930424` 

Could you give an example what you mean by _"You'll have to divide by time to figure out the rate ..."_?

**Comment by AlfaJackal** [comment]
Ok, extracted data for about five minutes, tried to hit every 60s:

According to the upload speed shown in the UCK it must be around 20-25 MB/s.

Minute 1:
```
{
  "name": "wan",
  "ifname": "eth0",
  "ip": "",
  "netmask": "255.255.252.0",
  "mac": "",
  "up": true,
  "speed": 1000,
  "full_duplex": true,
  "rx_bytes": 12614060474,
  "rx_dropped": 12025,
  "rx_errors": 0,
  "rx_packets": 41798662,
  "tx_bytes": 563068477372828,
  "tx_dropped": 0,
  "tx_errors": 0,
  "tx_packets": 4377246692,
  "rx_multicast": 13962,
  "enable": true,
  "dns": [
    "127.0.0.1"
  ],
  "gateway": ""
}
```

Minute 2:
```
{
  "name": "wan",
  "ifname": "eth0",
  "ip": "",
  "netmask": "255.255.252.0",
  "mac": "",
  "up": true,
  "speed": 1000,
  "full_duplex": true,
  "rx_bytes": 12622565004,
  "rx_dropped": 12025,
  "rx_errors": 0,
  "rx_packets": 41874486,
  "tx_bytes": 563068726429625,
  "tx_dropped": 0,
  "tx_errors": 0,
  "tx_packets": 4377416207,
  "rx_multicast": 13992,
  "enable": true,
  "dns": [
    "127.0.0.1"
  ],
  "gateway": ""
}
```

Minute 3:
```
{
  "name": "wan",
  "ifname": "eth0",
  "ip": "",
  "netmask": "255.255.252.0",
  "mac": "",
  "up": true,
  "speed": 1000,
  "full_duplex": true,
  "rx_bytes": 12627018044,
  "rx_dropped": 12025,
  "rx_errors": 0,
  "rx_packets": 41913201,
  "tx_bytes": 563068853037263,
  "tx_dropped": 0,
  "tx_errors": 0,
  "tx_packets": 4377502486,
  "rx_multicast": 14011,
  "enable": true,
  "dns": [
    "127.0.0.1"
  ],
  "gateway": ""
}
```

Minute 4:
```
{
  "name": "wan",
  "ifname": "eth0",
  "ip": "",
  "netmask": "255.255.252.0",
  "mac": "",
  "up": true,
  "speed": 1000,
  "full_duplex": true,
  "rx_bytes": 12635759557,
  "rx_dropped": 12025,
  "rx_errors": 0,
  "rx_packets": 41990193,
  "tx_bytes": 563069106613591,
  "tx_dropped": 0,
  "tx_errors": 0,
  "tx_packets": 4377675153,
  "rx_multicast": 14040,
  "enable": true,
  "dns": [
    "127.0.0.1"
  ],
  "gateway": ""
}
```

Minute 5
```
{
  "name": "wan",
  "ifname": "eth0",
  "ip": "",
  "netmask": "255.255.252.0",
  "mac": "",
  "up": true,
  "speed": 1000,
  "full_duplex": true,
  "rx_bytes": 13073950592,
  "rx_dropped": 12375,
  "rx_errors": 0,
  "rx_packets": 42343539,
  "tx_bytes": 563069287668768,
  "tx_dropped": 0,
  "tx_errors": 0,
  "tx_packets": 4377822929,
  "rx_multicast": 14057,
  "enable": true,
  "dns": [
    "127.0.0.1"
  ],
  "gateway": ""
}
```

**Comment by davidnewhall** [comment]
And what do you see in Grafana during this same time period? 200? is it showing 10x higher or something?

**Comment by AlfaJackal** [comment]
This is from the standard Unifi-Poller: USG Dashboard:

![image](https://user-images.githubusercontent.com/17096950/87832045-56c24800-c885-11ea-8fb8-c6c813834999.jpeg)

**Comment by davidnewhall** [comment]
Looks like you're back to 30s. Your controller is not updating the data every 30 seconds, so you need to keep that increased to 60s or so.

**Comment by AlfaJackal** [comment]
Sure, I took the default USG dashboard. But even if I change it to 60s, the numbers are wrong.

**Comment by davidnewhall** [comment]
`UP_INFLUXDB_INTERVAL` << yup!

**Comment by davidnewhall** [comment]
Please re-open this issue if you have additional problems or questions I can help with. Thanks and good luck!
