### ISSUE TITLE
Remove or allow disabling of UniFi metrics from /metrics endpoint

### ISSUE THREAD

**Issue by cfunkhouser** [unifi-poller/unifi-poller#252]
Right now, the `/metrics` endpoint includes many (all?) of the same metrics from my controllers that I can get from the `/scrape` endpoint. In my monitoring setups, I traditionally use the `/metrics` endpoint of my various exporters to monitor the health of the exporter job itself. This works well for things like the `blackbox_exporter`, for example.

With `unifi-poller`, I am getting a bunch of duplicate metrics unnecessarily, which is growing my memory footprint for no gain. Is there a strong reason these metrics need to be included under the `/metrics` endpoint? Would you be opposed to a PR removing them, or - even better - adding a configuration option to gate their export there?

**Comment by davidnewhall** [comment]
Most folks have 1 controller and use the `/metrics` endpoint exclusively, so removing it is not an option. Gating those metrics on a config option seems OK.

Do you have `dynamic` enabled in your poller config?

**Comment by cfunkhouser** [comment]
> Most folks have 1 controller and use the /metrics endpoint exclusively...

Interesting. If it's the way most people do it, why is the "just use `/metrics`" approach "not recommended" in the Prometheus docs?

> Do you have `dynamic` enabled in your poller config?

No, I only have one controller right now, and already have other tools for "dynamic" target generation (read: a Rube Goldberg machine of shell scripts) that I'm using with Prometheus already. It was easy enough to hook this in, and the only thing scarier than the existing system is the existing system plus something else I could forget about. 😃

Anyway, I'll whip up a PR to do add the gate.

**Comment by davidnewhall** [comment]
For a single controller, using `/metrics` _is_ the recommend approach, described at the top of the [Prometheus wiki doc](https://github.com/unifi-poller/unifi-poller/wiki/Prometheus#single-controller). For multiple controllers, it is not recommended because it's "not the prometheus way" to receive metrics in a single scrape for multiple entities. The other approaches are recommended, but `/metrics` still works (for convenience?).

**Comment by davidnewhall** [comment]
Please re-open this issue if I can help with anything else here. If you submit a PR I'll take a look, but it sounds like the explanations above may be sufficient. Thank you and good luck!
