### ISSUE TITLE
Month over month data usage

### ISSUE THREAD

**Issue by User-042** [unifi-poller/unifi-poller#253]
I’m trying to create a picture of how much data were using month over month. but I can’t seem to figure out a measurement that seems even close to realistic which measurement do I choose

**Comment by davidnewhall** [comment]
You want the tx and rx bytes for your USG or UDM.

**Comment by davidnewhall** [comment]
Were you able to find the measurements?

**Comment by User-042** [comment]
yes

**Comment by davidnewhall** [comment]
Sweet! Let me know if I can help further!
