### ISSUE TITLE
Support for Timescale DB? Please +1

### ISSUE THREAD

**Issue by dnaq** [unifi-poller/unifi-poller#254]
I'm wondering how much work it would be to export the metrics to timescaledb instead of influxdb/Prometheus. I might have some time to put towards adding support if I could get some pointers on where to start, but I can't promise anything. So consider this issue a feature request together with a tentative offer to help. 😀

EDIT by @davidnewhall ->
Gauging interest: **Please click thumbs up on this issue if [Timescale DB](https://www.timescale.com/products/how-it-works) support interests you.**

**Comment by davidnewhall** [comment]
The system is module. Prometheus and InfluxDB are both handled by their respective Go libraries:
- https://github.com/unifi-poller/influxunifi
- https://github.com/unifi-poller/promunifi

There are open PRs in both of these repos to add new features. I'm also not entirely sure if the new features are setup the way I want, so things are likely to change. Both of these modules take their input data from the [unifi](https://github.com/unifi-poller/unifi) module, ultimately.

To create a new output module, I'd recommend forking or copying one of the existing output modules (above) and start changing things to work with the new database. If you're new to Go, this will be challenging. Good luck!

**Comment by dnaq** [comment]
Thanks for your reply. I'll take a look and see if I can find the time to whip something up.

**Comment by davidnewhall** [comment]
If you can get some base code laid down that write metrics to the database, I'm certainly willing to help polish it up. I just don't really have the time to setup and maintain a third database for this project right now. If you're familiar with the intricacies and caveats of TimeScale, your knowledge will be indispensable in making this work correctly. I look forward to seeing what you come up with! If you have question about how to make the library interact with the [poller](https://github.com/unifi-poller/poller) library, please hit me up. Discord works well. I haven't fully documented "how" to write a plugin and which methods are required, so some of it may seem strange.

**Comment by dnaq** [comment]
I just found out that timescaledb already integrates with prometheus as described [here](https://docs.timescale.com/tutorials/prometheus-adapter), so my use case will be solved by this. Maybe I'll have some time in the future to look more at this, but right now I won't be able to do so.

**Comment by davidnewhall** [comment]
That looks pretty slick, and appears to be a pretty good way to set things up. Nice find!
