### ISSUE TITLE
Latest Controller support

### ISSUE THREAD

**Issue by MatthewGCampbell** [unifi-poller/unifi-poller#256]
Running a UDM Pro with 1.7.2 which comes bundled with controller 5.13.30. Would the latest version support that or do I need to downgrade?

**Comment by davidnewhall** [comment]
No one's complained yet.

**Comment by MatthewGCampbell** [comment]
I got it to work its just I was also testing 1.8.0 and it doesn't seem to let you login via the IP so that's why I wasn't working just got my versions messed up. At lest with my UDM Pro it doesn't.

**Comment by davidnewhall** [comment]
I'll see if I can find some folks on Discord running 1.8.0 that can do some testing.

**Comment by MatthewGCampbell** [comment]
I flashed and then it seemed to work probably just a bug

**Comment by davidnewhall** [comment]
Cool cool! I talked to another gentleman in Discord and he said 1.8.0 was working OK for him. Glad you got it figured out!
