### ISSUE TITLE
InfluxDB Retention Policy

### ISSUE THREAD

**Issue by rodrigolangella** [unifi-poller/unifi-poller#259]
Hey David,

Could not find anything that could lead me to Retention Policies for InfluxDB.   It seems InfluxDB comes with infinite Retention Policy and this was filling up my partition in 75GB for about 3 months.   I've managed to create a new policy connecting to the database manually,  I'm wondering if there is any easier way or configuration file I've missed.  Perhaps future releases could count with 90Days retention policy instead of infinite?

Using Unifi-Poller in docker

**Comment by davidnewhall** [comment]
Hello! 

Data retention is dictated by the `create database` command. The [official docs are here](https://docs.influxdata.com/influxdb/v1.8/query_language/manage-database/#create-database).

To keep 2 weeks of data, you'd run a command like:
```
create database unifi with duration 14d
```

Hope that helps!

**Comment by johnny2678** [comment]
If you've already created the influxdb unifi database, you can alter the autogenerated retention policy.  You'll probably want to do this depending on what system you are running influx/grafana on.  

It doesn't look like any of the prebuilt dashboards show more than a day so I just issued:
`alter retention policy autogen on unifi DURATION 7d REPLICATION 1`

This project is really great - was up and gather data in 20 minutes with an existing influx/grafana install and unifi-poller running in docker.

Thanks so much!

**Comment by davidnewhall** [comment]
Some other folks use continuous queries to store specific data they care about long term, while setting the default retention policy to something short like a week. There are many many options available to store and collate your data in a way that works for your environment. It will require some tinkering with InfluxDB (or Prometheus if you go that route). Please re-open this issue if you have more questions. Good luck!
