### ISSUE TITLE
application-builder: should be run with a dedidacted user

### ISSUE THREAD

**Issue by M0NsTeRRR** [unifi-poller/unifi-poller#260]
Hello,

Unifi-poller should be run with a dedicated user, nobody user is used by NFS
check https://wiki.ubuntu.com/nobody for a full explanation

https://github.com/unifi-poller/unifi-poller/blob/12900b3e7120a1cae979b84604daab59f3918e5e/init/systemd/template.unit.service#L20

Best regards,

**Comment by davidnewhall** [comment]
The latest release runs the application as a dedicated user.
 https://github.com/unifi-poller/unifi-poller/releases/tag/v2.1.0
