### ISSUE TITLE
No file @rb_sysopen.....

### ISSUE THREAD

**Issue by farberm** [unifi-poller/unifi-poller#261]
I am having the following error installing on OS X...any help would be appreciated.

Updating Homebrew...
==> Installing unifi-poller from golift/mugs
==> Downloading https://golift.io/unifi-poller/archive/v2.0.1.tar.gz
Already downloaded: /Users/markfarber/Library/Caches/Homebrew/downloads/5aebcd014d73b54185a24b29e1653ffb3827f372138c2e6a6cffffbaf5a9d8ac--unifi-poller-2.0.1.tar.gz
==> make install VERSION=2.0.1 ITERATION=790 PREFIX=/usr/local/Cellar/unifi-poll
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ rb_sysopen - /usr/local/var/log/unifi-poller.log

**Comment by davidnewhall** [comment]
`mkdir -p /usr/local/var/log/` should fix it.

**Comment by davidnewhall** [comment]
Were you able to get this setup?

**Comment by farberm** [comment]
Yes that worked thanks

**Comment by davidnewhall** [comment]
Great!
