### ISSUE TITLE
Can't start bash from unifi-poller Docker container.

### ISSUE THREAD

**Issue by scyto** [unifi-poller/unifi-poller#262]
When I try and start bash (or sh or ash) i get this:

![image](https://user-images.githubusercontent.com/11369180/90459239-944d0780-e0b5-11ea-812a-7e54dbceb4ab.png)

this error occurs for a couple of reasons
1. there is no shell in the path
2. i guessed the wrong shell name
3. there is no shell in the container
4. the container has an EXEC form entrypoint and not a CMD form entry point

It is *really* useful when troubleshooting to be easily able to shell in using the CMD form, in this case i am not sure which of the 4 items above is (i assumed 4 but can't find what the runtime entrypoint is given all the golift stuff being used).

I guess my ask is can you clarify if this is an issue because your shell isn't bash, ash or sh OR if this is the EXEC form of entrypoint is being used?

alex

**Comment by davidnewhall** [comment]
The docker container contains only one binary: `unifi-poller` and a config file for it. There is no bash, there is no OS, there's nothing else to execute. The entire contents of the docker image are in the GitHub repo (minus the binary which is built by docker hub).

**Comment by scyto** [comment]
Oh that’s a good explanation, as such closing.
