### ISSUE TITLE
UDM built in AP Stats are missing/wrong

### ISSUE THREAD

**Issue by HeedfulCrayon** [unifi-poller/unifi-poller#263]
If you look at my grafana dashboard, it is completely missing data from my UDM (labeled as Eve in the image), when I have multiple clients connected to it.
![image](https://user-images.githubusercontent.com/5224972/90567298-2a8d3600-e167-11ea-9663-21abb3f42ec3.png)

**Comment by davidnewhall** [comment]
What data does the UniFi API return for this device? Poller just writes to the database what the controller gives it.

`unifi-poller -j devices` will print out the raw device json.

**Comment by HeedfulCrayon** [comment]
I can't seem to run that command as I am running this inside a docker container on my synology nas.  It won't let me access the terminal

**Comment by HeedfulCrayon** [comment]
You're right, it isn't missing data, it is just saying my client connection quality is 0 on my UDM AP, but that is not right... I have multiple clients connected to it that are performing just fine

**Comment by davidnewhall** [comment]
You can download unifi-poller binaries are run them locally. You can also use `docker run -ti golift/unifi-poller -j devices`. As for your controller reporting a CCQ of 0 - you may want to ask UniFi support why that's the case.

**Comment by HeedfulCrayon** [comment]
ok.  Makes sense that this is more of a unifi issue than your poller, since it is getting data, and the other graphs are also getting data other than 0.  Thank you
