### ISSUE TITLE
Unifi-poller compatible with UDMP?

### ISSUE THREAD

**Issue by shan52** [unifi-poller/unifi-poller#265]
Hi,
I tried to run Unifi-poller  on my Unraid server 
`[ERROR] metric fetch for InfluxDB failed: re-authenticating to https://192.168.1.1:8443: unifi controller: Get "https://192.168.1.1:8443/": dial tcp 192.168.1.1:8443: connect: connection refused`

I followed the installation guide and everything should worked..

**Comment by davidnewhall** [comment]
Your UDMP listens on port 443 not 8443. Remove `:8443` from the configured URL.

**Comment by shan52** [comment]
Thanks it worked! Would be great if you could add this information in the wiki.

**Comment by davidnewhall** [comment]
I'm working on something even better than that. ;)
