### ISSUE TITLE
URL Parsing Issue

### ISSUE THREAD

**Issue by tibmeister** [unifi-poller/unifi-poller#267]
using stable image in docker swarm and getting error:

[ERROR] Controller 1 Auth or Connection Error, retrying: unifi controller: parse "\"https://192.168.15.71:8443\"/": first path segment in URL cannot contain colon
[ERROR] parse "\"http://influx-General:8086\"": first path segment in URL cannot contain colon

I can, via web browser, log in with the credentials and URL without issue.  Using unifipoller for username/password for testing, so no special char issues in the mess.

**Comment by davidnewhall** [comment]
Your URsL have quotes in them. `""https://192.168.15.71:8443""` and `""http://influx-General:8086""`

If you're not sure why, please share your configuration.

**Comment by tibmeister** [comment]
Well, in JSON one would typically quote a string value, and I forgot I'm dealing with YAML and not JSON.  Now that I got rid of the quotes, well, things seems to be working, if I'm reading this line correctly:

[INFO] Everything checks out! Poller started, InfluxDB interval: 30s

But now I'm getting 

[ERROR] influxdb.Write(points): {"error":"database not found: \"unifi\""}

Here's my compose lines for the environment variables

unifi-poller:
378     image: golift/unifi-poller:stable
379     networks:
380       - net
381     environment:
382       - UP_UNIFI_DEFAULT_URL=https://10.27.200.50:8443
383       - UP_UNIFI_DEFAULT_USER=unifipoller
384       - UP_UNIFI_DEFAULT_PASS=unifipoller
385       - UP_UNIFI_DEFAULT_SAVE_SITES=true
386       - UP_UNIFI_DEFAULT_SAVE_IDS=true
387       - UP_UNIFI_DEFAULT_SAVE_EVENTS=true
388       - UP_UNIFI_DEFAULT_SAVE_ALARMS=true
389       - UP_UNIFI_DEFAULT_SAVE_ANOMALIES=true
390       - UP_UNIFI_DEFAULT_SITE_0=[all]
391       - UP_INFLUXDB_URL=http://influx-General:8086
392       - UP_INFLUX_DB=unifi
393       - UP_INFLUXDB_INTERVAL=30s
394       - UP_PROMETHEUS_DISABLE=true
395     deploy:
396       placement:
397         constraints:
398           - node.role != manager

**Comment by scyto** [comment]
Did you make the database? Are your creds to access the database right?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by davidnewhall** [comment]
Glad it's working! Please check back in it you need more assistance.

**Comment by tedder** [comment]
FWIW, I had this and couldn't figure it out until this thread gave me some prompting. I had it in docker-compose like this:
```
    environment:
    - UP_UNIFI_DEFAULT_URL="https://10.11.12.13:443"
```

That is taken literally, including the quotes. This is correct:

```
    environment:
    - UP_UNIFI_DEFAULT_URL=https://10.11.12.13:443
```

This is true of all fields in a docker-compose.yml (and probably other setup methods). So I probably would have had problems with my UP_UNIFI_DEFAULT_PASS too.

Figured it was worth putting here for posterity.

**Comment by davidnewhall** [comment]
I guess I could go full shotgun and rip quotes off the strings. We'll see. Thanks for the update!

**Comment by tedder** [comment]
I don't think it would help much, because once you get to the password it's hard to know what the right thing to do is (well, I guess the odds of a password beginning and ending with quotes is low, though having one or more in the string wouldn't be).

If nothing else, a hint with the error message maybe.

**Comment by davidnewhall** [comment]
I put about 5 minutes of solid thought into this as I worked through each scenario in my head. Here it is:
1. If I rip all quotes including the password it will lead folks with a password ending in a quote on an hours-long wild goose chase they cannot win. This is the rarest of these 3 options.
2. If I rip all quotes including password, folks will not run into the error described in this thread. (same as 1)
3. If I rip all quotes except the password, folks will now struggle with a bad password error for hours when they quote all their strings.
4. If I leave it like it is now, folks will get a URL error immediately leading to a bad-quotes conclusion.

I'm leaning toward rip them all off and leave a warning that passwords ending in a quote are unacceptable.

**Comment by tedder** [comment]
Sounds good!
