### ISSUE TITLE
unifi-poller+unifi: Support neighbouring AP/rogue AP

### ISSUE THREAD

**Issue by carlneuhaus** [unifi-poller/unifi-poller#268]
Looking through what is returned via the API I noted neighbouring AP/rogue APs is returned via _stat/rogueap_.

Is it possible to add this endpoint?

**Comment by davidnewhall** [comment]
Can you provide the full API path? I'll pull it and see what numbers can be graphed.

**Comment by carlneuhaus** [comment]
The path I have (Cloud Key 2) is https://<controller>:8443/api/s/default/stat/rougeap?within=1&_limit=10000

**Comment by davidnewhall** [comment]
I'm just getting a 404... hm. Can you send me the output of this command? (or attach in a [gist](https://gist.github.com))
```
unifi-poller -j "other /api/s/default/stat/rougeap"
```

**Comment by carlneuhaus** [comment]
My mistake, I can not spell. 
Please update rougeap to rogueap
`unifi-poller -j "other /api/s/default/stat/rogueap"`

**Comment by davidnewhall** [comment]
I can get data there. Thanks!

**Comment by Ornias1993** [comment]
This is actually pretty usefull to have, keeping track of rogueAP's historically for security purposes!

**Comment by davidnewhall** [comment]
Seems to work. It's way more data than I want to collect. Every GM (and other) vehicle that drives by gets logged.
![Screen Shot 2021-03-21 at 10 46 14 PM](https://user-images.githubusercontent.com/2402929/111945657-507d0f00-8a97-11eb-9df1-0af44c6bd17a.png)

**Comment by davidnewhall** [comment]
The current release incorporates this feature: https://github.com/unifi-poller/unifi-poller/releases/tag/v2.1.0

I'll release new UAP dashboards that include the above (screen shot) table in a week or two. I'm not including graph panels, but they should be easy to make if that's what you'd like to have.

**Comment by ChoiZ** [comment]
Hello @davidnewhall can you please publish your new UAP dashboards for rogue AP alerts for unifi-poller v2.1.3?
