### ISSUE TITLE
unifi-poller: Add config option to keep disabled and down ports.

### ISSUE THREAD

**Issue by wetterfrosch** [unifi-poller/unifi-poller#270]
Hi there & let me say at first: Great tool! Thaks a much.

I performed a version-switch from ~1.5.something to v2.0.1-787 today, using a v5.12.35 controller and noticed that I just get information on currently active switch-ports. A drop and recreation of the influxDB didn't help.

**Comment by davidnewhall** [comment]
Only ports that are `up` and `enabled` have their numbers stored.

**Comment by wetterfrosch** [comment]
Thanks for clarification. I would like to configure that, in fact both options. Background of the use-case is that I like to monitor the appearance of devices based on link-speed or rx_bytes-r or so. My "truth" on "what should exist" would be defined through the string of the port-descriptions. 

By the way: There is a field/value "poe_voltage"; In my first approach I tried at least to "initiate" the ports with the setting of 24V passive-PoE, but the fact that there've been 24V hasn't been monitored ;)

**Comment by davidnewhall** [comment]
> By the way: There is a field/value "poe_voltage"; In my first approach I tried at least to "initiate" the ports with the setting of 24V passive-PoE, but the fact that there've been 24V hasn't been monitored ;)

Sorry, I don't really understand what you're telling me in this paragraph.

I can probably add a config flag to allow storing unused ports.

**Comment by wetterfrosch** [comment]
> Sorry, I don't really understand what you're telling me in this paragraph.

Point is that it might be very important to know if there is, in particular passive-PoE, active on a port or not (thus it might harm devices plugged to this port). From the IT-perspective its more a german Yoda saying "this world is not valid".

> I can probably add a config flag to allow storing unused ports.

I would appreciate this very very much! 

I would like to use these bits as "you have to fix this device/cable/socket"-reminder (again) :)

**Comment by davidnewhall** [comment]
I think I added this. Try https://github.com/unifi-poller/unifi-poller/releases/tag/v2.0.2-beta1

**Comment by davidnewhall** [comment]
This one is also in the current update as mentioned in #298. There is a new config option called `dead_ports`. Add it in your `[influxdb]` config.

```toml
[influxdb]
 dead_ports = true
```

Of you can use an env variable: `UP_INFLUXDB_DEAD_PORTS=true`

**Comment by wetterfrosch** [comment]
Thank you very much for this! (:

**Comment by davidnewhall** [comment]
The current release incorporates this feature: https://github.com/unifi-poller/unifi-poller/releases/tag/v2.1.0

**Comment by wetterfrosch** [comment]
Happy user reports: This is great and can look really great -- at least when Grafana supports natural sorting within tables :)

![grafik](https://github.com/unpoller/unpoller/assets/506253/2291f50c-627c-4079-b616-932fa81c5b58)
