### ISSUE TITLE
Question: Loki Logging via Environmental Variables (docker-compose)

### ISSUE THREAD

**Issue by lux4rd0** [unifi-poller/unifi-poller#272]
Just a quick question on this - looking for the details needed to add to my docker-compose in order to get the Loki configurations via environmental variables:

https://github.com/unifi-poller/unifi-poller/wiki/Configuration

```
[loki]
  url = "http://127.0.0.1:3100"
```

Thanks!

**Comment by davidnewhall** [comment]
Loki support is currently in the `dn2_events` branch and that feature has not yet made it into a released version. 

If you're using the Docker tag `events` then you have the correct code. You need to set something like `UP_LOKI_URL=http://127.0.0.1:3100`. These are other available config variables (from the [open PR that adds Look support](https://github.com/unifi-poller/unifi-poller/blob/dn2_events/examples/up.conf.example)):
```
[loki]
   url = ""
   # The rest of this is advanced & optional. See wiki.
   user       = ""
   pass       = ""
   verify_ssl = false
   tenant_id  = ""
   interval   = "2m"
   timeout    = "10s"
```
These Translate to `UP_LOKI_USER`, `UP_LOKI_TIMEOUT`, etc.

Does that answer your question?

**Comment by lux4rd0** [comment]
@davidnewhall - yes - it did!! I pulled your "golift/unifi-poller:events" docker image and configured it as:

`UP_LOKI_URL: http://fqdn:3100`

In my docker-compose.yml file. It started sending logs over just fine. Now to see about building some Grafana dashboards! Thanks again!!

**Comment by davidnewhall** [comment]
Enjoy! Please come back with any feedback you have!
