### ISSUE TITLE
"...(status: 500 ): authentication failed"

### ISSUE THREAD

**Issue by migueblanco** [unifi-poller/unifi-poller#273]
Hi,
I just recently installed the unifi-poller docker on my testing environment, but I've been having issue in getting it to connect to the unifi controller, this is the log:
<img width="1153" alt="Screen Shot 2020-10-19 at 12 06 24 PM" src="https://user-images.githubusercontent.com/22178182/96477776-e2d96800-1204-11eb-9669-b18a1ec87855.png">
this is the unifi-poller docker compose snippet:
  unifi-poller:
    image: golift/unifi-poller:latest
    container_name: unifi-poller
    restart: unless-stopped
    environment:
      - UP_INFLUXDB_DB="unifi"
      - UP_INFLUXDB_USER="unifipoller"
      - UP_INFLUXDB_PASS="testpass1234"
      - UP_INFLUXDB_URL=http://192.168.100.239:8086
      - UP_UNIFI_DEFAULT_USER="unifipoller"
      - UP_UNIFI_DEFAULT_PASS="testpass1234"
      - UP_UNIFI_DEFAULT_URL=https://192.168.100.239:8443
      - UP_POLLER_DEBUG=true
      - UP_UNIFI_DEFAULT_VERIFY_SSL=false
      - UP_UNIFI_DEFAULT_SAVE_DPI=false
I already created the datasource for influxdb in grafana, using the credentials above, so I know that part is working, but haven't any luck with the connection on the unifi controller.
Any help?

Thanks in advanced!

**Comment by davidnewhall** [comment]
You have the wrong username and password configured for your unifi controller. Or that user doesn't have access to the API. Try logging in with those credentials yourself and see if you can navigate the UI.

**Comment by migueblanco** [comment]
Thanks David, for your quick reply, so if I try to login this is what I got:
<img width="547" alt="Screen Shot 2020-10-19 at 2 42 04 PM" src="https://user-images.githubusercontent.com/22178182/96499372-51c1bb80-121b-11eb-8e07-495cb62ab6d2.png">

**Comment by davidnewhall** [comment]
You need to give the user account more privileges. Try `admin` to start and whittle it down from there. This part escapes me because I made my user 3 years ago and haven't looked at it much sense.

**Comment by migueblanco** [comment]
Thanks for your help David, yes, it was a permission issue, fixed right now, thanks again.
