### ISSUE TITLE
[Feature] Support Docker Healthcheck

### ISSUE THREAD

**Issue by Ornias1993** [unifi-poller/unifi-poller#274]
Applications do in theory all stall at time without `exit 1` at times, including Unifi-Poller. Thats the nature of being a computer program: Strange behavior does happen.

It would be nice if we could at least have a handle/call to setup a docker healthcheck or (preferably) include it in the dockerfile. That way we can easily catch such situations and restart the container.

It's also an advisory in the CIS docker security benchmark v1.2.0

TLDR:
Add docker Healthcheck.

**Comment by davidnewhall** [comment]
Can you show me a log of this happening?

**Comment by Ornias1993** [comment]
I didn't report any behavior, I requested a change of the dockerfile.

**Comment by davidnewhall** [comment]
You sure write that things come across arrogant. Thanks for the feature request.

**Comment by Ornias1993** [comment]
@davidnewhall It was meant to be quite arrogant tbh. :')
Good to know it hit it's mark :)

Was it needed? Totally not, but if someone submits a feature request it aint a bug report.

**Comment by davidnewhall** [comment]
Well in that case.

**Comment by Ornias1993** [comment]
@davidnewhall I always learned that issues should be evaluated on their merrits, not on your personal feelings. But it's your repo ofcoarse. Your repo your rules.

**Comment by davidnewhall** [comment]
I'm glad you learned things. That's valuable in this world.

**Comment by Ornias1993** [comment]
@davidnewhall Glad we agree about something today :)

**Comment by Ornias1993** [comment]
Anyhow, Ontopic:
are there any (sub) commands of Unifi-Poller that could in theory already be used to poll its status? (last run metrics or something?)
