### ISSUE TITLE
AP data is showing radio_protocol of "an" ???

### ISSUE THREAD

**Issue by fabriziorizzo** [unifi-poller/unifi-poller#275]
Now that I have unif-poller pulling data from my controller into InfluxDB and reporting via Grafana, I'm seeing data reporting that there are client connections to my access points with a protocol/channel combination that doesn't seem to make sense.

I see connections with a protocol value of "ac" on high channels corresponding to my 5ghz radio configurations (e.g. channel 149), and I see connections with protocol values of "ng" on channels corresponding to my 2.4gHz radio configurations. These make sense.
However, I am also seeing connection data with a protocol value of "an" also on the 5gHz channel numbers. Does this make any sense? 802.11n is a 2.4gHz specification, and 802.11a can do both 2.4 and 5.2gHz... but never heard of anything specified as "802.11an". Is there such a thing as 802.11an???
Is this an Ubiquity thing or perhaps something that UniFi-Poller is fudging?

**Comment by zunder1990** [comment]
I am not an authoritative source but I would say that na is for 802.11 n client that connect on 5ghz. When 802.11 came out it was 5ghz only.

**Comment by davidnewhall** [comment]
The data comes directly from the controller. Since UniFi doesn't document their API we can only make guesses as to what it is. I have the same values on my controller.

**Comment by davidnewhall** [comment]
linking. https://www.reddit.com/r/Ubiquiti/comments/jtp6qd/unifipoller_3rd_party_is_showing_a_strange/
