### ISSUE TITLE
Any instructions for Rasbery Pi 4 user with Home Assistant?

### ISSUE THREAD

**Issue by NFCES** [unifi-poller/unifi-poller#276]
New comer here. Any instructions for Rasbery Pi 4 user with Home Assistant? Not sure what I should be following here. Please advise

**Comment by davidnewhall** [comment]
I've never personally used a Pi, but we have many users that have. One of them wrote this guide:
https://nerdygeek.uk/2020/06/18/unifi-poller-an-easy-step-by-step-guide/

Hope it helps! You can find him, and others in our Discord.

**Comment by davidnewhall** [comment]
That get ya going?

**Comment by davidnewhall** [comment]
Please let me know if I can help further!
