### ISSUE TITLE
Annotations

### ISSUE THREAD

**Issue by estcado** [unifi-poller/unifi-poller#278]
Hello

I don't understand how to configure the dasboard.

I see in the Annotations a configuration activated but I cannot find how to do it.

I am using Grafana, with a data source, influxdb, which works for the rest.

how to set this dashboard.

thank you

**Comment by davidnewhall** [comment]
Which dashboard are you configuring and what's not working?

**Comment by estcado** [comment]
Hello
here are the dashboards
![image](https://user-images.githubusercontent.com/6891474/99950615-14ea6680-2d7d-11eb-9958-224ed0c41bda.png)
![image](https://user-images.githubusercontent.com/6891474/99950713-3ea38d80-2d7d-11eb-8667-5bdd6a61603a.png)
thanks

**Comment by davidnewhall** [comment]
I'm not understanding the problem you're having here. Can you elaborate? My dashboards do not natively use any annotations, that's a Grafana feature.

**Comment by estcado** [comment]
Ok I can't use the right dashboard for my need.

I have switches that I want supervised, I thought that would do.

but in the dashboard nothing goes back.
![image](https://user-images.githubusercontent.com/6891474/99951708-cfc73400-2d7e-11eb-8820-85c08e41d1e2.png)

**Comment by davidnewhall** [comment]
Is your problem that devices are missing? All devices? Some devices? Do your sites work? Do other dashboards work? Please provide more data.

**Comment by davidnewhall** [comment]
Make sure you're using InfluxDB 1.7 or 1.8.

**Comment by estcado** [comment]
I'm new to all of this, for sites I don't know.

I use "Eyes of netoyorks", which integrates grafana, I add my switches in nagios.

for the Influx version


![image](https://user-images.githubusercontent.com/6891474/100225733-f9b75c80-2f1e-11eb-99a2-cd58143ae8ca.png)

**Comment by davidnewhall** [comment]
That screenshot is from Grafana, and does not show your Influx version.

Have you followed a guide to get to where you are now?

**Comment by davidnewhall** [comment]
Recommend following these:
https://github.com/unifi-poller/unifi-poller/wiki/Installation
https://github.com/unifi-poller/unifi-poller/wiki/Grafana
