### ISSUE TITLE
Missing Data from Controller

### ISSUE THREAD

**Issue by lslamp** [unifi-poller/unifi-poller#279]
Firstly, What a Great Tool. Thanks.
It seems that I might be missing something in the config.
I have installed the unifi-poller and that seems to be working and delivering data.
below is a small extract from the log file.

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
Nov 25 01:51:14 kodi systemd[1]: unifi-poller.service: Succeeded.
Nov 25 01:51:14 kodi systemd[1]: Stopped unifi-poller - Polls a UniFi controller, exports metrics to InfluxDB and Prometheus.
Nov 25 01:51:14 kodi systemd[1]: Started unifi-poller - Polls a UniFi controller, exports metrics to InfluxDB and Prometheus.
Nov 25 01:51:14 kodi unifi-poller[105555]: 2020/11/25 01:51:14 [INFO] Loading Configuration File: /etc/unifi-poller/up.conf
Nov 25 01:51:14 kodi unifi-poller[105555]: 2020/11/25 01:51:14 [INFO] UniFi Poller v2.0.1-787 Starting Up! PID: 105555
Nov 25 01:51:15 kodi unifi-poller[105555]: 2020/11/25 01:51:15 [INFO] Found 1 site(s) on controller https://192.168.1.99:8443: default (ICAN)
Nov 25 01:51:15 kodi unifi-poller[105555]: 2020/11/25 01:51:15 [INFO] Configured UniFi Controller 1:
Nov 25 01:51:15 kodi unifi-poller[105555]: 2020/11/25 01:51:15 [INFO]    => URL: https://192.168.1.99:8443
Nov 25 01:51:15 kodi unifi-poller[105555]: 2020/11/25 01:51:15 [INFO]    => Version: 6.0.36
Nov 25 01:51:15 kodi unifi-poller[105555]: 2020/11/25 01:51:15 [INFO]    => Username: lawrence@e2snail.com (has password: true)
Nov 25 01:51:15 kodi unifi-poller[105555]: 2020/11/25 01:51:15 [INFO]    => Hash PII: false
Nov 25 01:51:15 kodi unifi-poller[105555]: 2020/11/25 01:51:15 [INFO]    => Verify SSL: false
Nov 25 01:51:15 kodi unifi-poller[105555]: 2020/11/25 01:51:15 [INFO]    => Save DPI: false
Nov 25 01:51:15 kodi unifi-poller[105555]: 2020/11/25 01:51:15 [INFO]    => Save IDS: false
Nov 25 01:51:15 kodi unifi-poller[105555]: 2020/11/25 01:51:15 [INFO]    => Save Sites: true
Nov 25 01:51:15 kodi unifi-poller[105555]: 2020/11/25 01:51:15 [INFO] Prometheus config missing (or disabled), Prometheus HTTP listener disabled!
Nov 25 01:51:15 kodi unifi-poller[105555]: 2020/11/25 01:51:15 [INFO] Everything checks out! Poller started, InfluxDB interval: 30s
Nov 25 01:51:45 kodi unifi-poller[105555]: 2020/11/25 01:51:45 [INFO] UniFi Metrics Recorded. Sites: 1, Clients: 12, UAP: 3, USG/UDM: 1, USW: 7, IDS Events: 0, Points: 65, Fields: 1733, Errs: 0, Elapsed: 27ms
Nov 25 01:52:15 kodi unifi-poller[105555]: 2020/11/25 01:52:15 [INFO] UniFi Metrics Recorded. Sites: 1, Clients: 12, UAP: 3, USG/UDM: 1, USW: 7, IDS Events: 0, Points: 65, Fields: 1733, Errs: 0, Elapsed: 17ms
Nov 25 01:52:45 kodi unifi-poller[105555]: 2020/11/25 01:52:45 [INFO] UniFi Metrics Recorded. Sites: 1, Clients: 12, UAP: 3, USG/UDM: 1, USW: 7, IDS Events: 0, Points: 65, Fields: 1733, Errs: 0, Elapsed: 20ms
Nov 25 01:53:15 kodi unifi-poller[105555]: 2020/11/25 01:53:15 [INFO] UniFi Metrics Recorded. Sites: 1, Clients: 12, UAP: 3, USG/UDM: 1, USW: 7, IDS Events: 0, Points: 65, Fields: 1733, Errs: 0, Elapsed: 18ms
Nov 25 01:53:45 kodi unifi-poller[105555]: 2020/11/25 01:53:45 [INFO] UniFi Metrics Recorded. Sites: 1, Clients: 12, UAP: 3, USG/UDM: 1, USW: 7, IDS Events: 0, Points: 65, Fields: 1733, Errs: 0, Elapsed: 18ms
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

When I look at the config within Grafana I am sure that I have not filled in all the necessary data. Below is a screenshot of what I see.

![image](https://user-images.githubusercontent.com/6013759/100168695-09548800-2ec2-11eb-9bd8-53f6bc0a7c7f.png)
The only field that is populated is the following.
![image](https://user-images.githubusercontent.com/6013759/100168749-28ebb080-2ec2-11eb-81d8-62d7f7f2435a.png)

Personally I think but I am not sure, but I think that I have not configured the following correctly.

![image](https://user-images.githubusercontent.com/6013759/100168824-4ae53300-2ec2-11eb-887d-23d55629e160.png)

![image](https://user-images.githubusercontent.com/6013759/100168876-66503e00-2ec2-11eb-8e32-988645bf7bf5.png)

![image](https://user-images.githubusercontent.com/6013759/100168906-76681d80-2ec2-11eb-8652-af7cbf416db9.png)

![image](https://user-images.githubusercontent.com/6013759/100168923-83850c80-2ec2-11eb-9e99-84f78169799d.png)

I hope that you can see or understand what it is that I am doing incorrectly.
Thanks
Lawrence

**Comment by davidnewhall** [comment]
You probably need to upgrade Influx. What version are you running? Needs at least 1.7.

**Comment by lslamp** [comment]
David,
Thanks for your feedback. I tried to do an upgrade which failed and I had no clue why, so I removed influxdb 1.6 and installed 2.0 (thinking that the newer is the way to go), but it has caused more confusion than ever.
It seems that influxdb 2.0 has it's own URL apart from Grafana. Now if I try to DataSource within your template, I get a Bar Request error. I have no clue where to turn or what to do.
Do you have any ideas. Should I downgrade to influxdb 1.8?
Thanks
Lawrence

**Comment by davidnewhall** [comment]
You'll need 1.7 or 1.8, yes. 2.0 is all different and this doesn't work with that version [yet]. 1.6 is too old and doesn't work with the newer Grafana.

**Comment by lslamp** [comment]
I am now back to the same spot I was in earlier with v1.6. The screen shots are the same. Only I have now installed 1.8
Tested my data source and all seems good but still not data ?

What am I doing wrong?
Lawrence

**Comment by davidnewhall** [comment]
I'm not sure. It sounds like you're still on 1.6.
Make sure it's 1.8. Use cur, like this: (fix the IP)
```
$ curl -sL -I 127.0.0.1:8086/ping
HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: 698cd18a-2f02-11eb-84d6-0242ac17001e
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.8.3
X-Request-Id: 698cd18a-2f02-11eb-84d6-0242ac17001e
Date: Wed, 25 Nov 2020 09:41:37 GMT
```

**Comment by lslamp** [comment]
![image](https://user-images.githubusercontent.com/6013759/100212029-25314b80-2f0d-11eb-858b-7c28da5c32a2.png)

I have also taken a look, there is data in the database.
![image](https://user-images.githubusercontent.com/6013759/100212450-a1c42a00-2f0d-11eb-9204-7bd751b81d8a.png)

There has to be something in grafana that I am not doing or missing.

**Comment by lslamp** [comment]
this from the dashboard
![image](https://user-images.githubusercontent.com/6013759/100212806-1a2aeb00-2f0e-11eb-9ed8-d8497f9b1c17.png)


this from the CLI terminal
![image](https://user-images.githubusercontent.com/6013759/100212776-0ed7bf80-2f0e-11eb-8405-901bf869fbec.png)

Seems that only the first variable below gives results. the lower two give no data
![image](https://user-images.githubusercontent.com/6013759/100213286-b7861f00-2f0e-11eb-971b-d3cb14a0a469.png)

**Comment by lslamp** [comment]
![image](https://user-images.githubusercontent.com/6013759/100213628-23688780-2f0f-11eb-8c78-985fb741ffc3.png)

**Comment by lslamp** [comment]
is there a query or a way to see what values are listed under the key tag?
I find it strange that there is data and it is not being presented.
I ran the following command on the CLI 
select * from usg

![image](https://user-images.githubusercontent.com/6013759/100218821-83fac300-2f15-11eb-845b-b5c8d0bcf75a.png)

So I really think that I have something mis-configured with regardsthe variables and connection to the DB

**Comment by davidnewhall** [comment]
Why are your variables named `kodi` and `icanunifi`? These are not part of dashboards I created. This seems to be a data source or variable-specific issue with the dashboards or Grafana. The data is indeed making it into influxdb, so influxdb and poller seem good at this point. Focus on Grafana settings. Try importing my dashboards again. 

When you query influx you can't use grafana variables. Try:
```
show tag values from "usg" with key="site_name"
show tag values from "usg" with key="name"
```

**Comment by davidnewhall** [comment]
Glad it's working out. Please let me know if I can help any more!
