### ISSUE TITLE
Unifi Gateway data

### ISSUE THREAD

**Issue by lslamp** [unifi-poller/unifi-poller#280]
David,

Please let me start with the fact that this is an INCREDIBLE monitoring tool. Very Impressive.
I am not sure that this is an issue. I have now had time to look through what you have done. There is a huge set of data that is presented and there are loads of options to filter through it and view individual devices and ports. What I seem to not find is the data on the Unifi Gateway at all. This might be my complete misunderstanding of the data set.
Looking at the dashboard I can see all of my APs and all my switches. within my network, but I do not see the gateway device at all.

below all switches
![image](https://user-images.githubusercontent.com/6013759/100277452-766c2a00-2f63-11eb-81f4-4c8c1ed69b2a.png)

below all Devices
![image](https://user-images.githubusercontent.com/6013759/100278679-91d83480-2f65-11eb-950a-06c6e71b2a2c.png)

all switches
![image](https://user-images.githubusercontent.com/6013759/100278848-c6e48700-2f65-11eb-86a0-27955f641442.png)

all APs
![image](https://user-images.githubusercontent.com/6013759/100278740-a74d5e80-2f65-11eb-9393-56002c1295ca.png)

Looking at the list of devices, you can see UAP, UDM and USW
Can I assume that the UDM device is the gateway itself. Does that in turn mean that there could be something not configured and that is the reason when the UDM device is selected there is no data present?

Thanks again for your great support.
Regards
Lawrence

**Comment by davidnewhall** [comment]
> Looking at the dashboard 

Which dashboard? There are 6. Does your gateway show up on the USG dashboard? Do you have a UDM or a USG on your network? Does your controller have more than 1 site; how many?

> Can I assume that the UDM device is the gateway itself. 

A UDM is a gateway and will be considered as such.

> Does that in turn mean that there could be something not configured and that is the reason when the UDM device is selected there is no data present?

What data is not present that you're expecting, and which dashboard/panels are you looking at?

-- -

Your screenshot don't provide enough data, take bigger ones that show the variables, panels and dashboard titles.

**Comment by lslamp** [comment]
I have a USG ... with only 1 site ICAN

You say 6 dashboards. haha then I am missing some because I only see one. How can I see the rest ?

LAwrence

**Comment by lslamp** [comment]
this is the view of the manage dashboards 

![image](https://user-images.githubusercontent.com/6013759/100289238-ba1d5e80-2f78-11eb-9a7e-3d60d517fa4f.png)

**Comment by lslamp** [comment]
David,

I am an idiot. I just downloaded the USG dashboard and that shows great data as well

Sorry.
Lawrence

**Comment by lslamp** [comment]
I have now added the following template ... UAP for Influxdb but I am seeing that I am miising a pluging.

![image](https://user-images.githubusercontent.com/6013759/100290220-1f724f00-2f7b-11eb-826e-ed4ae10f30f2.png)

What pluging should I install to view the red piecharts

**Comment by lslamp** [comment]
Ignore the last I found it.
Lawrence

**Comment by davidnewhall** [comment]
The installation process is documented in the wiki. Recommend reading these two articles:
https://github.com/unifi-poller/unifi-poller/wiki/Installation
https://github.com/unifi-poller/unifi-poller/wiki/Grafana

**Comment by lslamp** [comment]
David,
Those are the instructions that I have followed. This is how I have managed to get this far, that as well as a load of help and support from you .

Thanks again.
Lawrence

**Comment by davidnewhall** [comment]
Great, those articles should cover most of these issues. Were you able to get DPI working? Anything else you need assistance with?
