### ISSUE TITLE
Docker image: HTTP error 500

### ISSUE THREAD

**Issue by simonszu** [unifi-poller/unifi-poller#281]
Hi, 
i have the following issue when running unifi-poller in Docker:
```
2020/11/27 18:27:42 [ERROR] metric fetch failed: unifi.GetSiteDPI(https://192.168.1.244:8443): https://192.168.1.244:8443/api/s/default/stat/sitedpi: 500 : invalid status code from server
2020/11/27 18:27:42 [INFO] UniFi Measurements Exported. Site: 0, Client: 0, UAP: 0, USG/UDM: 0, USW: 0, Descs: 0, Metrics: 0, Errs: 1, 0s: 0, Reqs/Total: 2.0667s / 2.0667s
```
However, the API is accessible from outside docker, and from other containers in the same network. Also, it has worked in the past. So now I'd like to debug from inside the unifi-poller container, but apparently there is no shell or anything installed. I'd like to know how to debug it.

**Comment by simonszu** [comment]
I have moved unifi-poller to a container using host network, no success yet. Whats even more strange:
```
2020/11/27 18:59:51 [INFO] Loading Configuration File: /etc/unifi-poller/up.conf
2020/11/27 18:59:51 [INFO] UniFi Poller v2.0.1-787 Starting Up! PID: 1
2020/11/27 18:59:53 [INFO] Found 1 site(s) on controller https://192.168.1.244:8443: default (Home)
2020/11/27 18:59:53 [INFO] Configured UniFi Controller 1:
2020/11/27 18:59:53 [INFO]    => URL: https://192.168.1.244:8443
2020/11/27 18:59:53 [INFO]    => Version: 6.0.28
2020/11/27 18:59:53 [INFO]    => Username: unifipoller (has password: true)
2020/11/27 18:59:53 [INFO]    => Hash PII: false
2020/11/27 18:59:53 [INFO]    => Verify SSL: false
2020/11/27 18:59:53 [INFO]    => Save DPI: true
2020/11/27 18:59:53 [INFO]    => Save IDS: false
2020/11/27 18:59:53 [INFO]    => Save Sites: true
2020/11/27 18:59:53 [INFO] Prometheus exported at https://0.0.0.0:9130/ - namespace: unifipoller
2020/11/27 18:59:53 [INFO] InfluxDB config missing (or disabled), InfluxDB output disabled!
2020/11/27 18:59:55 [INFO] Re-authenticating to UniFi Controller: https://192.168.1.244:8443
2020/11/27 18:59:57 [ERROR] metric fetch failed: unifi.GetSiteDPI(https://192.168.1.244:8443): https://192.168.1.244:8443/api/s/default/stat/sitedpi: 500 : invalid status code from server
2020/11/27 18:59:57 [INFO] UniFi Measurements Exported. Site: 0, Client: 0, UAP: 0, USG/UDM: 0, USW: 0, Descs: 0, Metrics: 0, Errs: 1, 0s: 0, Reqs/Total: 2.2682s / 2.2683s
2020/11/27 19:00:10 [INFO] Re-authenticating to UniFi Controller: https://192.168.1.244:8443
2020/11/27 19:00:12 [ERROR] metric fetch failed: unifi.GetSiteDPI(https://192.168.1.244:8443): https://192.168.1.244:8443/api/s/default/stat/sitedpi: 500 : invalid status code from server
2020/11/27 19:00:12 [INFO] UniFi Measurements Exported. Site: 0, Client: 0, UAP: 0, USG/UDM: 0, USW: 0, Descs: 0, Metrics: 0, Errs: 1, 0s: 0, Reqs/Total: 2.2625s / 2.2626s
2020/11/27 19:00:25 [INFO] Re-authenticating to UniFi Controller: https://192.168.1.244:8443
2020/11/27 19:00:27 [ERROR] metric fetch failed: unifi.GetSiteDPI(https://192.168.1.244:8443): https://192.168.1.244:8443/api/s/default/stat/sitedpi: 500 : invalid status code from server
2020/11/27 19:00:27 [INFO] UniFi Measurements Exported. Site: 0, Client: 0, UAP: 0, USG/UDM: 0, USW: 0, Descs: 0, Metrics: 0, Errs: 1, 0s: 0, Reqs/Total: 2.2363s / 2.2363s
```
So, unifi-poller is able to connect to the controller at least once, but it gets a 500 afterwards. 
I have disabled DPI, and the error is gone. But why should the API not accept DPI requests when it did before?

**Comment by davidnewhall** [comment]
This is likely an issue with the account not having access.

Log into your controller with the same username and password you have in the Poller config. Can you access the same data?

**Comment by simonszu** [comment]
In the Unifi controller i can see in the statistics tab which hosts my clients are accessing, so i assume the account is able to access DPI data. The permissions which the unifipoller profile on the controller has are: 
- Role: Read only
- Alerts: Everything disabled
- Site permissions: Everything disabled
- Global permissions: Everything enabled

I assumed that are the most permissive Read Only settings the controller would give me. And, yes, unifi-poller worked fine with these settings when i initially deployed it, even with SAVE_DPI enabled. I think a firmware update somehow broke DPI access, since that's the only thing i changed on the controller since then. 

UPDATE: Yep, most certainly a firmware update. During debugging i checked for newer firmware on my CloudKey, and it suggested to install Controller version 6.36 over 6.28. Afterwards, the errors are gone.

**Comment by davidnewhall** [comment]
_woo!_
