### ISSUE TITLE
Unifi Network Controller 6 support?

### ISSUE THREAD

**Issue by ggear** [unifi-poller/unifi-poller#284]
Hi,

Not an issue as such, but I am interested if Network Controller 6 will work with this great codebase?

I have seen some anecdotal evidence on the forums that this does indeed work but note that this is not listed as a tested environment.

Thanks,
Graham

**Comment by davidnewhall** [comment]
Sounds shiny and new. I've never used it. Please let me know if it works for you. :)

**Comment by ggear** [comment]
OK, I will report back once I upgrade, thanks @davidnewhall

**Comment by davidnewhall** [comment]
Standing by for your report!

**Comment by Ornias1993** [comment]
Because there hasn't been a reply yet:
I can confirm this works on my end with a UDM-PRO running controller version 6

**Comment by davidnewhall** [comment]
Thank you for confirming!
