### ISSUE TITLE
Speedtest not working

### ISSUE THREAD

**Issue by genexxa** [unifi-poller/unifi-poller#286]
Hi guys,

both speedtest in the USG dashboard have stopped working this morning.  They are now showing 0 Mpbs.  All the other fields are working fine.  Anything I can do to troubleshoot thses 2 fields?

Thanks

**Comment by davidnewhall** [comment]
Poller pulls this data from your controller and stores it in your database. If the numbers are 0, that means the controller is providing zeros. You can verify this by checking the API output from the controller.

**Comment by genexxa** [comment]
> 
> 
> Poller pulls this data from your controller and stores it in your database. If the numbers are 0, that means the controller is providing zeros. You can verify this by checking the API output from the controller.

Thanks for your help.  I'll first try to reboot the device.  Maybe I'll try to check the API output after.  I don't have any experience doing that, any easy way of checking?

**Comment by davidnewhall** [comment]
Poller has a build-in tool to dump api paths from the controller. I believe the speed test data is in the site list, so run poller like this:
```
unify-poller -j "other /api/stat/sites" -c /path/to/up.conf
``` 
The quotes are needed to parse the command correctly. You may also need to pass `-c /path/to/up.conf` to give it a config. All it needs is the url and user/pass so it can auth and grab the api data.

**Comment by davidnewhall** [comment]
Were you able to find the api data?

**Comment by davidnewhall** [comment]
Please let me know if I can provide additional assistance.
