### ISSUE TITLE
Add info about `jool-exporter` to jool Documentation

### ISSUE THREAD

**Issue by cooperlees** [unifi-poller/unifi-poller#287]
Hi,

I wanted to see over time the trends / usage patterns for my home network's jool usage. To do this I've written a simple [prometheus exporter] that wraps the `jool stats display --csv --explain` command that allows prometheus to come and scrape the data storing the key value pairs into it's time series database.

My Example home Dashboard:
<img width="1769" alt="grafana_jool_example" src="https://user-images.githubusercontent.com/3005596/102745874-dd39f480-4311-11eb-81e7-70d2dfc5c7cc.png">

I've open sourced this to GitHub + pushed to PyPI.
- https://github.com/cooperlees/jool-exporter
- https://pypi.org/project/jool-exporter/

Would you be open to me adding this into your documentation somewhere? If so, where? Happy to do the PR.

Once again, thanks for jool!

**Comment by cooperlees** [comment]
Sorry, Wrong repo. To much open!

**Comment by davidnewhall** [comment]
No worries!
