### ISSUE TITLE
Why is chronograf in docker compose file ?

### ISSUE THREAD

**Issue by tablatronix** [unifi-poller/unifi-poller#289]
I see absolutely no mention of what this is for or why its in this config exmaple

**Comment by davidnewhall** [comment]
It's an example compose file. You can add or remove the pieces that work in your environment. I use chronograf to browse Prometheus.

**Comment by tablatronix** [comment]
ok that makes sense, threw me for a loop

**Comment by davidnewhall** [comment]
Sorry about that. The file was mostly contributed by others. I don't actually use it myself at all. I run everything on unRAID. As -is, it's just ask example of apps that work in this ecosystem. If you don't need Chronograf, just remove those pieces. :) Hope it's working out for you! Thanks for stopping by.

**Comment by tablatronix** [comment]
Can I ask or create a new issue, how do i change the grafana datasource? I changed the variables, but it doesn't seem to be affecting the panel datasources

**Comment by davidnewhall** [comment]
The only way to change the data source is to edit the panels. It's probably easier to just import them again and overwrite them. When you do that you can pick the data source and apply it to all panels.

**Comment by tablatronix** [comment]
I have an alternate datasource `influxdb_unifi` not influxdb

**Comment by tablatronix** [comment]
It works!, thanks you so much , this is awesome
