### ISSUE TITLE
Grafana: Install required plugins automatically?

### ISSUE THREAD

**Issue by tablatronix** [unifi-poller/unifi-poller#290]
Not sure if there is a built in way to auto install grafana plugins, I had to add
pi chart and discreet

`grafana-cli plugins install grafana-piechart-panel`

`grafana-cli plugins install natel-discrete-panel`

Might be worth adding to docs if it has to be done manually, I did not see another way.

**Comment by davidnewhall** [comment]
Seems to be in the docs. https://github.com/unifi-poller/unifi-poller/wiki/Grafana#Plugins

**Comment by tablatronix** [comment]
Geez I skipped over that whole part of the docs somehow
