### ISSUE TITLE
Error in query: "...derivative cannot be used with other fields"

### ISSUE THREAD

**Issue by ryanmboyce** [unifi-poller/unifi-poller#291]
In query inspector I'm getting the following error on several of my graphs

`Object
message:"InfluxDB Error: error parsing query: derivative cannot be used with other fields"`

Running UDM Pro versions
UI: 6.0.43.0
Backend: 6.0.43
Build: atag_6.0.43_14348

Query:
![image](https://user-images.githubusercontent.com/28747183/103178298-71d2b400-4836-11eb-98a3-6b2ab21103b3.png)

Anyway to fix?

**Comment by davidnewhall** [comment]
What version of Grafana? Influx?

Is the problem only in the query inspector? Is there "no problem" if you don't look at query inspector? Do the panels and graphs render OK? Does it affect all 6 dashboards? Does removing `sum()` (in your screenshot) resolve it? Does it happen after a fresh dashboard import?

**Comment by ryanmboyce** [comment]
Versions:
`# grafana-server -v
Version 7.3.6 (commit: ea06633c34, branch: HEAD)`
`# influx --version
InfluxDB shell 0.10.0`
My graphs are empty when this error occurs:
![image](https://user-images.githubusercontent.com/28747183/103181314-b40aee00-4854-11eb-97bb-e2b74c3a73d8.png)

**Comment by davidnewhall** [comment]
Does it always occur? Intermittent? To get the influxDB version, use a command like this:
```
curl -sL -I localhost:8086/ping
```
What you provided is the CLI version.

**Comment by ryanmboyce** [comment]
I can remove the **_non_negative_derivitave_** from the query and it displays results however its not grouped by time:

![image](https://user-images.githubusercontent.com/28747183/103181345-f16f7b80-4854-11eb-8ce0-228065257b7e.png)

**Comment by davidnewhall** [comment]
I suspect upgrading InfluxDB to 1.8.x will resolve this.

**Comment by davidnewhall** [comment]
Please let me know if I can provide additional assistance.
