### ISSUE TITLE
Docker Image Can Not Connect To InfluxDB

### ISSUE THREAD

**Issue by ThePieMonster** [unifi-poller/unifi-poller#292]
The Docker image is unable to connect to the InfluxDB database per the error below. My Grafana instance can connect to the same database in question just fine. 

`2020/12/31 06:31:48 [ERROR] influxdb.Write(points): Post "http://localhost:8086/write?consistency=&db=unifi&precision=ns&rp=": dial tcp 127.0.0.1:8086: connect: connection refused`

**Comment by davidnewhall** [comment]
Switch `localhost` with the IP of your influxdb.

**Comment by ThePieMonster** [comment]
Ah, internal IP is needed instead of localhost or 127.0.0.1 even when Docker is running on the same machine as InfluxDB. Thanks.

**Comment by davidnewhall** [comment]
I put all my containers on a custom bridge network. Then you can use DNS and refer to them by container name.
