### ISSUE TITLE
Help, not really a issue...

### ISSUE THREAD

**Issue by rechena** [unifi-poller/unifi-poller#294]
HI, sorry, not sure if the right place, but I have this tool running and I think its amazing. Recently I tried to pull the data from influx into my Home Assistant tool so I could use the rx_bytes and the tx_bytes from my APs. But I can't seem to get the values right. If I understand correctly the data it stored in bytes on the influx side? But when I run the conversion from bytes to MB I get weird numbers. The same does not happen if I use the grafana dashboard. So maybe its my lack of knowledge or so, but I can't get the values to make sense.... 

Any idea what I might be doing wrong? Thanks for the help.

**Comment by davidnewhall** [comment]
Hard to say. Can you provide more info? Like: the influx queries, their values, the math you're performing on them, values generated and values expected.

**Comment by davidnewhall** [comment]
Please come to Discord so we can chat. Might be easier.
