### ISSUE TITLE
Need to delete old site (Help needed)

### ISSUE THREAD

**Issue by geeneo** [unifi-poller/unifi-poller#295]
Hi.

Just love this "tool"   Can someone help me please?  How do I delete on old Site?

**Comment by davidnewhall** [comment]
Delete it from what?

**Comment by davidnewhall** [comment]
Tags in influxdb and probably prometheus too, cannot be deleted. You need to nuke the entire database and start over. 
https://github.com/unifi-poller/unifi-poller/wiki/InfluxDB#influxdb
