### ISSUE TITLE
After updating Cloud Key firmware, connection fails

### ISSUE THREAD

**Issue by lmondoux** [unifi-poller/unifi-poller#297]
[ERROR] Controller 1 Auth or Connection Error, retrying: unifi controller: Get "https://192.168.99.4:8443/": dial tcp 192.168.99.4:8443: connect: connection refused

I was able to solve this by removing the port from the IP address.

**Comment by davidnewhall** [comment]
UDM is the same way. Works on default port 443. Thanks for sharing!

**Comment by lmondoux** [comment]
No problem. FYI I'm on 6.0.43 now.
