### ISSUE TITLE
unifi-poller+unifi: Add more SFP port data: input-/output-power & temperature

### ISSUE THREAD

**Issue by wetterfrosch** [unifi-poller/unifi-poller#298]
Hi & thanks for this very great tool again!
I'd like to put this wish down here, cause I already looked for this twice and haven't found anything.

It would be very great to have the details of an SFP-module, too (if these are provided). A regular Ubiquiti fibre-optic shows in the WebUI details when hovering the port in the switch overview:
![image](https://user-images.githubusercontent.com/506253/104813437-8f79b480-5809-11eb-8634-fcd475c30fb0.png)

In my opinion the order of relevance of these is:

1. Input power (dBm)
2. Output power (dBm)
3. Temperature (°C)
4. Voltage (V)
5. Current (A)

Especially monitoring of the input- and output- power values is something I like to do from time to time.

**Comment by davidnewhall** [comment]
If it's in the API it can be graphed. Show me how to get that data from the API and I'll add it. :)

**Comment by davidnewhall** [comment]
Okay seriously, if someone can run `unifi-poller -j d` it'll output the devices JSON. Show me a snippet of the SFP data. I don't have any SFPs and don't know what it looks like.

**Comment by wetterfrosch** [comment]
> Okay seriously, if someone can run `unifi-poller -j d` it'll output the devices JSON. Show me a snippet of the SFP data. I don't have any SFPs and don't know what it looks like.

Hey david & thanks for following up. I didn't know until now that it is so easy to get UniFi's API-response/dump so easily with unifi-poller. I back then was already looking forward to start a discussion with the UniFi API by myself.

There is something! Cause the dump is a little chunky, I still have no "path" to the object, but it seems: Within the array `port_table` one gets more details within a particular `port_idx` when there is a SFP present. The following comes from a US-XG, but is as well present when looking at a SFP-port of a US-48:

```
{"port_idx":1,
"media":"SFP+",
"port_poe":false,
"poe_caps":0,
"speed_caps":1048928,
"op_mode":"switch",
"portconf_id":"5fb2a24db021381ccc581b45",
"anomalies":0,
"autoneg":false,
"dot1x_mode":"unknown",
"dot1x_status":"disabled",
"enable":true,
"flowctrl_rx":false,
"flowctrl_tx":false,
"full_duplex":true,
"is_uplink":false,
"jumbo":true,
"rx_broadcast":4424949,
"rx_bytes":666246130519,
"rx_dropped":0,
"rx_errors":0,
"rx_multicast":10284465,
"rx_packets":1353097821,
"satisfaction":100,
"satisfaction_reason":0,
"sfp_compliance":"10GBase-SR",
"sfp_current":"11.004",
"sfp_found":true,
"sfp_part":"UF-MM-10G",
"sfp_rev":"",
"sfp_rxfault":false,
"sfp_rxpower":"-3.59",
"sfp_serial":"FT17101901680",
"sfp_temperature":"40.429",
"sfp_txfault":false,
"sfp_txpower":"-3.51",
"sfp_vendor":"UBNT",
"sfp_voltage":"3.281",
"speed":10000,
"stp_pathcost":0,
"stp_state":"forwarding",
"tx_broadcast":6258897,
"tx_bytes":1522391674364,
"tx_dropped":0,
"tx_errors":0,
"tx_multicast":44618615,
"tx_packets":1695799630,
"up":true,
"tx_bytes-r":141042,
"rx_bytes-r":180403,
"bytes-r":321446,
"name":"some port description",
"masked":false,
"aggregated_by":false},
```

So considering what might be important for a SFP I would categorize:

"nice to have"
- "sfp_compliance":"10GBase-SR",
- "sfp_rev":"",
- "sfp_serial":"FT17101901680",
- "sfp_vendor":"UBNT",
- "sfp_part":"UF-MM-10G",

"helpful"
- "sfp_found":true,

"kind of mandatory"
- "sfp_current":"11.004",
- "sfp_rxfault":false,
- "sfp_rxpower":"-3.59",
- "sfp_temperature":"40.429",
- "sfp_txfault":false,
- "sfp_txpower":"-3.51",
- "sfp_voltage":"3.281",

**Comment by davidnewhall** [comment]
This is very helpful, thank you so much!

**Comment by davidnewhall** [comment]
Are you using influx or prometheus?

**Comment by wetterfrosch** [comment]
By the way @davidnewhall, if I may ask: what's your "business" with this? When looking at my usage of your software, it raises within mine the question if there is some tip-box for this project?

**Comment by davidnewhall** [comment]
I just like writing software. :) No tips needed. Thanks!

**Comment by davidnewhall** [comment]
I'm pretty sure this is ready to go, but I have not released a new version yet. I added a whole pile of new features I need to spend time testing before I do that. If you know how to compile Go, you should be able to clone this repo, cd into it and type `make` to produce a binary. If you use docker, you can try `golift/unifi-poller:features`. You'll find SFP data in `usw_ports` along with the rest of your switch port data.

**Comment by wetterfrosch** [comment]
Thanks! Let's see how ambitious I am in terms of compiling Go (not thaaat much at the moment ;) ... 

> No tips needed. 

Ok, so I hope I'll find some time for polishing some Grafana-stuff! :)

**Comment by davidnewhall** [comment]
The current release incorporates this feature: https://github.com/unifi-poller/unifi-poller/releases/tag/v2.1.0

I have not updated the USW dashboards and probably won't until I have SFPs to see the data. Sorry about that, and good luck!
