### ISSUE TITLE
dashboards: Remove html break on USG text panel in USG dashboard.

### ISSUE THREAD

**Issue by flopp999** [unifi-poller/unifi-poller#299]
https://grafana.com/grafana/dashboards/10416

Remove < br > in the Panel where text is "Unifi USG"

Now I need to scroll

**Comment by davidnewhall** [comment]
Difficult to determine what the problem is.

**Comment by davidnewhall** [comment]
Font size issue? The panel is just a space filler.

**Comment by flopp999** [comment]
I wrote < br > but it was removed

**Comment by flopp999** [comment]
![image](https://user-images.githubusercontent.com/21694965/106046728-ecffe200-60e2-11eb-8590-3e67004d7952.png)

**Comment by fblgit** [comment]
I think that the poller is a great tool, and the dashboard "initially" is also ok...
but, I think that its missing one very important point... there are graphs/visualizations that can be done in grafana but that are not available in the Unifi UI... which I believe, is the real value.. to see the same graphs/metrics... their UI is much more "smooth"... lets see if got time this weekend and send a PR for an "alternative" Dashboard that doesn't kill your browser in grafana.

**Comment by davidnewhall** [comment]
My dashboards are examples. They work well for my home network. I expect engineers to create their own visualizations with the data that poller stuffs into influxdb and prometheus. My dashboards just scratch the surface, and there's considerably more that can be done. Contributions are welcome! You can even publish your to Grafana.com; include unifi-poller in the name so it's easy to find.

**Comment by davidnewhall** [comment]
Removed the br locally so when I update the dashboard it will be gone. Thanks for the report!
