### ISSUE TITLE
unifi-poller service fails

### ISSUE THREAD

**Issue by shahzy1** [unifi-poller/unifi-poller#300]
This is the result of status command on LINUX DEBIAN;
systemctl status unifi-poller

 unifi-poller.service - unifi-poller - Polls a UniFi controller, exports metric
   Loaded: loaded (/lib/systemd/system/unifi-poller.service; enabled; vendor pre
   Active: activating (auto-restart) (Result: exit-code) since Thu 2021-01-28 21
  Process: 7913 ExecStart=/usr/bin/unifi-poller $DAEMON_OPTS (code=exited, statu
 Main PID: 7913 (code=exited, status=1/FAILURE)

No data is collected so no dancing metrics in grafana dashboard.

does anybody knows what's wrong?

**Comment by davidnewhall** [comment]
Can you provide application logs and configuration information?

**Comment by shahzy1** [comment]
what's the location of these logs?

**Comment by shahzy1** [comment]
I am not using docker. I ran this command today;

journalctl -f -u unifi-poller.service

this is the output;
Feb 10 23:05:28 UCKP systemd[1]: unifi-poller.service: Failed with result 'exit-code'.
Feb 10 23:05:39 UCKP systemd[1]: unifi-poller.service: Failed with result 'exit-code'.
Feb 10 23:05:49 UCKP systemd[1]: unifi-poller.service: Failed with result 'exit-code'.
Feb 10 23:05:59 UCKP systemd[1]: unifi-poller.service: Failed with result 'exit-code'.
Feb 10 23:06:09 UCKP systemd[1]: unifi-poller.service: Failed with result 'exit-code'.
Feb 10 23:06:19 UCKP systemd[1]: unifi-poller.service: Failed with result 'exit-code'.
Feb 10 23:06:30 UCKP systemd[1]: unifi-poller.service: Failed with result 'exit-code'.
Feb 10 23:06:40 UCKP systemd[1]: unifi-poller.service: Failed with result 'exit-code'.

thanks in advance for your help

**Comment by davidnewhall** [comment]
on linux, syslog probably writes log to /var/log/syslog. https://github.com/unifi-poller/unifi-poller/wiki/Installation#linux-post-install

**Comment by davidnewhall** [comment]
Please let me know if you still need assistance. Just re-open this issue.
