### ISSUE TITLE
support: UDM Pro, WAN2 problems

### ISSUE THREAD

**Issue by thib3113** [unifi-poller/unifi-poller#301]
Hello, 

It seems I have a problem with the WAN2 . 

First, my network : 
 I have a "Freebox" ( router from my ISP "Free", with an SFP+ 10Gb/s output ) . 
 My UDM pro WAN 2 ( SFP+ ), is connected to my Freebox by SFP+ . 
 An USA is plugged on the other SFP+ port .
 
In unifi, I've inverted WAN and WAN2 ( so the wan port is a backup for the wan2, but not connected for the moment )
![image](https://user-images.githubusercontent.com/5489218/106301647-3e7dad80-6258-11eb-833d-b906999dbfb0.png)

---

Second, in grafana dashboard "USG Dashboard", the speed is "only" 1Gb/s ( I rearrange a little )
![image](https://user-images.githubusercontent.com/5489218/106301840-7e449500-6258-11eb-9ce1-1225c311a1d6.png)

When checking in influxDB (with chronograph),
![image](https://user-images.githubusercontent.com/5489218/106302058-bea41300-6258-11eb-8114-02904b246002.png)

The speed is incorrect, and the name ... I'm not sure about the name ... I found in unifi the same name as "mac address", but the Freebox know another mac address ... ( so, I think if unifi say that, it's normal ) .

So, I try the cli : `unifi-poller  -j devices `

And, I found this : 
```
        {
          "port_idx": 10,
          "media": "SFP+",
          "port_poe": false,
          "speed_caps": 1048864,
          "op_mode": "switch",
          "portconf_id": "6001f8ab3fd98c05e9465fa8",
          "autoneg": true,
          "enable": true,
          "flowctrl_rx": false,
          "flowctrl_tx": false,
          "full_duplex": true,
          "is_uplink": true,
          "mac": "f4:92:bf:72:51:31",
          "mac_table": [
            {
              "age": 930503,
              "authorized": true,
              "hostname": "?",
              "ip": "192.168.1.254",
              "lastReachable": 10,
              "mac": "34:27:92:60:d5:9c",
              "rx_bytes": 2876145708,
              "rx_packets": 2887553,
              "tx_bytes": 427321719,
              "tx_packets": 3223629
            }
          ],
          "name": "Port 10",
          "num_port": 1,
          "rx_broadcast": 0,
          "rx_bytes": 3624118616991,
          "rx_dropped": 0,
          "rx_errors": 0,
          "rx_multicast": 0,
          "rx_packets": 2480319350,
          "rx_rate": 2408360,
          "speed": 10000,
          "tx_broadcast": 0,
          "tx_bytes": 198569386565,
          "tx_dropped": 0,
          "tx_errors": 0,
          "tx_multicast": 0,
          "tx_packets": 862249795,
          "tx_rate": 4372295,
          "type": "ethernet",
          "up": true,
          "ifname": "eth9",
          "ip": "192.168.1.30",
          "netmask": "255.255.255.0",
          "tx_bytes-r": 0,
          "rx_bytes-r": 0,
          "bytes-r": 0,
          "network_name": "wan2",
          "masked": false,
          "aggregated_by": false
        }
```
 The mac, is the same on the Freebox, but the ifname is "eth9" (strange ?) . 
 
 I read this : https://github.com/unifi-poller/unifi-poller/issues/40 , and I didn't found a thing called "wan" in the json in UDM part ...
 I have "wan2" and "wan1" . 
 ```
 
      "wan2": {
        "max_speed": 1000,
        "type": "ethernet",
        "autoneg": true,
        "enable": true,
        "flowctrl_rx": false,
        "flowctrl_tx": false,
        "full_duplex": false,
        "is_uplink": false,
        "mac": "f4:92:bf:72:51:30",
        "media": "GE",
        "name": "eth8",
        "num_port": 1,
        "port_idx": 9,
        "port_poe": false,
        "rx_broadcast": 0,
        "rx_bytes": 0,
        "rx_dropped": 0,
        "rx_errors": 0,
        "rx_multicast": 0,
        "rx_packets": 0,
        "speed": 10,
        "speed_caps": 1048623,
        "tx_broadcast": 0,
        "tx_bytes": 644,
        "tx_dropped": 0,
        "tx_errors": 0,
        "tx_multicast": 0,
        "tx_packets": 6,
        "tx_rate": 0,
        "up": false,
        "ifname": "eth8",
        "tx_bytes-r": 0,
        "rx_bytes-r": 0,
        "bytes-r": 0
      },
      "wan1": {
        "max_speed": 1000,
        "type": "ethernet",
        "autoneg": true,
        "enable": true,
        "flowctrl_rx": false,
        "flowctrl_tx": false,
        "full_duplex": true,
        "is_uplink": true,
        "mac": "f4:92:bf:72:51:31",
        "mac_table": [
          {
            "age": 930503,
            "authorized": true,
            "hostname": "?",
            "ip": "192.168.1.254",
            "lastReachable": 10,
            "mac": "34:27:92:60:d5:9c",
            "rx_bytes": 2876145708,
            "rx_packets": 2887553,
            "tx_bytes": 427321719,
            "tx_packets": 3223629
          }
        ],
        "media": "SFP+",
        "name": "eth9",
        "num_port": 1,
        "port_idx": 10,
        "port_poe": false,
        "rx_broadcast": 0,
        "rx_bytes": 3624118616991,
        "rx_dropped": 0,
        "rx_errors": 0,
        "rx_multicast": 0,
        "rx_packets": 2480319350,
        "rx_rate": 2408360,
        "speed": 10000,
        "speed_caps": 1048864,
        "tx_broadcast": 0,
        "tx_bytes": 198569386565,
        "tx_dropped": 0,
        "tx_errors": 0,
        "tx_multicast": 0,
        "tx_packets": 862249795,
        "tx_rate": 4372295,
        "up": true,
        "ifname": "eth9",
        "ip": "192.168.1.30",
        "netmask": "255.255.255.0",
        "tx_bytes-r": 0,
        "rx_bytes-r": 0,
        "bytes-r": 0
      }
 ```
 
 Here, in the wan2, the max_speed is `1000` (but the speed is `10000` ? ), I doesn't know if this json come directly from unifi, or the unifi poller already work on it ?
 
 --- 
 
because I'm not a network / unifi / grafana / influxDB expert, it's maybe a misstake from me .

Doesn't hesitate if you need more informations .

**Comment by davidnewhall** [comment]
I'll have to look into this a bit more. Thank you for your report!

**Comment by davidnewhall** [comment]
Okay, sorry it took me so long to process this. Answers below:

> The mac, is the same on the Freebox, but the ifname is "eth9" (strange ?) .

Port 10 is eth9, port 1 is eth0. The wan2 port is presumably the 10th port on a UDM, so this seems correct.

> I read this : #40 , and I didn't found a thing called "wan" in the json in UDM part ...
I have "wan2" and "wan1" .

`wan1` and `wan2` are the correct data structures, and you pasted them above. They both show what looks like correct speeds (10Mb and 10Gb). Is wan2 supposed to be 10Mb, or maybe it's just not used?

> Here, in the wan2, the max_speed is 1000 (but the speed is 10000 ? ), I doesn't know if this json come directly from unifi, or the unifi poller already work on it ?

This comes directly from the controller; that's a bug in the controller.

---

Thank you for such a detailed report and your due diligence in collecting data with `-j`. Bravo.

The speed in the panel on the USG dashboard comes from `uplink` not `wan1` nor `wan2`. It looks like this in the `-j d` (unifi devices) output:
```son
uplink": {
  "drops": 6,
  "enable": true,
  "full_duplex": true,
  "gateways": [
    "67.181.72.1"
  ],
  "ip": "67.18x.xx.120",
  "latency": 23,
  "mac": "74:83:c2:1a:35:3b",
  "name": "eth2",
  "nameservers": [
    "127.0.0.1"
  ],
  "netmask": "255.255.252.0",
  "num_port": 1,
  "rx_bytes": 453903815569,
  "rx_dropped": 26406,
  "rx_errors": 0,
  "rx_multicast": 317397,
  "rx_packets": 700603005,
  "speed": 1000,
  "speedtest_lastrun": 1615144450,
  "speedtest_ping": 29,
  "speedtest_status": "Success",
  "tx_bytes": 994435240151,
  "tx_dropped": 0,
  "tx_errors": 0,
  "tx_packets": 864595763,
  "up": true,
  "uptime": 20743,
  "xput_down": 471.06,
  "xput_up": 33.622,
  "tx_bytes-r": 1196486,
  "rx_bytes-r": 40654,
  "bytes-r": 1237141,
  "max_speed": 1000,
  "type": "wire"
}
```

Please find this. If the speed says `1000`, there's not a lot we can do to fix _that_. You can, however, change the panel in the dashboard to show the wan2 speed instead of the uplink speed.

**Comment by thib3113** [comment]
Hello, no problem for the long time :) . 
 
Just, I change some configurations, so the stats between first post, and this can change .

---

```
Port 10 is eth9, port 1 is eth0. The wan2 port is presumably the 10th port on a UDM, so this seems correct.
```
Ok, good .

```
wan1 and wan2 are the correct data structures, and you pasted them above. They both show what looks like correct speeds (10Mb and 10Gb). Is wan2 supposed to be 10Mb, or maybe it's just not used?
```
Yes is it possible it's not linked ( I will post my updated wan1 and 2 below )

---

So, here is the actual output : 

- uplink.speed = 1000
- uplink.max_speed = 1000

But, by checking key `wan*`, we can see "wan1" say `"is_uplink": true`, and "wan2" say `"is_uplink": false`, so maybe can check this ? ( but I agree it seems to be a controller bug ... )

```
{
    "wan2": {
        "max_speed": 1000,
        "type": "ethernet",
        "autoneg": true,
        "enable": true,
        "flowctrl_rx": false,
        "flowctrl_tx": false,
        "full_duplex": true,
        "is_uplink": false,
        "mac": "f4:92:bf:72:51:30",
        "mac_table": [
            {
                "age": 2431418,
                "authorized": true,
                "hostname": "?",
                "ip": "192.168.8.1",
                "lastReachable": 1,
                "mac": "24:6f:8c:95:55:30"
            }
        ],
        "media": "GE",
        "name": "eth8",
        "num_port": 1,
        "port_idx": 9,
        "port_poe": false,
        "rx_broadcast": 0,
        "rx_bytes": 116531924,
        "rx_dropped": 0,
        "rx_errors": 0,
        "rx_multicast": 0,
        "rx_packets": 2255983,
        "rx_rate": 291,
        "speed": 1000,
        "speed_caps": 1048623,
        "tx_broadcast": 0,
        "tx_bytes": 72805269,
        "tx_dropped": 0,
        "tx_errors": 0,
        "tx_multicast": 0,
        "tx_packets": 1538797,
        "tx_rate": 291,
        "up": true,
        "ifname": "eth8",
        "ip": "192.168.8.112",
        "netmask": "255.255.255.0",
        "tx_bytes-r": 0,
        "rx_bytes-r": 0,
        "bytes-r": 0,
        "dns": ["1.1.1.1", "8.8.8.8"]
    },
    "wan1": {
        "max_speed": 1000,
        "type": "ethernet",
        "autoneg": true,
        "enable": true,
        "flowctrl_rx": false,
        "flowctrl_tx": false,
        "full_duplex": true,
        "is_uplink": true,
        "mac": "f4:92:bf:xx:xx:31",
        "mac_table": [
            {
                "age": 2431423,
                "authorized": true,
                "hostname": "82-xx-xx-254.subs.proxad.net",
                "ip": "82.xx.xx.254",
                "lastReachable": 16,
                "mac": "34:27:xx:xx:d5:9d"
            }
        ],
        "media": "SFP+",
        "name": "eth9",
        "num_port": 1,
        "port_idx": 10,
        "port_poe": false,
        "rx_broadcast": 0,
        "rx_bytes": 376723381824,
        "rx_dropped": 0,
        "rx_errors": 0,
        "rx_multicast": 0,
        "rx_packets": 581797301,
        "rx_rate": 880450,
        "speed": 10000,
        "speed_caps": 1048864,
        "tx_broadcast": 0,
        "tx_bytes": 1399398944907,
        "tx_dropped": 0,
        "tx_errors": 0,
        "tx_multicast": 0,
        "tx_packets": 1045209746,
        "tx_rate": 10987169,
        "up": true,
        "ifname": "eth9",
        "ip": "82.xx.xx.40",
        "netmask": "255.255.255.0",
        "tx_bytes-r": 0,
        "rx_bytes-r": 0,
        "bytes-r": 0,
        "dns": ["1.1.1.1", "8.8.8.8"]
    },
    "uplink": {
        "drops": 12,
        "ip": "82.xx.xx.40",
        "latency": 12,
        "name": "eth9",
        "nameservers": ["1.1.1.1", "8.8.8.8"],
        "netmask": "255.255.255.0",
        "num_port": 1,
        "rx_bytes": 376839913748,
        "rx_dropped": 0,
        "rx_errors": 0,
        "rx_multicast": 0,
        "rx_packets": 584053284,
        "speedtest_lastrun": 1615161745,
        "speedtest_ping": 16,
        "speedtest_status": "Success",
        "tx_bytes": 1399471750176,
        "tx_dropped": 0,
        "tx_errors": 0,
        "tx_packets": 1046748543,
        "up": true,
        "uptime": 345020,
        "xput_down": 3268.854,
        "xput_up": 456.921,
        "port_idx": 10,
        "media": "SFP+",
        "rx_rate": 880450,
        "tx_rate": 10987169,
        "max_speed": 1000,
        "type": "wire",
        "speed": 1000,
        "full_duplex": true,
        "tx_bytes-r": 1373432,
        "rx_bytes-r": 110092,
        "bytes-r": 1483524
    }
}
```


---

```
You can, however, change the panel in the dashboard to show the wan2 speed instead of the uplink speed.
```

how ? I'm not an influx expert, but grafana does'nt seems to know a field `wan`, to autocomplete the query (replacing "uplink_speed") : 
`SELECT "uplink_speed" *1000000 FROM "usg" WHERE ("name" =~ /^$host$/ AND "site_name" =~ /^$Site$/) AND $timeFilter GROUP BY "name"`

**Comment by davidnewhall** [comment]
The data you're looking for is in another table: `usg_wan_ports`. Play with that one and you should be able to fix this. See example:
![Screen Shot 2021-03-22 at 2 15 29 AM](https://user-images.githubusercontent.com/2402929/111966784-8e3c6080-8ab4-11eb-8875-8aa9e28dad9d.png)

**Comment by thib3113** [comment]
Hello @davidnewhall , thank you .

Just some things : 
 - purpose = wan doesn't exist . I've purpose = eth8 or eth9 . ( but `wan` can be interesting for the failover )
 - speed seems to be in mb, so I need to add Math(*1000000) for gb .

**Comment by davidnewhall** [comment]
The speed is indeed in Mb. My 1Gb link shows `1000`. This is just the way the controller provides it.
![Screen Shot 2021-03-22 at 3 14 14 AM](https://user-images.githubusercontent.com/2402929/111974614-cfd10980-8abc-11eb-8843-5faf8f3b01ae.png)

**Comment by davidnewhall** [comment]
Please let me know if I can help with anything else!

**Comment by thib3113** [comment]
@davidnewhall maybe just a things . Is it normal that I doesn't have a `purpose = wan` ?

**Comment by davidnewhall** [comment]
I only have a USG4, and mine shows a purpose named `wan`, which [maps to the `name` ](https://github.com/unifi-poller/influxunifi/blob/master/usg.go#L89) on the wan port.  In the JSON you pasted above you have `eth9` in the `name` field, so this seems normal. Just what you have it named, or what UDM sets the name to, vs my USG has it set to `wan`.

**Comment by thib3113** [comment]
Oh ok . I'm not a go developper, so I doesn't understand all the code . 

but, ok, I understand, thank you :) .
