### ISSUE TITLE
Unifi Poller not working on newest update

### ISSUE THREAD

**Issue by andrewchumchal** [unifi-poller/unifi-poller#304]
UDM-Pro
Firmware | 1.8.6

After updating to 1.8.6 I had notice I am no longer getting data in my influxdb. I have attached a screenshot of the docker logs. Please let me know if you need anything else

![image](https://user-images.githubusercontent.com/8008169/106467420-3729f000-6462-11eb-96f3-ad0253868695.png)

**Comment by davidnewhall** [comment]
You blurred out the URL, so guessing. Try removing `:8443`.

**Comment by davidnewhall** [comment]
Your URL is missing `https://`.
