### ISSUE TITLE
Docker Multiple Controllers env

### ISSUE THREAD

**Issue by ozrouter** [unifi-poller/unifi-poller#307]
Hi all
This isn't recognized (in the logs its default settings), what format for docker compose?

```
      - UP_UNIFI_CONTROLLER_0_USER=${UNIFI_USER_0}
      - UP_UNIFI_CONTROLLER_0_PASS=${UNIFI_PASS_0}
      - UP_UNIFI_CONTROLLER_0_URL=${UNIFI_URL_0}
      - UP_UNIFI_CONTROLLER_1_USER=${UNIFI_USER_1}
      - UP_UNIFI_CONTROLLER_1_PASS=${UNIFI_PASS_1}
      - UP_UNIFI_CONTROLLER_1_URL=${UNIFI_URL_1}
```

**Comment by davidnewhall** [comment]
Seems right, but that's only a small portion of your config and without any output or errors I can't begin to troubleshoot.

**Comment by ozrouter** [comment]
thanks for that, I'll start from scratch and see how we go

**Comment by davidnewhall** [comment]
If you need help troubleshooting: Please provide your config(s) and any relevant logs that show the problem you're having.

**Comment by ozrouter** [comment]
User error! My Docker VM had some bugs, the config as above works fine, thanks!
