### ISSUE TITLE
docs: docker run command in wiki needs updating

### ISSUE THREAD

**Issue by pjdw** [unifi-poller/unifi-poller#309]
I tried to get poller running with prometheus in docker. 
Wiki says starting the container with:
`docker run -d -v /host/path/up.conf:/config/unifi-poller.conf golift/unifi-poller`
I would suggest adding a name and add host as network. 
`docker run --name unifipoller --net="host" -d -v /docker/dashboard/unifi-poller/up.conf:/config/unifi-poller.conf golift/unifi-poller`
Only with above command I got it running.

**Comment by davidnewhall** [comment]
I certainly do not recommend running this app in `host` networking mode. What was the problem/error with the command in the wiki?

**Comment by pjdw** [comment]
I did not got metrics running on an ip. I asked for help on discord and did a lot of experimenting. I finally got it running with host.
If there is another way, please let me know.
NB I would like very much to express my gratitude for developing poller!
- Pieter

**Comment by davidnewhall** [comment]
Expose the port. (Docker basics)

```
docker run -d --expose 9130:9130 -v /host/path/up.conf:/config/unifi-poller.conf golift/unifi-poller

```

**Comment by davidnewhall** [comment]
The wiki will soon be replaced by a documentation website with a better interface and more examples. We'll make sure this example gets in there.

**Comment by mabunixda** [comment]
@PianSom you are mixing builder expose and run expose . 
builder expose is a documentation/hint
run expose exposes the ports you are defining. 

host is always a bad idea, except some usecases

**Comment by davidnewhall** [comment]
Thank you @panks21 - we'll get this incorporated!

**Comment by davidnewhall** [comment]
I've added your docker compose example here: https://unifipoller.com/docs/install/dockercompose/#prometheus-example

Thanks again!

**Comment by cinntech** [comment]
Unless I'm missing something - you may want to update that code to:

 unifi-poller:
    restart: unless-stopped
    ports:
      - '9130:9130'
    container_name: unifi-poller
    image: golift/unifi-poller:latest
    environment:
      - UP_INFLUXDB_DISABLE: true
      - UP_POLLER_DEBUG: false
      - UP_UNIFI_DYNAMIC: false
      - UP_PROMETHEUS_HTTP_LISTEN: 0.0.0.0:9130
      - UP_PROMETHEUS_NAMESPACE: unifipoller
      - UP_UNIFI_CONTROLLER_0_PASS: unifipoller123
      - UP_UNIFI_CONTROLLER_0_SAVE_ALARMS: true
      - UP_UNIFI_CONTROLLER_0_SAVE_ANOMALIES: true
      - UP_UNIFI_CONTROLLER_0_SAVE_DPI: true
      - UP_UNIFI_CONTROLLER_0_SAVE_EVENTS: true
      - UP_UNIFI_CONTROLLER_0_SAVE_IDS: true
      - UP_UNIFI_CONTROLLER_0_SAVE_SITES: true
      - UP_UNIFI_CONTROLLER_0_URL: https://192.168.14.250:8443
      - UP_UNIFI_CONTROLLER_0_USER: unifipoller
      - UP_UNIFI_CONTROLLER_1_PASS: unifipoller123
      - UP_UNIFI_CONTROLLER_1_SAVE_ALARMS: true
      - UP_UNIFI_CONTROLLER_1_SAVE_ANOMALIES: true
      - UP_UNIFI_CONTROLLER_1_SAVE_DPI: true
      - UP_UNIFI_CONTROLLER_1_SAVE_EVENTS: true
      - UP_UNIFI_CONTROLLER_1_SAVE_IDS: true
      - UP_UNIFI_CONTROLLER_1_SAVE_SITES: true
      - UP_UNIFI_CONTROLLER_1_URL: https://192.168.1.200:8443
      - UP_UNIFI_CONTROLLER_1_USER: unifipoller

**Comment by davidnewhall** [comment]
You appear to be missing a config file. Works either way.

**Comment by madAndroid** [comment]
> https://unifipoller.com/docs/install/dockercompose/#prometheus-example

I just ran into this as well - the `environment` section needs to be an array of values, not a map
