### ISSUE TITLE
[ERROR] read /config/unifi-poller.conf: is a directory

### ISSUE THREAD

**Issue by DJ-Q** [unifi-poller/unifi-poller#311]
How do i specify the conf file to use?

I am using docker and portainer but everytime i try to start unifi-poller i get the folliwng error

[ERROR] read /config/unifi-poller.conf: is a directory

**Comment by davidnewhall** [comment]
In Docker? You don't. Either use env variables, or mount the conf @ `/config/unifi-poller.conf`

**Comment by DJ-Q** [comment]
Thank you David 

I couldnt get ENV variables to work from portainer, but worked fine from CLI - great product - thank you for your work.
