### ISSUE TITLE
[ERROR] Controller 1 Auth or Connection Error, retrying: unifi controller: Get "https://xx.xx.xx.xx:8443/": dial tcp xx.xx.xx.xx:8443: connect: connection refused

### ISSUE THREAD

**Issue by Tijn1974** [unifi-poller/unifi-poller#312]
When setting up the unif-poller according the wiki instructions in docker, I did get a error and could nog get any data. 

[ERROR] Controller 1 Auth or Connection Error, retrying: unifi controller: Get "https://xx.xx.xx.xx:8443/": dial tcp xx.xx.xx.xx:8443: connect: connection refused

I have a unifi cloudkey gen2+ running 6.0.45.0

After trying allot, I did find some solution some did post in a other forum. 
- When config the environment in the image/container, change the 
UP_UNIFI_DEFAULT_URL      https://xx.xx.xx.xx:8443 
into https://xx.xx.xx.xx 

So without port number.

Its now working great here. 

Maybe this info can be added to the wiki.

**Comment by davidnewhall** [comment]
Than you for the report! Duplicates #306 so closing it out.
