### ISSUE TITLE
UDM PRO v1.8.6 -> 1.9.0 - Bandwidth Grafana Query Broken

### ISSUE THREAD

**Issue by ThePieMonster** [unifi-poller/unifi-poller#315]
I updated the UDM Pro to version 1.9.0 today (also re-deployed the latest version of the docker image from today March 1, 2021) and the below InfluxDB query no longer produces any data.

`SELECT "rx_bytes" + "tx_bytes" FROM "usg_wan_ports" WHERE ("device_name" =~ /^$host$/ AND "site_name" =~ /^$Site$/) AND $timeFilter GROUP BY "purpose"`

![image](https://user-images.githubusercontent.com/11359134/109605627-10a3b700-7aeb-11eb-9419-6d36c261be66.png)

**Comment by davidnewhall** [comment]
Do any queries return data?

**Comment by ThePieMonster** [comment]
> Do any queries return data?

Here is a screenshot from the UniFi-Poller: USG Insights - InfluxDB dashboard @davidnewhall 

![image](https://user-images.githubusercontent.com/11359134/109606132-d1c23100-7aeb-11eb-863a-3e30153222dc.png)

**Comment by davidnewhall** [comment]
I'm pretty sure those data are counters. They probably reset when you upgraded? 
The first screenshot shows data. Is that from before the upgrade?

**Comment by ThePieMonster** [comment]
> I'm pretty sure those data are counters. They probably reset when you upgraded?
> The first screenshot shows data. Is that from before the upgrade?

Ya after the upgrade in the first screenshot there is that dropoff where there is "No Data". If I moved the time selection to just the last half hour for the first screenshot it would show "No Data".

**Comment by davidnewhall** [comment]
I'd suggesting playing with the query to see if there's any data there for those two rows. If there really isn't any, then ubiquiti may have changed the location in the API. I can't be certain right now. We'll leave your issue open in case other folks experience the same problem. Thank you for the report! 

You can make unifi-poller print out API data directly from your controller. Try this:
```
unifi-poller -c /path/to/up.conf -j device
```
That will print out the raw JSON data for all devices. You can inspect this to see if the values you're looking for present or not. I'll have to do some digging to figure out exactly where to expect those in the API.

**Comment by ThePieMonster** [comment]
Well, funny story. 

I checked the InfluxDB and looked at the past hour of data and as you can see below there is data. 
![image](https://user-images.githubusercontent.com/11359134/109610012-cd991200-7af1-11eb-9ca9-34b8888fbd19.png)

It seems that the Grafana time series graph display is pulling some data from the last day of the month or something which is why there is that dropoff effect. However the numbers that are displayed on top of the time series graph is correct.

Ultimately this seems to be a Grafana issue, but I'm unsure of what exactly is the problem. @davidnewhall I think it would be great if you added a new dashboard to the list of UniFi Poller dashboards called Overview or something that displayed the upload, download, total, and a normal line graph (for alerting) like below. Then we could have a properly supported dashboard for those of us that want to monitor just these simple metrics. 

![image](https://user-images.githubusercontent.com/11359134/109704659-7b410b00-7b5c-11eb-827a-2bedfe1733fe.png)

**Comment by davidnewhall** [comment]
Yeah I'm not real sure what happened here. I'm glad it worked out though. My setup has been down for a few weeks, and I'm trying to get is straightened out. 

I'm already maintaining 12 dashboards, and while I appreciate the idea, I think it would be better if someone else made the overview dashboard. In fact, I'd be quite happy if more folks made more dashboards for this data source. I'm committed to maintaining these 12, which should give you a strong basis to create your own overview dashboard. Anyone can upload to grafana.com, and if you include `unifi-poller` in the dashboard name it'll be included in the link I give out to folks.

Please re-open this issue, or make a new one if I can help with anything else. Thank you!

**Comment by SeekingHelp24** [comment]
Should everything be working with a UXG? I am seeing this same issue ( I know this is an old post ) but I just happened to notice the mention of a UXG and more work to be done.  Is this still the case? Everything was working without issue until the Network Application 7.5.187 update.
