### ISSUE TITLE
UDM Pro re-authentication loop, [ERROR] metric fetch failed: re-authenticating to https://x.x.x.x

### ISSUE THREAD

**Issue by mukhtarhussainbaloch** [unifi-poller/unifi-poller#316]
**I have UDM pro version: 1.8.6.**

Up-poller is constently outputing the following :
up-poller       | 2021/03/02 14:05:57 [INFO] Re-authenticating to UniFi Controller: https://x.x.x.x
up-poller       | 2021/03/02 14:05:57 [INFO] Re-authenticating to UniFi Controller: https://x.x.x.x
up-poller       | 2021/03/02 14:04:24 [INFO] UniFi Measurements Exported. Site: 0, Client: 0, UAP: 0, USG/UDM: 0, USW: 0, Descs: 0, Metrics: 0, Errs: 1, 0s: 0, Reqs/Total: 2m15.3186s / 2m15.3186s
up-poller       | 2021/03/02 14:03:46 [ERROR] metric fetch failed: unifi.GetClientsDPI(https://x.x.x.x): Post "https://x.x.x.x/proxy/network/api/s/default/stat/stadpi": EOF

**Comment by davidnewhall** [comment]
Looks like wrong URL or user/pass for your controller. Or possible a firewall causing problems. Can you curl your controller from the same system running poller?

**Comment by mukhtarhussainbaloch** [comment]
It does not look like a wrong URL or user/pass or firewall issue. Because I left it running over night and I it pulled some data and populated the Influxdb. I can see the graphs in Graphana.
and logs like
up-poller       | 2021/03/03 06:10:05 [INFO] UniFi Metrics Recorded. Sites: 1, Clients: 518, UAP: 22, USG/UDM: 1, USW: 7, IDS Events: 0, Points: 80260, Fields: 341301, Errs: 0, Elapsed: 4.143s

**and again i am getting logs**

up-poller       | 2021/03/03 06:16:09 [INFO] UniFi Metrics Recorded. Sites: 0, Clients: 0, UAP: 0, USG/UDM: 0, USW: 0, IDS Events: 0, Points: 0, Fields: 0, Errs: 1, Elapsed: 1ms
up-poller       | 2021/03/03 06:16:09 [ERROR] metric fetch failed: re-authenticating to https://x.x.x.x: unifi controller: unable to get server version: invalid character '<' looking for beginning of value
up-poller       | 2021/03/03 06:16:09 [INFO] UniFi Measurements Exported. Site: 0, Client: 0, UAP: 0, USG/UDM: 0, USW: 0, Descs: 0, Metrics: 0, Errs: 1, 0s: 0, Reqs/Total: 277.9ms / 278ms

**Comment by davidnewhall** [comment]
How often does it fail?

**Comment by mukhtarhussainbaloch** [comment]
It fails regularly. It succeeds a few times.

**Comment by davidnewhall** [comment]
Where is poller installed (linux, mac, docker, windows), and where is your UDM; same network? same switch? Are you on the same network? Does your access (in a browser) to the controller work OK? Can you curl the controller successfully (repeatedly) from the same host running poller? Can you rule out a network issue, by putting everything on the same switch? Can you try running poller from another computer? (it's multi-arch, try it from your workstation)

What version of poller are you running? Can you share your configuration file (minus sensitive info)?

**Comment by mukhtarhussainbaloch** [comment]
Poller is running in a docker on Ubuntu 20.04.2 LTS. 
UDM and poller are on the same network and switch. Access to the controller in a browser on the host running poller works fine. can curl to the controller repeatedly. 

version: "3"
services:
  influxdb:
    container_name: up_influxdb
    restart: unless-stopped
    image: influxdb:1.8
    ports:
      - '8086:8086'
    volumes:
      - /home/mukhtar/docker-unifi-poller/docker/influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=unifi
      - INFLUXDB_ADMIN_USER=unifi
      - INFLUXDB_ADMIN_PASSWORD=unifi
  grafana:
    container_name: up_grafana
    image: grafana/grafana
    restart: unless-stopped
    user: 1000:1000
    ports:
      - '3000:3000'
    volumes:
      - /home/mukhtar/docker-unifi-poller/docker/grafana:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel,natel-discrete-panel,grafana-piechart-panel
  unifi-poller:
    container_name: up-poller
    restart: unless-stopped
    image: golift/unifi-poller
    depends_on:
      - influxdb
      - grafana
    ports: 
      - '9130:9130'
    volumes:
      - /home/mukhtar/docker-unifi-poller/docker/unifi-poller:/config


up.conf

[unifi.defaults]
  url  = "https://10.2.0.10"
  user = "unifipoller"
  pass = "unifipoller"
  save_dpi = true

[influxdb]
  url  = "http://10.2.1.12:8086"
  user = "unifi"
  pass = "unifi"
  db   = "unifi"
  verify_ssl = false
[prometheus]
  disable = false
  # This controls on which ip and port /metrics is exported when mode is "prometheus".
  # This has no effect in other modes. Must contain a colon and port.
  http_listen = "0.0.0.0:9130"
  report_errors = false

**Comment by davidnewhall** [comment]
Can you try running poller directly on the ubuntu to host to rule out a docker problem?

**Comment by davidnewhall** [comment]
You can download a binary from the releases page (and not install a full package). You can run it from your home folder. Just need to pass it a config file.

**Comment by mukhtarhussainbaloch** [comment]
./unifi-poller.amd64.linux --config=./unifi-poller.conf
2021/03/03 13:00:43 [INFO] Loading Configuration File: ./docker-unifi-poller/docker/unifi-poller/unifi-poller.conf
2021/03/03 13:00:43 [INFO] UniFi Poller v2.0.1-787 Starting Up! PID: 57197
2021/03/03 13:00:45 [INFO] Found 1 site(s) on controller https://10.2.0.10: default (Default)
2021/03/03 13:00:45 [INFO] Configured UniFi Controller 1:
2021/03/03 13:00:45 [INFO]    => URL: https://10.2.0.10
2021/03/03 13:00:45 [INFO]    => Version: 
2021/03/03 13:00:45 [INFO]    => Username: unifipoller (has password: true)
2021/03/03 13:00:45 [INFO]    => Hash PII: false
2021/03/03 13:00:45 [INFO]    => Verify SSL: false
2021/03/03 13:00:45 [INFO]    => Save DPI: true
2021/03/03 13:00:45 [INFO]    => Save IDS: false
2021/03/03 13:00:45 [INFO]    => Save Sites: true
2021/03/03 13:00:45 [INFO] Everything checks out! Poller started, InfluxDB interval: 30s
2021/03/03 13:00:45 [INFO] Prometheus exported at https://0.0.0.0:9130/ - namespace: unifipoller
2021/03/03 13:03:13 [INFO] Re-authenticating to UniFi Controller: https://10.2.0.10
2021/03/03 13:03:18 [INFO] Re-authenticating to UniFi Controller: https://10.2.0.10
2021/03/03 13:03:21 [ERROR] metric fetch failed: unifi.GetClientsDPI(https://10.2.0.10): Post "https://10.2.0.10/proxy/network/api/s/default/stat/stadpi": EOF
2021/03/03 13:03:21 [INFO] UniFi Measurements Exported. Site: 0, Client: 0, UAP: 0, USG/UDM: 0, USW: 0, Descs: 0, Metrics: 0, Errs: 1, 0s: 0, Reqs/Total: 2m11.5755s / 2m11.5756s

**Comment by davidnewhall** [comment]
Very strange. I really don't know what else to try. I've never seen this before... it's having trouble getting a full/correct request response from the controller.

**Comment by davidnewhall** [comment]
Perhaps permissions? Maybe try with your user account instead of unifipoller, just to rule thatout.

**Comment by mukhtarhussainbaloch** [comment]
maybe there is something wrong with the UDM Pro controller side? the user has the read permission on the controller.

**Comment by mukhtarhussainbaloch** [comment]
I used my login user instead of the unifipoller user but the output is the same.

**Comment by mukhtarhussainbaloch** [comment]
I restarted the UDM pro multiple time and it is working now. I think the problem is with the UDM.

**Comment by davidnewhall** [comment]
Based on all the info I have available to me, I would not be surprised if this was the UDM acting strange. I remember one other person having a problem and a full reset of the unit fixed it.

**Comment by davidnewhall** [comment]
Let me know if you still need assistance!

**Comment by ChiefGyk** [comment]
I am actually experiencing the same issue on a Cloud Key Gen 2, it works great for a while then drops out and I get the same erros.

**Comment by davidnewhall** [comment]
https://github.com/unifi-poller/unifi-poller/issues/321
