### ISSUE TITLE
Ubuntu 18.04 Installation 

### ISSUE THREAD

**Issue by Lornero2020** [unifi-poller/unifi-poller#318]
Hi guys,

I am new to linux.

Followed the commands in the wiki and I am getting:

E: Unable to locate package https://golift.io
E: Couldn't find any package by glob 'https://golift.io'
E: Couldn't find any package by regex 'https://golift.io'
gpg: no valid OpenPGP data found.

Any ideas??

**Comment by davidnewhall** [comment]
Which command gave you that error?

**Comment by Lornero2020** [comment]
Hi David,

curl -s https://golift.io/gpgkey | sudo apt-key add -

I tried that line and it gave the errors above

**Comment by davidnewhall** [comment]
What operating system?

**Comment by Lornero2020** [comment]
Ubuntu 18.04

Yep I can see a bunch of them like grafana, influxdb, ubuntu cd image etc

**Comment by davidnewhall** [comment]
Run the command again. I'm pretty sure you typo'd something. The error looks like it come from `apt-get` not `curl` nor `apt-key`.

**Comment by Lornero2020** [comment]
I think I found the issue, I did not have curl installed. just installed curl libcurl4 packages will try now

**Comment by Lornero2020** [comment]
Bang! we got the OK

Thanks David, appreciate it mate!
