### ISSUE TITLE
Cloud Key G2 Reauthentication loop

### ISSUE THREAD

**Issue by ChiefGyk** [unifi-poller/unifi-poller#321]
I had a Grafana server drop out this morning from Unifi stats, and that's fine as I was swapping it out, and it was all perfect for about an hour, then authentication loops happened again. Same as on my Odroid HC2 I switched from. I am on a Raspberry Pi 4 2GB using Raspberry Pi OS, and I know it's not an issue of that as unifi poller ran for months on my Odroid. 
```
Mar 16 16:11:09 logging unifi-poller[1688]: 2021/03/16 16:11:09 [INFO] Re-authenticating to UniFi Controller: https://192.168.1.10:8443
Mar 16 16:11:09 logging unifi-poller[1688]: 2021/03/16 16:11:09 [ERROR] metric fetch for InfluxDB failed: re-authenticating to https://192.168.1.10:8443: unifi controller: Get "https://192.168.1.10:8443/": dial tcp 192.168.1.10:8443: connect: connection refused
Mar 16 16:11:09 logging unifi-poller[1688]: 2021/03/16 16:11:09 [INFO] UniFi Metrics Recorded. Sites: 0, Clients: 0, UAP: 0, USG/UDM: 0, USW: 0, IDS Events: 0, Points: 0, Fields: 0, Errs: 1, Elapsed: 3ms
Mar 16 16:11:39 logging unifi-poller[1688]: 2021/03/16 16:11:39 [INFO] Re-authenticating to UniFi Controller: https://192.168.1.10:8443
```

That's all I get.

You can see it was in fact working perfectly and then just randomly dropped out for no reason 
![image](https://user-images.githubusercontent.com/19499446/111374514-95f2a400-8673-11eb-99d5-2584aa2f9e41.png)

**Comment by davidnewhall** [comment]
Connection refused means there's not a controller at that IP and port combination. Try removing :8443 from the url.

**Comment by ChiefGyk** [comment]
> Connection refused means there's not a controller at that IP and port combination. Try removing :8443 from the url.

already tried that, and doing 443. All of them didn't work same results

**Comment by ChiefGyk** [comment]
Just for kicks and giggles I recreated a whole new local account on Unifi with read only permissions and same exact error. Cloudkey us fully up to date

**Comment by davidnewhall** [comment]
What URL do you put in your browser to access your controller?

**Comment by ChiefGyk** [comment]
I put a straight IP address, for me 192.168.1.10 and like I said it was working perfectly fine when it first started then dropped out and hasn't been able to reconnect since. Which is a shame as I used this for many months prior without issues. You can see the screenshot above as proof

**Comment by davidnewhall** [comment]
Can you show me the error poller gives you when you remove the `:8443`?

> and like I said it was working perfectly fine when it first started then dropped out and hasn't been able to reconnect since. Which is a shame as I used this for many months prior without issues. You can see the screenshot above as proof

I read everything you said and I'm trying to help you find the misconfiguration in your software.

**Comment by ChiefGyk** [comment]
> Can you show me the error poller gives you when you remove the `:8443`?
> 
> > and like I said it was working perfectly fine when it first started then dropped out and hasn't been able to reconnect since. Which is a shame as I used this for many months prior without issues. You can see the screenshot above as proof
> 
> I read everything you said and I'm trying to help you find the misconfiguration in your software.

This is what ti showed when I tried it earlier

`Mar 16 16:34:40 logging unifi-poller[2486]: 2021/03/16 16:34:40 [INFO]    => URL: https://192.168.1.10
Mar 16 16:34:40 logging unifi-poller[2486]: 2021/03/16 16:34:40 [INFO]    => Username: unifipoller (has password: true)
Mar 16 16:34:40 logging unifi-poller[2486]: 2021/03/16 16:34:40 [INFO]    => Hash PII: false
Mar 16 16:34:40 logging unifi-poller[2486]: 2021/03/16 16:34:40 [INFO]    => Verify SSL: false
Mar 16 16:34:40 logging unifi-poller[2486]: 2021/03/16 16:34:40 [INFO]    => Save DPI: false
Mar 16 16:34:40 logging unifi-poller[2486]: 2021/03/16 16:34:40 [INFO]    => Save IDS: false
Mar 16 16:34:40 logging unifi-poller[2486]: 2021/03/16 16:34:40 [INFO]    => Save Sites: true
Mar 16 16:34:40 logging unifi-poller[2486]: 2021/03/16 16:34:40 [INFO] Everything checks out! Poller started, InfluxDB interval: 30s
Mar 16 16:34:40 logging unifi-poller[2486]: 2021/03/16 16:34:40 [INFO] Prometheus exported at https://0.0.0.0:9130/ - namespace: unifipoller
Mar 16 16:35:10 logging unifi-poller[2486]: 2021/03/16 16:35:10 [INFO] Re-authenticating to UniFi Controller: https://192.168.1.10
Mar 16 16:35:10 logging unifi-poller[2486]: 2021/03/16 16:35:10 [ERROR] metric fetch for InfluxDB failed: re-authenticating to https://192.168.1.10: unifi controller: Get "https://192.168.1.10/": dial tcp 192.168.1.10:443: connect: connection refused
Mar 16 16:35:10 logging unifi-poller[2486]: 2021/03/16 16:35:10 [INFO] UniFi Metrics Recorded. Sites: 0, Clients: 0, UAP: 0, USG/UDM: 0, USW: 0, IDS Events: 0, Points: 0, Fields: 0, Errs: 1, Elapsed: 3ms
Mar 16 16:35:40 logging unifi-poller[2486]: 2021/03/16 16:35:40 [INFO] Re-authenticating to UniFi Controller: https://192.168.1.10
Mar 16 16:35:40 logging unifi-poller[2486]: 2021/03/16 16:35:40 [ERROR] metric fetch for InfluxDB failed: re-authenticating to https://192.168.1.10: unifi controller: Get "https://192.168.1.10/": dial tcp 192.168.1.10:443: connect: connection refused
Mar 16 16:35:40 logging unifi-poller[2486]: 2021/03/16 16:35:40 [INFO] UniFi Metrics Recorded. Sites: 0, Clients: 0, UAP: 0, USG/UDM: 0, USW: 0, IDS Events: 0, Points: 0, Fields: 0, Errs: 1, Elapsed: 3ms
`

**Comment by davidnewhall** [comment]
Thank you. These are the two errors I've seen (one from your first post, and one from your last):
1. `dial tcp 192.168.1.10:8443: connect: connection refused`
1. `dial tcp 192.168.1.10:443: connect: connection refused`

Normally I'd say "Your controller is not on that IP because none of the ports are open," but you already said you connect to it at that IP in your browser. That leads me to conclude there is a firewall preventing access.

**Comment by ChiefGyk** [comment]
Yup I just did a trace and it seems there was a rogue rule that for some reason only effected those two subnets. So it should be working now

**Comment by ChiefGyk** [comment]
So it works now but I did have to drop 8443 from the line as well to restore it.

**Comment by davidnewhall** [comment]
Yup, they changed the port on the UDM with that update you did.

**Comment by davidnewhall** [comment]
Let me know if I can help further!
