### ISSUE TITLE
influxdb.go:88: [ERROR] influxdb.Write(points):

### ISSUE THREAD

**Issue by WantedFreak** [unifi-poller/unifi-poller#322]
I'm not sure what is going on here. No data was shown in grafana so I looked in Unifi-pollers logs and found an html error 404 page.

I tired browsing the 2 urls being requested and it returned data fine.
https://192.168.0.101/proxy/network/api/s/default/stat/sta
https://192.168.0.101/proxy/network/api/s/default/stat/device

How can I find out where the 404 error is coming from?

```
2021/03/19 18:12:11 [INFO] Loading Configuration File: /config/unifi-poller.conf
2021/03/19 18:12:11.735415 start.go:81: [DEBUG] Debug Logging Enabled
2021/03/19 18:12:11.735528 start.go:84: [INFO] UniFi Poller v2.0.1-787 Starting Up! PID: 1
2021/03/19 18:12:11.735601 unifi.go:106: [DEBUG] Requesting https://192.168.0.101/ to determine API paths
2021/03/19 18:12:11.784282 unifi.go:135: [DEBUG] Using NEW UniFi controller API paths for https://192.168.0.101/
2021/03/19 18:12:11.784455 unifi.go:192: [DEBUG] Requesting https://192.168.0.101/api/auth/login, with params: true, cookies: 0
2021/03/19 18:12:12.145909 unifi.go:90: [DEBUG] Requested https://192.168.0.101/api/auth/login: elapsed 362ms, returned 1391 bytes
2021/03/19 18:12:12.146190 unifi.go:192: [DEBUG] Requesting https://192.168.0.101/proxy/network/status, with params: false, cookies: 1
2021/03/19 18:12:12.163637 unifi.go:163: [DEBUG] Requested https://192.168.0.101/proxy/network/status: elapsed 18ms, returned 76 bytes
2021/03/19 18:12:12.163861 input.go:92: [DEBUG] Authenticated with controller successfully, https://192.168.0.101
2021/03/19 18:12:12.163898 input.go:107: [DEBUG] Checking Controller Sites List
2021/03/19 18:12:12.164012 unifi.go:192: [DEBUG] Requesting https://192.168.0.101/proxy/network/api/stat/sites, with params: false, cookies: 1
2021/03/19 18:12:12.241070 unifi.go:163: [DEBUG] Requested https://192.168.0.101/proxy/network/api/stat/sites: elapsed 77ms, returned 2498 bytes
2021/03/19 18:12:12.242630 site.go:34: [DEBUG] Found 2 site(s): default,kp4tnk7c
2021/03/19 18:12:12.242696 input.go:119: [INFO] Found 2 site(s) on controller https://192.168.0.101: default (*), kp4tnk7c (*)
2021/03/19 18:12:12.242723 interface.go:51: [INFO] Configured UniFi Controller 1:
2021/03/19 18:12:12.242746 interface.go:63: [INFO]    => URL: https://192.168.0.101
2021/03/19 18:12:12.242770 interface.go:66: [INFO]    => Version: 
2021/03/19 18:12:12.242793 interface.go:69: [INFO]    => Username: unifipoller (has password: true)
2021/03/19 18:12:12.242814 interface.go:70: [INFO]    => Hash PII: false
2021/03/19 18:12:12.242834 interface.go:71: [INFO]    => Verify SSL: false
2021/03/19 18:12:12.242857 interface.go:72: [INFO]    => Save DPI: false
2021/03/19 18:12:12.242885 interface.go:73: [INFO]    => Save IDS: false
2021/03/19 18:12:12.242904 interface.go:74: [INFO]    => Save Sites: true
2021/03/19 18:12:12.243037 collector.go:105: [INFO] Prometheus config missing (or disabled), Prometheus HTTP listener disabled!
2021/03/19 18:12:12.243214 influxdb.go:73: [INFO] Everything checks out! Poller started, InfluxDB interval: 30s
2021/03/19 18:12:42.243691 unifi.go:192: [DEBUG] Requesting https://192.168.0.101/proxy/network/api/stat/sites, with params: false, cookies: 1
2021/03/19 18:12:42.353260 unifi.go:163: [DEBUG] Requested https://192.168.0.101/proxy/network/api/stat/sites: elapsed 110ms, returned 2498 bytes
2021/03/19 18:12:42.355676 site.go:34: [DEBUG] Found 2 site(s): default,kp4tnk7c
2021/03/19 18:12:42.355846 clients.go:17: [DEBUG] Polling Controller, retreiving UniFi Clients, site default (*) 
2021/03/19 18:12:42.356037 unifi.go:192: [DEBUG] Requesting https://192.168.0.101/proxy/network/api/s/default/stat/sta, with params: false, cookies: 1
2021/03/19 18:12:42.428118 unifi.go:163: [DEBUG] Requested https://192.168.0.101/proxy/network/api/s/default/stat/sta: elapsed 72ms, returned 5854 bytes
2021/03/19 18:12:42.432125 unifi.go:192: [DEBUG] Requesting https://192.168.0.101/proxy/network/api/s/default/stat/device, with params: false, cookies: 1
2021/03/19 18:12:42.532780 unifi.go:163: [DEBUG] Requested https://192.168.0.101/proxy/network/api/s/default/stat/device: elapsed 101ms, returned 34611 bytes
2021/03/19 18:12:42.537494 devices.go:47: [DEBUG] Unmarshalling Device Type: ugw, site * (default) 
2021/03/19 18:12:42.545882 devices.go:47: [DEBUG] Unmarshalling Device Type: uap, site * (default) 
2021/03/19 18:12:42.559436 devices.go:47: [DEBUG] Unmarshalling Device Type: usw, site * (default) 
2021/03/19 18:12:42.605284 influxdb.go:88: [ERROR] influxdb.Write(points): 
            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="utf-8">
                <title>404 Not Found</title>
            </head>
            <body align="center">
                <div role="main" align="center">
                    <h1>404: Not Found</h1>
                    <p>The requested resource could not be found.</p>
                    <hr />
                </div>
                <div role="contentinfo" align="center">
                    <small>Rocket</small>
                </div>
            </body>
            </html>
```

**Comment by davidnewhall** [comment]
It's coming from influxdb. What url did you put in for influx?

**Comment by WantedFreak** [comment]
> It's coming from influxdb. What url did you put in for influx?

:man_facepalming: I forgot to specify the port so it was haproxy responding with 404

All errors gone from the log but still not populating grafana, probably another miss in my config

**Comment by davidnewhall** [comment]
Does the log print out data about your devices and metrics now?

**Comment by WantedFreak** [comment]
It does, and the db is getting a bunch of data

**Comment by davidnewhall** [comment]
Check the data source in grafana. Make sure you didn't forget the port there too. If you imported the dashboard with the wrong data source, just import them again and you can pick again.

**Comment by WantedFreak** [comment]
Did not seem to help.
It does get some data, I can filter on some devices. See image
https://i.imgur.com/fcCq5x8.png

**Comment by davidnewhall** [comment]
Upgrade influx to 1.8.x.

**Comment by WantedFreak** [comment]
I upgraded from 1.6.x as default on Raspbian to 1.8.4 but did not make a difference

**Comment by davidnewhall** [comment]
Okay, can you show me the problem? The screenshot you provided looks pretty normal. A lot like mine:
![Screen Shot 2021-03-19 at 2 27 21 PM](https://user-images.githubusercontent.com/2402929/111843920-3dafe200-88bf-11eb-8cb4-658c03618ead.png)

**Comment by WantedFreak** [comment]
![](https://i.imgur.com/zWBGrtx.png)
![](https://i.imgur.com/mt7prqm.png)

**Comment by davidnewhall** [comment]
Well that sure is odd.  It's almost like it's looking at an old data source that's not getting any new data. If you change that to "last 7 days" does anything show up?

**Comment by WantedFreak** [comment]
Nothing shows up.

Grafana and Unifi-Poller both run in docker with the tag :latest. Influxdb 1.8.4 installed via apt. All on a Raspberry Pi 4 with Raspbian if that makes any difference

**Comment by davidnewhall** [comment]
Can you show me a screenshot of your data source for influx [in grafana]?

**Comment by davidnewhall** [comment]
Do any of the dashboards show data in the graphs?

**Comment by WantedFreak** [comment]
![](https://i.imgur.com/bD2oRIR.png)
No data in the graphs.
I just saw an error in the grafana log about paths not being writable, I'll look into that

**Comment by davidnewhall** [comment]
Is the `db` setting in poller's config also `unifi1` ?

**Comment by davidnewhall** [comment]
What version of Grafana are you running? At least 7.x.something? 
![Screen Shot 2021-03-19 at 2 41 58 PM](https://user-images.githubusercontent.com/2402929/111845033-515c4800-88c1-11eb-97e4-a9bc1ac5e2ea.png)

**Comment by davidnewhall** [comment]
Change access from `Browser` to `Server`.

**Comment by WantedFreak** [comment]
Apparently its running Grafana v6.7.6 (86c5fe3746)
I dont understand why as I pulled grafana:latest yesterday. I'll get 7.x and report back

**Comment by davidnewhall** [comment]
6 will probably work, but some of the panels will break. What you're experiencing doesn't seem like a grafana version issue, but it _could_ be. It feels/looks more like an influxdb issue, but if you're at 1.8.4 that shouldn't be it either. Try the Browser->Server change in the data source, and definitely get grafana 7. The latest version should work fine.

**Comment by WantedFreak** [comment]
Upgrading Grafana solved it!
Thank you for your help @davidnewhall! Hope you have a good weekend :smiley:

**Comment by davidnewhall** [comment]
Glad to hear it! Enjoy your new data!
