### ISSUE TITLE
update freebsd ports version to 2.1.0

### ISSUE THREAD

**Issue by antxxxx** [unifi-poller/unifi-poller#325]
Nothing for you to do, but I have created a patch to update the freebsd ports version to use 2.1.0 and so created this to track it.

Request for this is at https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=254482

**Comment by antxxxx** [comment]
This has now been accepted and merged so closing this issue

**Comment by davidnewhall** [comment]
Thank you again!
