### ISSUE TITLE
Run using Telegraf?

### ISSUE THREAD

**Issue by ytechie** [unifi-poller/unifi-poller#326]
I'm using Telegraf, which is a simple tool to enable running utilities like this on a schedule, and can output the data to Influx. If you're pulling data from a couple of places, it makes things pretty simple.

Is there a way to run the unifi-poller and just spit out the data to stdout? That would make it really easy to integrate into existing agents like Telegraf.

**Comment by davidnewhall** [comment]
There is not, but `curl` comes to mind..

**Comment by ytechie** [comment]
I'll give those commands a try. Thank you!

**Comment by davidnewhall** [comment]
fwiw, I wrote poller because telegraf, without additional scripts, can't do this by itself. So the choice was to write my own app or write a huge script to plug into telegraf. I chose app.

**Comment by ytechie** [comment]
Makes sense. Originally I was avoiding Telegraf, but I actually find it to be pretty simple and it abstracts the connection to Influx.

Here is an example sensor I wrote, which reads from a temp/humidity sensor on the Raspberry Pi:
https://github.com/ytechie/rv-iot/blob/telegraf-experiment/sensors/dht22/sensor.py

Then, in Telegraf, I just add this:
```
[[inputs.exec]]
  commands = [ "python3 /home/ubuntu/rv-iot/sensors/dht22/sensor.py" ]
  name_override = "dht22_sensor"
  data_format = "json"
```

**Comment by davidnewhall** [comment]
Pretty cool!
