### ISSUE TITLE
i/o timeout through Pi-hole

### ISSUE THREAD

**Issue by Lukas8299** [unifi-poller/unifi-poller#327]
I am using unifi-poller on my Rpi 4 with Portainer and a bridged network.
When i am using the unifi IP instead of Hostname in the ENV it is working fine.

`2021/03/23 11:04:51 [ERROR] metric fetch for InfluxDB failed: re-authenticating to https://unifi.local/: unifi controller: making request: Get "https://unifi.local/": dial tcp: lookup unifi.local on 192.168.14.2:53: read udp 172.17.0.6:51864->192.168.14.2:53: i/o timeout`

I have setup an Pi-hole on the same Rpi with macvlan network configuration.
My nslookup looks like this and the DNS resolution works fine on my other devices.

```
>nslookup unifi.local

Server:  pihole
Address:  192.168.14.2

Name:    unifi.local
Address:  192.168.14.1
```

**Comment by davidnewhall** [comment]
The application is having a problem reading the UDP reply from your DNS server. Looks like a network issue, but I don't know any enough any of your setup to really provide guidance. 

Why is it using `192.168.14.2` instead of the Docker DNS server?

**Comment by davidnewhall** [comment]
Hello, do you still need help with this?

**Comment by davidnewhall** [comment]
Please re-open if you still need assistance!
