### ISSUE TITLE
Grafana Client dashboard does not show wireless cameras or Amazon devices

### ISSUE THREAD

**Issue by bondskin** [unifi-poller/unifi-poller#331]
The existing Grafana dashboard for clients (https://grafana.com/grafana/dashboards/10418) has a great view to show cameras and Amazon devices but only if they are wired.

This makes sense looking at the SQL statement
"SELECT non_negative_derivative(sum("**wired-rx_bytes**"), 1s) AS "Rx", non_negative_derivative(sum("**wired-tx_bytes**"), 1s) AS "Tx" FROM "clients" WHERE "name" =~ /camera|cam$/ AND "site_name" =~ /^$Site$/ AND ("sw_name" =~ /^$Switch$/ OR "ap_name" =~ /^$AP$/) AND $timeFilter GROUP BY time($__interval), "name", "Mac""

However, it would be good if also wireless devices could be shown.
Is this possible?

**Comment by davidnewhall** [comment]
You can modify the queries to show anything you want. :) Definitely possible.

**Comment by bondskin** [comment]
> You can modify the queries to show anything you want. :) Definitely possible. 

Wow. Smart...

**Comment by davidnewhall** [comment]
![Screen Shot 2021-03-28 at 10 00 01 PM](https://user-images.githubusercontent.com/2402929/112789010-f3420a00-9010-11eb-9961-0d1e03364500.png)

**Comment by davidnewhall** [comment]
This should give you what you want, but I'm making assumptions on what you want since all you asked is if something is possible. I can't test this since I don't have any wireless cameras.
![Screen Shot 2021-03-28 at 10 12 15 PM](https://user-images.githubusercontent.com/2402929/112789766-a8c18d00-9012-11eb-8ed5-f534cd622742.png)

**Comment by bondskin** [comment]
thanks @davidnewhall , much appreciated.
It seems that each network interface is reported separately, (e.g. Apple TV comes with wireless and wired interface)

Having two queries work indeed but each interface is shown separately and not aggregated (which might also be right, based on the use case)

<img width="678" alt="Bildschirmfoto 2021-04-03 um 16 34 40" src="https://user-images.githubusercontent.com/55050117/113481579-a2139980-949a-11eb-87e6-9c41f0351c79.png">

**Comment by davidnewhall** [comment]
Correct. Each interface is a separate device to your network. You can do more trickery to combine them in the influx query, but it's not something I've ever tried, and I find it sufficient to have them displayed independently. On another panel I add `w` (to the alias) for wireless devices and `e` for ethernet-connected devices.  This helps distinguish them.

Please open another issue if I can help further!
