### ISSUE TITLE
Site_name discrepancy

### ISSUE THREAD

**Issue by qistoph** [unifi-poller/unifi-poller#341]
The values for the InfluxDB UAP Dashboard variable `Site` are extracted with
```
show tag values from "uap" with key="site_name" where source =~ /$Controller$/
```

On my InfluxDB this results in:
```
> show tag values from "uap" with key="site_name"
name: uap
key       value
---       -----
site_name default
```

The graph queries use this value (`default`) as condition for the `site_name` value of `clients`.

This mismatches however with the values I find in my `clients` measurement:
```
> show tag values from clients with key="site_name"
name: clients
key       value
---       -----
site_name Sitename (default)
```

I believe this looks like an issue with unifi-poller. I apologize for creating an issue if this is just an error in my configuration.

**Comment by davidnewhall** [comment]
Is all of this to say your panels are blank? ie. what's the symptom caused by the issue you're reporting? Are you using a UDM? If so, this may be related to #336 where they apparently removed the ability to set a site description?

What you're describing sounds like it would break everyone, but this is the first I've heard of a mismatch in these variables.

From my InfluxDB:
```
>  show tag values from "uap" with key="site_name"
name: uap
key       value
---       -----
site_name Home (default)
```
```
> show tag values from clients with key="site_name"
name: clients
key       value
---       -----
site_name Home (default)
```

**Comment by davidnewhall** [comment]
sh%t. This is a bug. https://github.com/unifi-poller/unifi/commit/b126f7e9cc4a84fd5bba0164037d8e0f487f738f#diff-b004b99dbb9c0b283495673e52d8054f7bb2d078391d8ed39f21eca89c63c562R139-R180

**Comment by qistoph** [comment]
> Is all of this to say your panels are blank? ie. what's the symptom caused by the issue you're reporting? 

A couple of panels are empty. The ones that are use `/$Site$/`. The ones that show up use `/$Site/`, without the match-at-end $. 

> Are you using a UDM? 
Nope

> If so, this may be related to #336 where they apparently removed the ability to set a site description?

I've seen that one, but thought my issues is different. 

> What you're describing sounds like it would break everyone, but this is the first I've heard of a mismatch in these variables.

That kinda surprised me too. 

If there's anything else that I could provide or look into, please let me know.

**Comment by davidnewhall** [comment]
What OS are you running on? I'd like to send you a test build to try.

**Comment by qistoph** [comment]
I'm running everything on docker; unifi controller, unifi-poller, influxdb and grafana.

**Comment by davidnewhall** [comment]
Okay, please try the tag `unstable`. Example:
```shell
docker pull golift/unifi-poller:unstable
```

This should [fix it...](https://github.com/unifi-poller/unifi-poller/compare/unstable?expand=1) Please let me know!  (and sorry, Docker took a really long time to[ build that..](https://hub.docker.com/repository/registry-1.docker.io/golift/unifi-poller/builds/628191cf-88ec-4585-8f0d-18af2cd50d05))

**Comment by qistoph** [comment]
Yup, that fixed it. Dashboard is looking good and the `uap` measurement how also has the correct site_name:
```
> show tag values from "uap" with key="site_name"
name: uap
key       value
---       -----
site_name Sitename (default)
site_name default
```

**Comment by davidnewhall** [comment]
A new release is building now. In an hour or two you may set put `unstable` back to `latest`. Thank you for this report!

**Comment by qistoph** [comment]
Thanks for the quick fixing! 👍
