### ISSUE TITLE
Docker image missing version info

### ISSUE THREAD

**Issue by SuperQ** [unifi-poller/unifi-poller#343]
When I upgraded from 2.0.1 to `:latest`, the build info is now empty.

```
# HELP unifipoller_build_info A metric with a constant '1' value labeled by version, revision, branch, and goversion from which unifipoller was built.
# TYPE unifipoller_build_info gauge
unifipoller_build_info{branch="",goversion="go1.16.3",revision="",version=""} 1
```

**Comment by davidnewhall** [comment]
Does this rely on https://github.com/prometheus/common/tree/main/version ?

**Comment by davidnewhall** [comment]
Aye. it does. rip. Added it back....

**Comment by davidnewhall** [comment]
It's going to take docker an hour to build a new `master` tag to try. In the meantime, I built it locally and pushed it here:
```
twitchcaptain/unifi-poller:latest
```

This is fixed...

**Comment by SuperQ** [comment]
No rush, I'll test when it's ready.

**Comment by SuperQ** [comment]
Confirmed, `golift/unifi-poller:master` returns the version strings.

```
unifipoller_build_info{branch="master (48cd12d)",goversion="go1.16.3",revision="885",version="2.1.3"} 1
```

**Comment by davidnewhall** [comment]
I'll try to get a new version released in the next week or two so this is more official. Thank you for letting me know about this!
