### ISSUE TITLE
repository do not include a Release

### ISSUE THREAD

**Issue by flopp999** [unifi-poller/unifi-poller#348]
This morning I got an error that bintray was not found.
Change repo to packagecloud but I got an error here as well.

`The repository 'https://packagecloud.io/golift/pkgs/debian buster Release' does not have a Release file`

I have downloaded and add the gpg key for packagecloud

what have I missed?

**Comment by davidnewhall** [comment]
`buster` is not the release where the packages are located. Which directions did you follow to install the repo? (I may need to fix/update something)

**Comment by davidnewhall** [comment]
Try this. https://unifipoller.com/docs/install/linux

Still curious if I need to update something!

**Comment by flopp999** [comment]
I was using this https://packagecloud.io/golift/pkgs/install
Maybe totally wrong :)

Now I use this `deb https://packagecloud.io/golift/pkgs/ubuntu focal main` and it worked fine

**Comment by davidnewhall** [comment]
Thank you. I'll see if package cloud can change that, or give me control over it.
