### ISSUE TITLE
Data Transfer by Category broken in UniFi-Poller: Network Sites - InfluxDB dashboard?

### ISSUE THREAD

**Issue by FreakZAR** [unifi-poller/unifi-poller#353]
I'm looking at the Network Sites Grafana dashboard and the Data Transfer by Category is showing up empty.

I used the Grafana and InfluxDB's explorers but cannot find the data with category as tag.

Is this perhaps broken?

My setup:
Unifi Poller 2.1.3
Inifi Controller 6.2.23
InfluxDB 4.1.0

I don't think it's a Grafana issue. Seems the poller is not fetching the data and thus not storing it in InfluxDB.

**Comment by bondskin** [comment]
Empty here, too. But I have disabled the DPI option in Unifi Poller

 save_dpi   = false

**Comment by FreakZAR** [comment]
I'm looking for the Unifi Statistics info. Want to visualize some of that with Grafana. I have defaults installed. Not sure if the poller actually fetches the data.

**Comment by FreakZAR** [comment]
I had to set UP_UNIFI_DEFAULT_SAVE_DPI = TRUE. Working now
