### ISSUE TITLE
Kubernetes examples shouldn't use ConfigMap

### ISSUE THREAD

**Issue by paulfantom** [unifi-poller/unifi-poller#355]
Kubernetes examples use `ConfigMap` when configuration holds sensitive data (user and password to unifi). Instead it would be good to use `Secret`.

**Comment by davidnewhall** [comment]
Can you provide a link to the thing you're suggesting needs to be fixed?

**Comment by paulfantom** [comment]
Sure:
- credentials I have in mind: https://github.com/unifi-poller/unifi-poller/blob/master/examples/k8s_unifi_poller.yaml#L75-L76
- whole thing: https://github.com/unifi-poller/unifi-poller/blob/master/examples/k8s_unifi_poller.yaml#L49-L82

I can create a PR to fix this if you want ;)

**Comment by davidnewhall** [comment]
Gotcha. Yeah I know zero about kubernetes and forgot about that example. It was added by @michaelpietzsch in #337. Maybe he has some input here? I'm open to further pull requests. Thanks!

**Comment by michaelpietzsch** [comment]
@paulfantom you are totally right. The proper way to do this is with secrets. I didn't implement it in this first iteration. Would you care to do a pull request ? I'd be happy to test and review it !

**Comment by davidnewhall** [comment]
Thank you so much gentlemen!
