### ISSUE TITLE
Does not work with Grafana 8

### ISSUE THREAD

**Issue by bondskin** [unifi-poller/unifi-poller#358]
Running Grafana on my Raspberry Pi4 (64bit), the upgrade from v7.5.7 to v8 breaks the Unifi-poller Dashboards in Grafana

downgrading to v7.x fixes it

**Comment by obzbdc** [comment]
Update to Grafana 8.0.1 fixes it.
It's to do with the collapsed panels in the dashboard, see https://github.com/grafana/grafana/issues/34788#issuecomment-856867729 for details.

**Comment by bondskin** [comment]
confirmed

**Comment by davidnewhall** [comment]
Thank you both!
