### ISSUE TITLE
Feature Request: Firewall/Connection Dashboard

### ISSUE THREAD

**Issue by MwC-Trexx** [unifi-poller/unifi-poller#91]
I would love to see a dashboard panel showing firewall/connection status type information.   Basically source/target/port/etc. table type information.   That is one area where even my old Asus router running 3rd party firmware (Merlin) was better than my fancy Unifi.

**Comment by davidnewhall** [comment]
Time series database just really isn't the best place for log entries. I could certainly do it, and I wrote code for IDS/IPS to do exactly that. I'm not terribly fond of it and I think UniFi should make this data easier to consume. The best method I can recommend would be to point your controller at a syslog server and put the data into elastic search or something similar.

I'll poke around the API a bit to see if this data is easy to extract; usually is, and go from there. I may be able to make it an option to collect and store firewall logs.

**Comment by MwC-Trexx** [comment]
Yeah.. I hear ya.  I really wish Unifi would add that capability into the controller/usg and then it becomes a non-issue.  While they do so well with many things some of the basic's like VPN/FW monitoring/etc. seem so lacking.  

I know UDM line is supposed to help make that easier moving to arm based hw, but still annoying not having it.  Thanks for digging into this for me.

**Comment by davidnewhall** [comment]
Going to link this here for others to catch up: https://community.ui.com/questions/Where-can-I-see-Active-WAN-Connections-IPs/2d484c88-14b1-4b09-b18e-0211a22a24ed

Lets chat some more. You can find me on discord. ;) I don't think this data is easy to obtain from the API, but I can probably give you some other tricks that you may be able to work on.

**Comment by davidnewhall** [comment]
I'm going to use this issue to remind me to add more IDS/IPS data. The juicy stuff is entirely missing.

**Comment by davidnewhall** [comment]
I finally spent the time to understand and build code to collect the DPI data. I'm using those changes to close this "reminder." As for a "firewall dashboard with statuses" - that's just not what a time series database is for and poller is the wrong application to garner that data. Sorry about that. :(

**Comment by MwC-Trexx** [comment]
Hey David - thanks for all your work on this. Have a happy holidays.

--
